
project_id = "wwhqbjrhbajpabfdwnip"

[functions.create-credit-checkout]
verify_jwt = true

[functions.webhook-credit-purchase]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = true

[functions.send-weekly-digest]
verify_jwt = true
