
project_id = "wwhqbjrhbajpabfdwnip"

[functions.create-checkout]
verify_jwt = true

[functions.create-free-post]
verify_jwt = true

[functions.toggle-auto-renew]
verify_jwt = true

[functions.verify-checkout-session]
verify_jwt = true
