
project_id = "wwhqbjrhbajpabfdwnip"

[functions.partner-contact]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
tenant_id = "realtime-dev"

[studio]
enabled = true
port = 54324

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54329
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:3000", "https://emviapp-final.vercel.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[functions.create-job-checkout]
verify_jwt = true

[functions.create-free-post]
verify_jwt = true

[functions.verify-checkout-session]
verify_jwt = true

[functions.webhook-credit-purchase]
verify_jwt = false

[functions.create-salon-checkout]
verify_jwt = true

[functions.diamond-tier-request]
verify_jwt = true

[functions.create-credit-checkout]
verify_jwt = true

[functions.webhook-job-posting]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-webhook-handler]
verify_jwt = false

# Removed conflicting stripe-webhook-job function - using webhook-job-posting for proper flow

[functions.verify-payment]
verify_jwt = false

[functions.process-pending-salons]
verify_jwt = false

[functions.ai-image-generation]
verify_jwt = true

[functions.photo-analysis]
verify_jwt = true

[edge-runtime]
enabled = true
port = 54330

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.twilio-sms]
verify_jwt = false

[functions.jobs-sitemap]
verify_jwt = false

[functions.artists-sitemap]
verify_jwt = false
