
project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[functions]
enabled = true

[functions.create-checkout]
verify_jwt = true

[functions.create-free-post]
verify_jwt = true

[functions.verify-checkout-session]
verify_jwt = true

[auth]
enabled = true
