
project_id = "wwhqbjrhbajpabfdwnip"

[functions.create-checkout]
verify_jwt = true

[functions.create-free-post]
verify_jwt = true

[functions.verify-checkout-session]
verify_jwt = true

[functions.diamond-tier-request]
verify_jwt = true

[functions.webhook-credit-purchase]
verify_jwt = false

