-- Community Seeding Script
-- Create diverse, authentic community posts with comments
-- Backdated over 7-10 days for organic feel

-- First, let's create some test user profiles in the profiles table for variety
-- (These would typically be real users, but for seeding we'll create test profiles)

-- Personal Stories (English & Vietnamese)
INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Just finished my first full set of gel extensions on myself! 💅 Started nail art 6 months ago as a stress reliever during college, now I''m thinking about making this my career. The feeling when you create something beautiful with your hands is unmatched ✨ #NailArtJourney #SelfTaught #DreamsBigger', 'story', 'nails', ARRAY['nail-art', 'gel-extensions', 'self-taught'], ARRAY['https://images.unsplash.com/photo-1649972904349-6e44c42644a7'], 24, 8, false, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Hôm nay mình thử technique mới để làm lông mi cong tự nhiên mà không cần mascara! 😍 Dùng heated eyelash curler + setting spray trước khi curl. Hiệu quả bất ngờ luôn các bạn ơi! Lông mi cong suốt 8 tiếng mà vẫn mềm mại. Ai muốn thử thì nhắn mình nhé 💕 #BeautyTipsVN #LashHacks', 'story', 'lashes', ARRAY['lash-tips', 'vietnamese-beauty'], ARRAY[], 31, 12, false, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Had the worst hair disaster last week - tried to bleach my hair at home and it turned ORANGE 🙈 Rushed to my colorist friend who spent 4 hours fixing it. Now I have the most gorgeous ashy blonde! Lesson learned: some things are worth paying professionals for. But also grateful for amazing friends who save the day 💛 #HairDisaster #FriendshipGoals #ProfessionalColorist', 'story', 'hair', ARRAY['hair-color', 'salon-life', 'friendship'], ARRAY[], 45, 15, false, NOW() - INTERVAL '5 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Mình vừa mở salon nhỏ tại quận 7! 🎉 Từ việc học nail art ở nhà đến có studio riêng, hành trình 2 năm đầy thử thách nhưng xứng đáng! Cảm ơn tất cả khách hàng đã tin tưởng và ủng hộ từ những ngày đầu. Special opening promotion: 30% off cho tất cả dịch vụ tuần đầu! #NewSalon #VietNailArt #SalonLife #District7', 'story', 'business', ARRAY['new-salon', 'vietnamese-business', 'grand-opening'], ARRAY['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'], 67, 23, true, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Client transformation today has me emotional 🥺💕 She came in feeling insecure about her eyebrows after over-plucking in the 2000s (we''ve all been there!). 2 hours later with microblading and she was literally crying happy tears. This is why I love what I do - it''s not just about beauty, it''s about confidence and helping people feel like the best version of themselves ✨ #MicrobladingMagic #ClientLove #ConfidenceBoost', 'story', 'brows', ARRAY['microblading', 'client-transformation', 'confidence'], ARRAY[], 89, 31, false, NOW() - INTERVAL '4 days');

-- Pro Tips
INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '🔥 PRO TIP: Want your gel polish to last 3+ weeks without chipping? Here''s my secret formula:\n\n1. Dehydrate nails with 70% alcohol (not acetone!)\n2. Ultra-thin base coat - cure 30 seconds\n3. Color in 3 THIN coats, curing between each\n4. Cap the free edge with top coat\n5. Cuticle oil daily (this is KEY!)\n\nBonus: Use a glass file for shaping - it seals the nail edge better than emery boards! Your clients will notice the difference 💅 #ProTips #GelPolish #NailTech', 'tip', 'nails', ARRAY['gel-polish', 'pro-tips', 'nail-tech'], ARRAY[], 156, 42, true, NOW() - INTERVAL '6 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Makeup artists - stop using setting spray wrong! ❌ Most people spray their face directly. ✅ Spray your beauty sponge/brush instead, THEN blend. This technique:\n\n• Prevents makeup from moving\n• Creates airbrushed finish\n• Makes foundation last 12+ hours\n• No more cakey look\n\nTried this on 50+ clients - 100% success rate! Game changer for oily skin especially 🙌 #MakeupTips #SettingSpray #ProMUA', 'tip', 'makeup', ARRAY['makeup-tips', 'setting-spray', 'pro-techniques'], ARRAY[], 203, 67, true, NOW() - INTERVAL '7 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Lash extension retention secret that doubled my client booking rate 👀\n\nStop using oil-free everything! Here''s what actually works:\n• Oil-free cleanser on lash line only\n• Gentle oil massage on face (avoiding lashes)\n• Sleep on silk pillowcase\n• Brush lashes upward every morning\n• Professional cleaning every 2 weeks\n\nMy clients now get 6-8 weeks between fills instead of 2-3! Happy clients = repeat business 💰 #LashExtensions #RetentionTips #LashTech', 'tip', 'lashes', ARRAY['lash-extensions', 'retention', 'client-care'], ARRAY[], 134, 38, false, NOW() - INTERVAL '8 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Bí quyết tạo kiểu tóc cong tự nhiên mà không cần máy uốn! 💁‍♀️\n\n🌸 Tóc ướt: Braid loosely (tết lỏng) trước khi ngủ\n🌸 Sáng mai: Gỡ bỏ, xịt sea salt spray\n🌸 Vuốt nhẹ bằng tay (không chải!)\n🌸 Finish với hair oil ở đuôi tóc\n\nKết quả: Sóng tự nhiên như nàng tiên cá! Phù hợp mọi độ dài tóc. Mình làm thế này 3 năm rồi, tóc khỏe mà đẹp ✨ #HairTipsVN #NaturalWaves #VietnameseHair', 'tip', 'hair', ARRAY['hair-styling', 'natural-waves', 'vietnamese-tips'], ARRAY[], 98, 29, false, NOW() - INTERVAL '9 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'SKINCARE GAME CHANGER: The 7-skin method that cleared my hormonal acne 🌟\n\nForget expensive serums - this Korean technique using ONE toner:\n• Apply toner with palms\n• Pat gently until absorbed\n• Repeat 7 times\n• Follow with moisturizer\n\nAfter 30 days my skin texture completely transformed. Key is using alcohol-free, hydrating toner. Takes 5 minutes but worth every second! #KoreanSkincare #SevenSkin #AcneTips', 'tip', 'skincare', ARRAY['korean-skincare', 'seven-skin', 'acne-tips'], ARRAY[], 267, 84, false, NOW() - INTERVAL '10 days');

-- Showcases with Photos
INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '✨ BRIDAL GLAM SHOWCASE ✨\n\n6 hours of artistry for this beautiful bride! Created a timeless look that photographs beautifully and lasts all day. Used airbrush foundation, hand-placed individual lashes, and custom lip color mixed to match her dress.\n\nThe glow when she saw herself in the mirror... pure magic 💕 Nothing beats making someone feel absolutely radiant on their special day!\n\n#BridalMakeup #WeddingGlam #MakeupArtist #BrideMakeup', 'showcase', 'makeup', ARRAY['bridal-makeup', 'wedding', 'airbrush'], ARRAY['https://images.unsplash.com/photo-1649972904349-6e44c42644a7'], 189, 56, true, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '🌈 RAINBOW OMBRÉ NAILS 🌈\n\nSpent 4 hours perfecting this gradient technique! Each nail transitions through 7 colors using a tiny makeup sponge and steady hands. The key is working fast before the polish dries and blending while it''s still tacky.\n\nClient wanted something bold for Pride month - mission accomplished! 🏳️‍🌈\n\n#RainbowNails #PrideNails #OmbreNails #NailArt #GelNails', 'showcase', 'nails', ARRAY['rainbow-nails', 'ombre', 'pride', 'nail-art'], ARRAY['https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5'], 234, 72, false, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'TRANSFORMATION TUESDAY! 💫\n\nFrom damaged, over-processed hair to healthy, glossy locks! This client had been bleaching at home for months. We did:\n\n🔹 Olaplex treatment series\n🔹 Cut off 6 inches of damage  \n🔹 Toned to perfect ash blonde\n🔹 Glossing treatment for shine\n\nSometimes less is more - health over length always! 💛\n\n#HairTransformation #OlaplexTreatment #HealthyHair #BlondeHair #HairRecovery', 'showcase', 'hair', ARRAY['hair-transformation', 'olaplex', 'blonde-hair', 'hair-health'], ARRAY['https://images.unsplash.com/photo-1506744038136-46273834b3fb'], 167, 43, false, NOW() - INTERVAL '5 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Volume lash set perfection! 👁️✨\n\n3D volume using 0.03 lashes - 5-7 fans per natural lash. This technique creates incredible fullness while staying lightweight. Client has sparse natural lashes but look at this transformation!\n\nUsed C curl for natural eye shape, varied lengths 8-12mm. Total application time: 2.5 hours. She''s been wearing them for 4 weeks and they still look fresh!\n\n#VolumeLashes #3DLashes #LashExtensions #EyeLashes #LashArt', 'showcase', 'lashes', ARRAY['volume-lashes', '3d-lashes', 'lash-extensions'], ARRAY['https://images.unsplash.com/photo-1582562124811-c09040d0a901'], 145, 38, false, NOW() - INTERVAL '7 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Microblading masterpiece! 🎨\n\nNatural hair-stroke technique for this client who lost her brows due to alopecia. We designed a shape that complements her bone structure perfectly. Used golden brown pigment to match her natural hair color.\n\nSeeing her confidence return is why I love this art form! 6 weeks healed, touch-up complete. These will last 1-2 years with proper care.\n\n#Microblading #BrowArt #AlopeciaSupport #EyebrowDesign #PermanentMakeup', 'showcase', 'brows', ARRAY['microblading', 'brow-art', 'alopecia', 'permanent-makeup'], ARRAY['https://images.unsplash.com/photo-1649972904349-6e44c42644a7'], 201, 67, false, NOW() - INTERVAL '9 days');

-- Questions/Polls
INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'POLL: What''s your go-to nail shape for clients? 💅\n\nI''ve been doing more coffin/ballerina shapes lately but wondering what everyone else is seeing as trending! Drop your top 3 in comments:\n\n🔸 Oval\n🔸 Round  \n🔸 Square\n🔸 Coffin/Ballerina\n🔸 Almond\n🔸 Stiletto\n\nAlso curious - do you charge extra for certain shapes? #NailShapes #NailTechLife #Poll', 'poll', 'nails', ARRAY['nail-shapes', 'nail-tech', 'poll'], ARRAY[], 67, 34, false, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'HELP! Lash retention issues 😭\n\nMy clients are losing 50% of their lashes within 2 weeks. I''m using quality adhesive, proper humidity (45-55%), good isolation... what am I missing?\n\nDetails:\n• 3 years experience\n• Classic and volume\n• Clients follow aftercare\n• Using speed-drying fans\n\nHas anyone dealt with this? Could it be seasonal? Product issue? I''m stumped! #LashProblems #LashRetention #HelpNeeded', 'question', 'lashes', ARRAY['lash-problems', 'retention-issues', 'help-needed'], ARRAY[], 43, 28, false, NOW() - INTERVAL '4 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Makeup artists: How do you handle difficult clients? 🤔\n\nHad a bride last week who wanted to completely change her look 30 minutes before ceremony. She saw a Pinterest photo and insisted we recreate it exactly (it was a completely different skin tone and face shape).\n\nHow do you educate clients about realistic expectations while keeping them happy? Would love to hear your strategies! #MakeupArtist #ClientManagement #BridalStruggles', 'question', 'makeup', ARRAY['client-management', 'bridal-makeup', 'difficult-clients'], ARRAY[], 78, 51, false, NOW() - INTERVAL '6 days');

-- @AI Ask/Share Posts
INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Asked @AI about fixing yellow-toned highlights and got this amazing advice! 🤯\n\n"Use a purple shampoo 2x/week, then tone with ash-based color 2 levels lighter than desired result. For stubborn brassiness, mix toner with 10vol developer and process for 15-20 minutes. Always deep condition after toning to prevent dryness."\n\nTried this on my client today and WOW! The yellow completely disappeared. AI is getting scary good at hair advice! 💜\n\n✨ Powered by EmviApp AI\n\n#AIBeautyTips #HairToning #YellowHair #AshBlonde', 'ai-tip', 'hair', ARRAY['ai-tips', 'hair-toning', 'purple-shampoo'], ARRAY[], 124, 47, false, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '@AI just blew my mind with this nail art technique! Asked about creating perfect French tips and got this:\n\n"Use striping tape as a guide, apply base color first, remove tape while polish is slightly tacky for crisp lines. For curved French tips, use hole reinforcement stickers as templates. Clean up with small brush dipped in acetone."\n\nBeen doing nails for 5 years and never thought of the hole reinforcement trick! Tried it today - cleanest French tips ever! 🤍\n\n✨ Powered by EmviApp AI\n\n#AITips #FrenchNails #NailArt #NailHacks', 'ai-tip', 'nails', ARRAY['ai-tips', 'french-nails', 'nail-hacks'], ARRAY[], 89, 32, false, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Hỏi @AI về cách làm môi không khô khi đeo khẩu trang, được response quá hay! 🎭\n\n"Sử dụng lip primer trước khi thoa son, chọn liquid lipstick dạng transfer-proof, dusting powder nhẹ qua giấy tissue, rồi spray setting spray từ xa 20cm. Kết thúc bằng lip balm ở góc môi để không bị khô."\n\nThử ngay hôm nay - đeo khẩu trang 8 tiếng mà son vẫn đẹp! AI hiểu beauty Việt Nam quá! 💋\n\n✨ Powered by EmviApp AI\n\n#AITips #KhauTrang #SonKhongTroi #VietnameseBeauty', 'ai-tip', 'makeup', ARRAY['ai-tips', 'mask-makeup', 'vietnamese-beauty'], ARRAY[], 156, 63, false, NOW() - INTERVAL '5 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Mind = BLOWN! 🤯 Asked @AI about lash mapping for hooded eyes and got the most detailed response:\n\n"For hooded eyes, use shorter lengths (6-8mm) on inner corner, gradually increase to 10-12mm at center, then decrease slightly. Use C or CC curl to lift the hood. Focus volume in the center to create opening effect. Avoid dramatic lengths that will hit the hood when eyes are open."\n\nThis is exactly what I learned in my $500 advanced course! AI is becoming the ultimate beauty educator 🎓\n\n✨ Powered by EmviApp AI\n\n#AIEducation #LashMapping #HoodedEyes #LashTech', 'ai-tip', 'lashes', ARRAY['ai-education', 'lash-mapping', 'hooded-eyes'], ARRAY[], 198, 71, true, NOW() - INTERVAL '7 days');

-- Challenge/Contest Entries  
INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '🏆 SUMMER NEON CHALLENGE ENTRY! 🏆\n\nChallenge was to create the brightest, most eye-catching neon design... I think I nailed it! 💥 Used 6 different neon gel polishes with glow-in-the-dark top coat. Each nail has a different geometric pattern inspired by 80s Memphis design.\n\nTook 3 hours and my client LOVES them! Perfect for festival season 🎪 Who else is joining the challenge?\n\n#SummerNeonChallenge #NeonNails #FestivalNails #GeometricNails #80sVibes', 'challenge', 'nails', ARRAY['neon-challenge', 'neon-nails', 'festival-nails'], ARRAY['https://images.unsplash.com/photo-1649972904349-6e44c42644a7'], 167, 45, false, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'SMOKY EYE CHALLENGE SUBMISSION! 👁️‍🗨️\n\nThe challenge: Create a wearable smoky eye using ONLY drugstore products under $50 total. Here''s my look using:\n\n• L''Oreal eyeshadow palette ($12)\n• Maybelline gel liner ($8)  \n• CoverGirl mascara ($7)\n• ELF brushes ($15)\n\nTotal: $42! Proof you don''t need expensive makeup to create stunning looks. Technique > tools always! 💪\n\n#DrugstoreChallenge #SmokyEye #BudgetBeauty #MakeupChallenge', 'challenge', 'makeup', ARRAY['drugstore-challenge', 'smoky-eye', 'budget-beauty'], ARRAY['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'], 203, 68, false, NOW() - INTERVAL '8 days');

-- Now add comments to posts
-- Personal Stories Comments
INSERT INTO community_post_comments (id, post_id, user_id, content, likes_count, created_at) VALUES
(gen_random_uuid(), (SELECT id FROM community_posts WHERE content LIKE 'Just finished my first full set%' LIMIT 1), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Girl YES! That''s exactly how I started too 🙌 Follow your passion!', 5, NOW() - INTERVAL '1 day 12 hours'),
(gen_random_uuid(), (SELECT id FROM community_posts WHERE content LIKE 'Just finished my first full set%' LIMIT 1), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Beautiful work! Do you have any favorite tutorials to recommend?', 3, NOW() - INTERVAL '1 day 8 hours'),
(gen_random_uuid(), (SELECT id FROM community_posts WHERE content LIKE 'Just finished my first full set%' LIMIT 1), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'The shape is perfect! 😍 You''re definitely talented enough to go pro', 7, NOW() - INTERVAL '1 day 4 hours');

-- Add @AI mention in comments
INSERT INTO community_post_comments (id, post_id, user_id, content, likes_count, created_at) VALUES
(gen_random_uuid(), (SELECT id FROM community_posts WHERE content LIKE 'Hôm nay mình thử technique%' LIMIT 1), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Cảm ơn tip hay quá! @AI có technique nào khác cho lông mi ngắn không nhỉ?', 4, NOW() - INTERVAL '2 days 10 hours'),
(gen_random_uuid(), (SELECT id FROM community_posts WHERE content LIKE 'Hôm nay mình thử technique%' LIMIT 1), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Mình thử rồi, hiệu quả thật! Lông mi cong cả ngày 💕', 8, NOW() - INTERVAL '2 days 6 hours'),
(gen_random_uuid(), (SELECT id FROM community_posts WHERE content LIKE 'Hôm nay mình thử technique%' LIMIT 1), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Heated curler nào bạn dùng vậy? Mình đang tìm mua', 2, NOW() - INTERVAL '2 days 2 hours');