import React, { useState, useEffect, useCallback } from 'react';
import { Calendar as CalendarIcon } from "lucide-react";
import { Calendar } from "@/components/ui/calendar";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Slider } from "@/components/ui/slider";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/use-toast";
import { useTranslation } from "@/hooks/useTranslation";
import { useAuth } from "@/context/auth";
import { supabase } from "@/integrations/supabase/client";
import { format, addMinutes, isWithinInterval, set, parseISO } from 'date-fns';
import { utcToZonedTime, zonedTimeToUtc } from 'date-fns-tz';
import { Loader2 } from "lucide-react";
import { TimePicker } from "@/components/ui/time-picker";
import { DateRange } from 'react-day-picker';

// Define types
interface TimeSlot {
  id: string;
  start_time: string;
  end_time: string;
  is_available: boolean;
  day_of_week: number;
}

interface ArtistCalendarProps {
  artistId: string;
}

const ArtistCalendar: React.FC<ArtistCalendarProps> = ({ artistId }) => {
  const { t } = useTranslation();
  const { toast } = useToast();
  const { userProfile } = useAuth();

  // State variables
  const [date, setDate] = useState<Date | undefined>(new Date());
  const [timeSlots, setTimeSlots] = useState<TimeSlot[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [selectedTimeSlot, setSelectedTimeSlot] = useState<TimeSlot | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  const [isUpdating, setIsUpdating] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [selectedTimeSlotForCompletion, setSelectedTimeSlotForCompletion] = useState<TimeSlot | null>(null);
  const [isMarkingComplete, setIsMarkingComplete] = useState(false);
  const [isMarkingIncomplete, setIsMarkingIncomplete] = useState(false);
  const [isTimeSlotIncompleteDialogOpen, setIsTimeSlotIncompleteDialogOpen] = useState(false);
  const [selectedTimeSlotForIncompletion, setSelectedTimeSlotForIncompletion] = useState<TimeSlot | null>(null);
  const [isSavingNotes, setIsSavingNotes] = useState(false);
  const [notes, setNotes] = useState('');
  const [selectedDateRange, setSelectedDateRange] = useState<DateRange | undefined>(undefined);
  const [isBulkUpdating, setIsBulkUpdating] = useState(false);
  const [bulkStartTime, setBulkStartTime] = useState<Date | null>(null);
  const [bulkEndTime, setBulkEndTime] = useState<Date | null>(null);
  const [isBulkAvailable, setIsBulkAvailable] = useState(true);
  const [isBulkUpdatingAvailability, setIsBulkUpdatingAvailability] = useState(false);
  const [isBulkDeleting, setIsBulkDeleting] = useState(false);
  const [isBulkDeleteConfirmationOpen, setIsBulkDeleteConfirmationOpen] = useState(false);
  const [isBulkCompleteConfirmationOpen, setIsBulkCompleteConfirmationOpen] = useState(false);
  const [isBulkIncompleteConfirmationOpen, setIsBulkIncompleteConfirmationOpen] = useState(false);
  const [isBulkMarkingComplete, setIsBulkMarkingComplete] = useState(false);
  const [isBulkMarkingIncomplete, setIsBulkMarkingIncomplete] = useState(false);
  const [isBulkCompleting, setIsBulkCompleting] = useState(false);
  const [isBulkIncompleting, setIsBulkIncompleting] = useState(false);
  const [isBulkCompletingAll, setIsBulkCompletingAll] = useState(false);
  const [isBulkIncompletingAll, setIsBulkIncompletingAll] = useState(false);
  const [isBulkCompleteAllConfirmationOpen, setIsBulkCompleteAllConfirmationOpen] = useState(false);
  const [isBulkIncompleteAllConfirmationOpen, setIsBulkIncompleteAllConfirmationOpen] = useState(false);
  const [isBulkCompleteAllConfirmationLoading, setIsBulkCompleteAllConfirmationLoading] = useState(false);
  const [isBulkIncompleteAllConfirmationLoading, setIsBulkIncompleteAllConfirmationLoading] = useState(false);
  const [isBulkCompletingAllLoading, setIsBulkCompletingAllLoading] = useState(false);
  const [isBulkIncompletingAllLoading, setIsBulkIncompletingAllLoading] = useState(false);
  const [isBulkCompletingLoading, setIsBulkCompletingLoading] = useState(false);
  const [isBulkIncompletingLoading, setIsBulkIncompletingLoading] = useState(false);
  const [isBulkDeleteLoading, setIsBulkDeleteLoading] = useState(false);
  const [isBulkDeleteAllLoading, setIsBulkDeleteAllLoading] = useState(false);
  const [isBulkDeleteAllConfirmationOpen, setIsBulkDeleteAllConfirmationOpen] = useState(false);
  const [isBulkDeletingAll, setIsBulkDeletingAll] = useState(false);
  const [isBulkDeletingAllLoading, setIsBulkDeletingAllLoading] = useState(false);
  const [isBulkDeleteConfirmationLoading, setIsBulkDeleteConfirmationLoading] = useState(false);
  const [isBulkDeleteAllConfirmationLoading, setIsBulkDeleteAllConfirmationLoading] = useState(false);
  const [isBulkDeleteAllConfirmationOpenLoading, setIsBulkDeleteAllConfirmationOpenLoading] = useState(false);
  const [isBulkDeleteConfirmationOpenLoading, setIsBulkDeleteConfirmationOpenLoading] = useState(false);
  const [isBulkDeleteAllLoadingAll, setIsBulkDeleteAllLoadingAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAll, setIsBulkDeleteAllConfirmationOpenAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAll, setIsBulkDeleteAllConfirmationLoadingAll] = useState(false);
  const [isBulkDeletingAllAll, setIsBulkDeletingAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAll, setIsBulkDeleteAllLoadingAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAll, setIsBulkDeleteAllConfirmationOpenAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAll, setIsBulkDeleteAllConfirmationLoadingAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAll, setIsBulkDeleteAllLoadingAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAll, setIsBulkDeleteAllConfirmationOpenAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAll, setIsBulkDeletingAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAll, setIsBulkDeletingAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllConfirmationLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeletingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAllLoadingAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll] = useState(false);
  const [isBulkDeleteAllConfirmationOpenAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAllAll, setIsBulkDeleteAll
