import React, { useState, useEffect } from 'react';
import { Calendar, momentLocalizer } from 'react-big-calendar';
import moment from 'moment';
import 'react-big-calendar/lib/css/react-big-calendar.css';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ChevronLeft, ChevronRight, Plus, Ban, CalendarIcon, Clock, User, Edit, Trash2, Check, X } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { format, parseISO, addHours, isAfter, isBefore, getDay } from 'date-fns';
import { useToast } from '@/components/ui/use-toast';

// Add this interface to include the is_manual property
interface Appointment {
  id: string;
  artist_id: string;
  customer_id: string;
  customer_name: string;
  customer_email: string;
  customer_phone: string;
  service_id: string;
  start_time: string;
  end_time: string;
  notes: string;
  status: string;
  created_at: string;
  updated_at: string;
  services: {
    id: string;
    name: string;
    price: number;
    duration: number;
  };
  is_manual?: boolean; // Add this property as optional
}

const localizer = momentLocalizer(moment);

const ArtistCalendar = ({ artistId }: { artistId: string }) => {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [events, setEvents] = useState<Appointment[]>([]);
  const [selectedEvent, setSelectedEvent] = useState<Appointment | null>(null);
  const [editMode, setEditMode] = useState(false);
  const [manualBooking, setManualBooking] = useState(false);
  const [newAppointment, setNewAppointment] = useState<Omit<Appointment, 'id' | 'created_at' | 'updated_at'>>({
    artist_id: artistId,
    customer_id: '',
    customer_name: '',
    customer_email: '',
    customer_phone: '',
    service_id: '',
    start_time: '',
    end_time: '',
    notes: '',
    status: 'scheduled',
    services: {
      id: '',
      name: '',
      price: 0,
      duration: 0,
    },
  });
  const [availableServices, setAvailableServices] = useState<any[]>([]);
  const [selectedService, setSelectedService] = useState<any | null>(null);
  const [dateRange, setDateRange] = useState([new Date(), addHours(new Date(), 1)]);
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [isDateModalOpen, setIsDateModalOpen] = useState(false);
  const [isTimeModalOpen, setIsTimeModalOpen] = useState(false);
  const [selectedTimeSlot, setSelectedTimeSlot] = useState<Date | null>(null);
  const [availableTimeSlots, setAvailableTimeSlots] = useState<Date[]>([]);
  const [isManualDialogOpen, setIsManualDialogOpen] = useState(false);
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isConfirmDialogOpen, setIsConfirmDialogOpen] = useState(false);
  const [isCanceling, setIsCanceling] = useState(false);
  const [isCompletedDialogOpen, setIsCompletedDialogOpen] = useState(false);
  const [isCompleting, setIsCompleting] = useState(false);
  const [isRescheduleDialogOpen, setIsRescheduleDialogOpen] = useState(false);
  const [isRescheduling, setIsRescheduling] = useState(false);
  const [isConfirming, setIsConfirming] = useState(false);
  const [isRejecting, setIsRejecting] = useState(false);
  const [isRejectDialogOpen, setIsRejectDialogOpen] = useState(false);
  const [isConfirmedDialogOpen, setIsConfirmedDialogOpen] = useState(false);
	const [isRejectedDialogOpen, setIsRejectedDialogOpen] = useState(false);
  const [isRescheduledDialogOpen, setIsRescheduledDialogOpen] = useState(false);
  const [isTimeConflict, setIsTimeConflict] = useState(false);
  const [timeConflictMessage, setTimeConflictMessage] = useState('');
  const [isTimeSlotModalOpen, setIsTimeSlotModalOpen] = useState(false);
  const [selectedTimeSlotStart, setSelectedTimeSlotStart] = useState<Date | null>(null);
  const [selectedTimeSlotEnd, setSelectedTimeSlotEnd] = useState<Date | null>(null);
  const [isTimeSlotConflict, setIsTimeSlotConflict] = useState(false);
  const [timeSlotConflictMessage, setTimeSlotConflictMessage] = useState('');
  const [isTimeSlotAvailable, setIsTimeSlotAvailable] = useState(true);
  const [timeSlotAvailabilityMessage, setTimeSlotAvailabilityMessage] = useState('');
  const [isTimeSlotConfirmDialogOpen, setIsTimeSlotConfirmDialogOpen] = useState(false);
  const [isTimeSlotConfirming, setIsTimeSlotConfirming] = useState(false);
  const [isTimeSlotRejectDialogOpen, setIsTimeSlotRejectDialogOpen] = useState(false);
  const [isTimeSlotRejecting, setIsTimeSlotRejecting] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotRescheduleDialogOpen, setIsTimeSlotRescheduleDialogOpen] = useState(false);
  const [isTimeSlotRescheduling, setIsTimeSlotRescheduling] = useState(false);
  const [isTimeSlotDeleteDialogOpen, setIsTimeSlotDeleteDialogOpen] = useState(false);
  const [isTimeSlotDeleting, setIsTimeSlotDeleting] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCompleting, setIsTimeSlotCompleting] = useState(false);
  const [isTimeSlotCancelDialogOpen, setIsTimeSlotCancelDialogOpen] = useState(false);
  const [isTimeSlotCanceling, setIsTimeSlotCanceling] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIsTimeSlotCompletedDialogOpen] = useState(false);
  const [isTimeSlotCanceledDialogOpen, setIsTimeSlotCanceledDialogOpen] = useState(false);
  const [isTimeSlotRescheduledDialogOpen, setIsTimeSlotRescheduledDialogOpen] = useState(false);
  const [isTimeSlotConfirmedDialogOpen, setIsTimeSlotConfirmedDialogOpen] = useState(false);
  const [isTimeSlotRejectedDialogOpen, setIsTimeSlotRejectedDialogOpen] = useState(false);
  const [isTimeSlotDeletedDialogOpen, setIsTimeSlotDeletedDialogOpen] = useState(false);
  const [isTimeSlotCompletedDialogOpen, setIs
