
export const JOB_TYPES = [
  { value: "full_time", label: "Full-Time" },
  { value: "part_time", label: "Part-Time" },
  { value: "contract", label: "Contract" },
  { value: "booth_rental", label: "Booth Rental" },
  { value: "commission", label: "Commission" },
  { value: "freelance", label: "Freelance" },
  { value: "temporary", label: "Temporary" },
  { value: "internship", label: "Internship" },
];

export const JOB_TEMPLATES = [
  {
    id: "nail_salon",
    label: "Nail Salon Hiring",
    defaultTitle: "Nail Technician Needed",
    defaultDescription: "We are looking for a skilled Nail Technician to join our team. The ideal candidate should have experience with manicures, pedicures, gel applications, and nail art. We offer a friendly work environment with competitive commission and a steady client base.",
    defaultSummary: "Experienced nail tech for busy salon",
    defaultType: "full_time",
  },
  {
    id: "hair_stylist",
    label: "Hair Stylist Needed",
    defaultTitle: "Hair Stylist Position Available",
    defaultDescription: "Our salon is seeking a creative and experienced Hair Stylist. You should be skilled in cutting, coloring, and styling for diverse clientele. We provide ongoing education and a supportive team environment.",
    defaultSummary: "Creative hair stylist for upscale salon",
    defaultType: "full_time",
  },
  {
    id: "massage",
    label: "Massage Therapist Opportunity",
    defaultTitle: "Licensed Massage Therapist",
    defaultDescription: "Join our wellness center as a Massage Therapist. We're looking for licensed professionals experienced in Swedish, deep tissue, and hot stone massage techniques. Part-time and full-time positions available.",
    defaultSummary: "Licensed massage therapist for spa center",
    defaultType: "part_time",
  },
  {
    id: "tattoo",
    label: "Tattoo Shop Job",
    defaultTitle: "Tattoo Artist Position",
    defaultDescription: "Established tattoo studio seeking talented artists to join our team. Must have a strong portfolio demonstrating creativity and technical skill. Booth rental with flexible schedule available.",
    defaultSummary: "Experienced tattoo artist with portfolio",
    defaultType: "booth_rental",
  },
  {
    id: "lash_artist",
    label: "Lash Artist Wanted",
    defaultTitle: "Lash Extension Specialist",
    defaultDescription: "Busy beauty studio looking for certified Lash Artists experienced with classic, hybrid, and volume techniques. Great earning potential with existing client base.",
    defaultSummary: "Certified lash tech for established studio",
    defaultType: "commission",
  },
  {
    id: "barber",
    label: "Barber Chair Opening",
    defaultTitle: "Barber Position Available",
    defaultDescription: "Modern barbershop has an opening for an experienced barber skilled in traditional and contemporary cutting techniques, beard grooming, and men's skincare. Commission or chair rental options available.",
    defaultSummary: "Skilled barber for modern shop",
    defaultType: "commission",
  },
  {
    id: "skin_care",
    label: "Skin Care / Facial Technician",
    defaultTitle: "Esthetician Needed",
    defaultDescription: "Spa seeking licensed Esthetician experienced in facials, skin analysis, extractions, and product recommendations. Knowledge of medical-grade skincare treatments is a plus.",
    defaultSummary: "Licensed esthetician for facial treatments",
    defaultType: "full_time",
  },
  {
    id: "beauty_supply",
    label: "Beauty Supply Hiring",
    defaultTitle: "Beauty Supply Store Associate",
    defaultDescription: "Local beauty supply store looking for knowledgeable staff with excellent customer service skills. Must have product knowledge across hair, makeup, and skincare categories.",
    defaultSummary: "Retail associate for beauty supply store",
    defaultType: "part_time",
  },
  {
    id: "makeup",
    label: "Freelance Makeup Gig",
    defaultTitle: "Makeup Artist Needed",
    defaultDescription: "Seeking talented Makeup Artists for events, photoshoots, and private clients. Must have a diverse portfolio showcasing various styles and techniques.",
    defaultSummary: "Versatile makeup artist for events",
    defaultType: "freelance",
  },
  {
    id: "custom",
    label: "Other (Custom)",
    defaultTitle: "",
    defaultDescription: "",
    defaultSummary: "",
    defaultType: "full_time",
  },
];
