
import { JobFormValues } from "./jobFormSchema";

// Base templates for different job types
export const JOB_TEMPLATES: Partial<JobFormValues>[] = [
  {
    id: 'nail-technician',
    title: 'Nail Technician',
    type: 'Full Time',
    description: 'We are looking for experienced nail technicians to join our team. Must be skilled in manicures, pedicures, gel polish, and acrylic application. Competitive pay and great working environment.'
  },
  {
    id: 'hair-stylist',
    title: 'Hair Stylist',
    type: 'Full Time',
    description: 'Now hiring skilled hair stylists with experience in cuts, color, and styling. Join our team and work in a positive salon environment with a loyal client base. Competitive commission and benefits offered.'
  },
  {
    id: 'spa-technician',
    title: 'Spa Technician',
    type: 'Full Time',
    description: 'Join our luxury spa as a skilled technician. We are seeking professionals experienced in facials, body treatments, and skincare recommendations. Create relaxing experiences for our valued clients.'
  },
  {
    id: 'receptionist',
    title: 'Salon Receptionist',
    type: 'Full Time',
    description: 'Seeking a friendly and organized receptionist for our busy salon. Responsibilities include scheduling appointments, greeting clients, answering phone calls, and processing payments. Customer service experience preferred.'
  },
  {
    id: 'lash-technician',
    title: 'Lash Technician',
    type: 'Full Time',
    description: 'Experienced lash technician needed for a growing lash studio. Must be skilled in classic and volume lash extensions with great attention to detail. Friendly attitude and professional demeanor required.'
  },
  {
    id: 'massage-therapist',
    title: 'Massage Therapist',
    type: 'Full Time',
    description: 'Licensed massage therapist wanted for our wellness center. Experience in various massage techniques required. Must have excellent customer service skills and the ability to customize treatments to client needs.'
  },
  {
    id: 'makeup-artist',
    title: 'Makeup Artist',
    type: 'Full Time',
    description: 'Talented makeup artist needed for our beauty studio. Experience with bridal, special event, and everyday makeup application required. Must have a strong portfolio and excellent client communication skills.'
  },
  {
    id: 'tattoo-artist',
    title: 'Tattoo Artist',
    type: 'Full Time',
    description: 'Professional tattoo artist wanted for established studio. Must have a strong portfolio demonstrating technical skill and artistic ability. Health and safety certification required.'
  },
  {
    id: 'booth-rental',
    title: 'Booth Rental Available',
    type: 'Booth Rental',
    description: 'Booth rental available in our busy, well-established salon. Great location with high foot traffic. Ideal for independent beauty professionals with existing clientele. All utilities included. Call for details.'
  },
  {
    id: 'salon-manager',
    title: 'Salon Manager',
    type: 'Full Time',
    description: 'Experienced salon manager needed to oversee daily operations. Responsibilities include staff management, inventory control, scheduling, and ensuring excellent customer service. Prior salon management experience required.'
  }
];

// Advanced polished descriptions for the AI modal
export const POLISHED_DESCRIPTIONS = {
  // English versions
  professional: {
    'nail-technician': 'Our established salon is seeking licensed nail technicians with a minimum of 2 years experience. Candidates must demonstrate proficiency in manicures, pedicures, gel application, acrylic sets, and nail art. Position offers competitive commission structure, flexible scheduling, and opportunities for professional development. Applicants should possess strong customer service skills and the ability to maintain a clean, sanitized workspace.',
    'hair-stylist': 'We are currently seeking experienced hair stylists to join our professional salon team. Qualified candidates will possess a valid cosmetology license and demonstrate expertise in cutting, coloring, styling, and hair treatments. The ideal candidate will stay current with industry trends, maintain a strong portfolio, and provide exceptional client consultations. We offer competitive compensation, continuous education opportunities, and a collaborative work environment.',
    'spa-technician': 'Our luxury day spa is seeking licensed estheticians with expertise in advanced skincare treatments. Candidates must be knowledgeable in product ingredients, facial techniques, and treatment customization. Strong communication skills are essential for performing thorough client consultations and crafting personalized skincare regimens. We provide ongoing training in the latest technologies and techniques, competitive compensation, and a serene work environment.',
    'receptionist': 'Our growing salon requires a professional front desk coordinator to manage daily operations. The ideal candidate will possess exceptional organizational skills, proficiency in salon scheduling software, and the ability to multitask in a fast-paced environment. Responsibilities include appointment management, client communication, retail sales, and maintaining an immaculate reception area. Previous salon or spa experience preferred.',
    'lash-technician': 'We are seeking a certified lash technician with proven experience in classic and volume extension application. The ideal candidate will demonstrate meticulous attention to detail, knowledge of proper isolation techniques, and understanding of eye anatomy and safety protocols. Must maintain exceptional sanitation standards and provide thorough client consultations. Commission-based compensation with booking bonuses available for consistently booked professionals.',
    'massage-therapist': 'Our wellness center seeks licensed massage therapists with certification in multiple modalities including deep tissue, Swedish, and therapeutic techniques. Candidates should possess strong anatomical knowledge, ability to develop targeted treatment plans, and excellent client communication skills. We provide a peaceful work environment, quality products and equipment, competitive compensation, and a loyal client base.',
    'makeup-artist': 'Established beauty studio seeking a professional makeup artist with experience in bridal, editorial, and special occasion makeup. Must demonstrate technical proficiency across diverse skin types and tones, knowledge of current products and techniques, and the ability to execute precise applications under time constraints. Portfolio review required during interview process. Position offers competitive compensation and product discounts.',
    'tattoo-artist': 'Reputable studio seeking an experienced tattoo artist to join our team. Candidates must present an extensive portfolio demonstrating technical precision, artistic versatility, and clean linework. Thorough understanding of sterilization procedures and safety protocols is essential. The ideal artist will maintain professional client interactions, possess excellent time management, and contribute to our collaborative studio environment.',
    'booth-rental': 'Prime booth rental available in an established, high-traffic salon. This professional space includes a styling station with premium equipment, product storage, and access to a modern color bar. Rental includes utilities, towel service, and inclusion in the salon's digital marketing efforts. Ideal for established professionals with existing clientele seeking a reputable location with excellent visibility and amenities.',
    'salon-manager': 'We are recruiting an experienced salon manager to oversee daily business operations and staff development. The ideal candidate will demonstrate proven leadership ability, financial management experience, and exceptional interpersonal skills. Responsibilities include inventory control, performance evaluations, conflict resolution, and maintaining service standards. Must possess relevant industry experience and business acumen. Competitive salary commensurate with experience.'
  },
  friendly: {
    'nail-technician': "Join our nail tech family where creativity flourishes! We're looking for talented techs who love creating beautiful nails as much as we do. Experience with gel, acrylics, and nail art preferred, but your warm personality and dedication to client happiness are just as important. We offer flexible hours, a fun team environment, and the chance to build lasting relationships with wonderful clients. Bring your passion and let's grow together!",
    'hair-stylist': "We're growing our salon family and looking for talented stylists who bring positivity and passion to their craft! If you love transforming hair and making clients smile, we want to meet you. Our friendly team supports each other, celebrates creativity, and believes in work-life balance. You'll enjoy flexible scheduling, birthday celebrations, team outings, and clients who become friends. Bring your scissors and your smile – let's create beauty together!",
    'spa-technician': "Our spa family is looking for a caring esthetician to help clients feel their absolute best! We believe in creating not just beautiful skin, but wonderful experiences where clients feel truly cared for. Your gentle touch and warm personality will be just as important as your technical skills. Join our supportive team where we celebrate each other's successes and grow together in a positive environment with flexible scheduling and happy clients who can't wait to see you again!",
    'receptionist': "Become the welcoming smile of our salon family! We're looking for a friendly front desk coordinator who loves making people feel special from the moment they walk in. You'll be the heart of our salon—greeting clients, offering refreshments, and ensuring everyone feels at home. If you're naturally warm, love multitasking, and believe in creating wonderful experiences, we'd love to meet you! Join our positive team where work feels less like work and more like spending time with friends.",
    'lash-technician': "Join our lash artist family and help clients feel beautiful every day! We're looking for a friendly lash tech who loves creating gorgeous, confidence-boosting lashes in our warm, welcoming studio. Bring your talent for classic and volume sets, along with your caring personality. You'll work with a supportive team that celebrates creativity and client connection. Flexible scheduling, a fun atmosphere, and clients who become friends make our studio a truly special place to grow your career!",
    'massage-therapist': "Bring your healing hands to our wellness family! We're seeking a caring massage therapist who believes in the power of therapeutic touch to transform someone's day. Our relaxed, positive environment puts both staff and clients at ease. You'll work with a supportive team that respects your expertise and values work-life balance. Flexible hours, a comfortable treatment space, and appreciative clients make this a truly rewarding place to practice your craft. Join us and share your gift of wellness!",
    'makeup-artist': "Calling creative makeup artists to join our beauty family! If you love making clients feel gorgeous and confident through the art of makeup, we want you on our team. Our friendly, supportive studio celebrates creativity and personal connection. You'll enjoy working with wonderful clients for special events, creating everyday looks, and sharing your passion for beauty. Flexible scheduling, a fun atmosphere, and clients who leave as friends make our studio a joyful place to grow your artistry!",
    'tattoo-artist': "Join our tattoo studio family where art and community come together! We're looking for a talented artist who brings positive energy and creative passion to their work. Beyond amazing technical skills, we value artists who connect with clients and make their tattoo experience memorable. Our laid-back shop has a supportive, drama-free culture where artists inspire each other and grow together. Flexible scheduling, regular shop events, and clients who become friends make this a truly special place to create lasting art.",
    'booth-rental': "Calling independent beauty pros looking for their new home! Our friendly, supportive salon family has the perfect booth available for you and your clients. You'll enjoy a warm atmosphere where everyone celebrates each other's success, regular salon gatherings, and a drama-free environment. The space includes everything you need to make your clients feel special, plus plenty of parking and great visibility. Bring your talent and your clients – we'd love to welcome you to our beauty community!",
    'salon-manager': "Join our salon family as our new leader! We're looking for a people-person with management experience who can guide our team with warmth and wisdom. You'll help nurture a positive environment where creativity thrives and everyone feels valued. Beyond scheduling and operations, you'll be the heart of our salon culture—celebrating team wins, mentoring new talent, and keeping the energy upbeat. If you believe leadership is about bringing out the best in others, we'd love to welcome you to our close-knit beauty family!"
  },
  luxury: {
    'nail-technician': "Our exclusive salon is seeking an elite nail artist to serve our distinguished clientele. The ideal candidate will demonstrate exceptional precision in luxury services including gel extensions, hand-painted nail art, and signature treatments. You will work in an opulent environment with premium products, state-of-the-art equipment, and a discerning clientele who expect perfection. We offer premium compensation, a sophisticated atmosphere, and the opportunity to elevate your artistry to the highest standards of luxury nail care.",
    'hair-stylist': "Our prestigious salon invites master stylists to join our exclusive team serving an elite clientele. We seek artists who demonstrate exceptional skill in precision cutting, couture color formulation, and red-carpet styling techniques. Your portfolio should showcase transformative work that reflects uncompromising standards. Our luxurious environment features premium amenities, state-of-the-art technology, and the finest product lines. We offer exclusive education with international platform artists and compensation befitting the highest echelon of hair design professionals.",
    'spa-technician': "Our renowned spa sanctuary seeks an elite esthetician to deliver transcendent skincare experiences to our distinguished clientele. The ideal candidate will possess expertise in advanced modalities including diamond microdermabrasion, LED therapy, and customized treatment protocols. You will work with exclusive, results-driven product lines in an immaculate treatment suite designed for ultimate relaxation. We offer premium compensation, continuing education with skincare luminaries, and a refined environment where excellence is the only standard.",
    'receptionist': "Our luxury salon seeks a refined Guest Relations Coordinator to orchestrate exceptional client experiences. The ideal candidate will possess impeccable communication skills, discretion with high-profile clientele, and natural elegance in presentation. You will master our premium booking system, curate refreshment offerings, and ensure seamless client journeys from arrival to departure. Your sophisticated presence will establish the tone for our exclusive atmosphere where every detail matters and no request is too extravagant.",
    'lash-technician': "Our premium beauty atelier seeks a master lash artist to serve our discerning clientele. The ideal candidate will demonstrate virtuosity in creating bespoke lash designs including Russian volume, mega volume, and hybrid techniques. You will work in a luxurious private suite with premium products and the most advanced tools in the industry. Our exclusive salon offers an unparalleled client experience, and we seek an artist whose exquisite technique and refined approach will satisfy the most discriminating lash connoisseurs.",
    'massage-therapist': "Our exclusive wellness sanctuary invites a distinguished massage therapist to join our team of elite practitioners. We seek a master of therapeutic touch with expertise in premium modalities including hot stone therapy, aromatherapy, and advanced deep tissue techniques. You will practice in a private treatment suite featuring luxurious amenities and state-of-the-art equipment. Our discerning clientele expects transformative experiences delivered with sophisticated attention to detail and personalized care.",
    'makeup-artist': "Our prestigious beauty studio seeks a premier makeup artist to serve an exclusive clientele including celebrities and social elite. The ideal candidate will demonstrate mastery of luxury application techniques, color theory, and trend forecasting. Your portfolio should showcase editorial-quality work applicable to high-profile events, photography, and special occasions. You will work with the most exclusive cosmetic lines in an impeccably appointed private studio. We offer premium compensation reflective of the unparalleled artistry our clients expect.",
    'tattoo-artist': "Our exclusive atelier seeks a distinguished tattoo artist to serve discerning clients who view body art as the ultimate luxury expression. The ideal candidate will demonstrate mastery in fine line work, photorealistic portraiture, and innovative techniques that transcend conventional tattooing. You will work in a private, gallery-like studio environment with state-of-the-art equipment and premium materials. Our clientele expects immaculate precision, artistic innovation, and an experience that reflects the significant investment they place in permanent art.",
    'booth-rental': "Exclusive opportunity for an established beauty professional to join our prestigious address. This premium booth rental offers an unparalleled setting in our award-winning salon frequented by discerning clientele. The elegantly appointed space features top-tier equipment, luxury finishes, and an ambiance that reflects sophistication. Rental includes access to our VIP amenities including concierge service, valet parking for clients, and inclusion in our curated social media featuring only the most distinguished beauty professionals in the city.",
    'salon-manager': "Our prestigious salon group seeks an exceptional Director of Operations to orchestrate excellence across all facets of our luxury establishment. The ideal candidate will bring refined leadership experience from premium hospitality or luxury retail environments. You will cultivate our team of elite artists, manage VIP client relationships, and ensure our exacting standards are maintained without compromise. This role demands sophisticated business acumen, impeccable taste, and the ability to anticipate needs in a setting where ordinary is never acceptable."
  },
  casual: {
    'nail-technician': "Looking for a talented nail tech to join our cool, laid-back salon! We need someone who's great with gel, acrylics, and basic nail art. Our vibe is super chill but we take our work seriously - our clients love leaving happy with gorgeous nails. You'll set your own pace with flexible hours, work with a team that feels like friends, and earn competitive pay with tips. Bring your skills and your good energy - we'd love to have you join our crew!",
    'hair-stylist': "Cool stylist wanted for our relaxed, modern salon! We're looking for someone who loves what they do and brings good energy to their chair. Whether you're into cutting, coloring, balayage, or all of the above, we want to see what you can do. Our salon has a laid-back atmosphere where clients feel comfortable and stylists can be themselves. Flexible scheduling, reasonable commission splits, and a drama-free workplace make this a great place to grow your career and enjoy coming to work.",
    'spa-technician': "Chill spa tech needed for our relaxed wellness studio! We're looking for someone who's skilled at facials and body treatments but also brings good vibes to their treatment room. Our place has a relaxed, judgment-free atmosphere where clients can truly unwind. No stuffy spa scripts here - just genuine care and effective treatments. You'll have flexible hours, a comfortable workspace, and clients who appreciate your authentic approach to skincare and wellness. Join our team and do great work in a pressure-free environment!",
    'receptionist': "Friendly desk person needed for our chill salon! We're looking for someone who can handle the basics - booking appointments, checking clients in, and keeping things running smoothly - while adding to our relaxed, welcoming vibe. No need for formal experience, just good organization skills and a naturally friendly attitude. You'll work reasonable hours in a laid-back environment with a team that appreciates what you do. Plus, you'll get to know our awesome clients and be an important part of making their experience great!",
    'lash-technician': "Lash artist wanted for our cozy beauty studio! If you're skilled with classic and volume lashes and like working at your own pace, we'd love to meet you. Our studio has a relaxed, homey feel where clients can chill out during their appointments and actually enjoy the experience. You'll have control over your schedule, a comfortable workspace, and clients who appreciate beautiful lashes without the pretentious salon environment. Bring your skills and your authentic self - we're all about keeping it real while doing amazing work.",
    'massage-therapist': "Massage therapist needed for our down-to-earth wellness center! We're looking for someone with solid massage skills who creates a comfortable, judgment-free environment for all clients. Our center is all about making wellness accessible and enjoyable without the stuffy spa attitude. You'll work reasonable hours, have a comfortable treatment room, and connect with clients who appreciate your genuine approach to bodywork. Join our team and do the work you love in a place that feels good to be.",
    'makeup-artist': "Creative makeup artist wanted for our fun, approachable beauty studio! We're looking for someone who loves creating everything from natural everyday looks to full glam, without the intimidating beauty counter vibe. Our studio is all about making clients feel comfortable and having a good time while getting gorgeous. You'll enjoy a flexible schedule, a relaxed atmosphere, and clients who appreciate your talent and friendly approach. If you love makeup and good vibes equally, we'd be stoked to have you join our team!",
    'tattoo-artist': "Tattoo artist wanted for our laid-back, friendly shop! We're looking for someone who brings solid technical skills and good energy to their work. Our shop has a chill, welcoming vibe without the intimidating attitude some places have. Clients appreciate our no-judgment approach and relaxed environment. You'll have flexibility with your schedule, a comfortable workspace, and the freedom to develop your own artistic style. If you're talented, easy to work with, and want to create in a drama-free zone, let's talk!",
    'booth-rental': "Chill booth rental available in our friendly, laid-back salon! Perfect for an independent stylist, nail tech, or lash artist looking for a comfortable place to do their thing. The vibe here is relaxed and welcoming - no salon drama or strict rules about how you run your business. You'll get a nice workspace, reasonable rent that includes utilities, plenty of parking, and neighbors who are cool to work alongside. Bring your clients to a place where everyone can feel comfortable and be themselves!",
    'salon-manager': "Salon manager needed for our modern, drama-free shop! We're looking for someone who can keep things running smoothly without creating a corporate vibe. You'll help coordinate schedules, keep supplies stocked, and generally make sure everything's working right, while still maintaining our relaxed atmosphere. The ideal person is organized but flexible, good with people, and understands that a happy team makes for happy clients. Reasonable hours, competitive pay, and the satisfaction of leading a salon where people actually enjoy coming to work!"
  },
  detailed: {
    'nail-technician': "Position: Licensed Nail Technician\n\nRequirements:\n• Minimum 2 years professional experience\n• Current state licensure\n• Expertise in acrylic application, gel systems, and natural nail care\n• Demonstrated nail art capabilities\n• Knowledge of proper sanitation protocols\n\nResponsibilities:\n• Perform manicures, pedicures, gel polish applications, acrylic sets, and dipping powder services\n• Maintain cleanliness of station between each client\n• Properly sanitize all implements according to state guidelines\n• Recommend appropriate home care products\n• Maintain accurate client records\n\nSchedule Requirements:\n• Must be available for 2 weekend shifts per week\n• Typical shift hours: 9:30am-7:00pm\n• Part-time and full-time positions available\n\nCompensation:\n• Commission-based (45-55% based on experience)\n• Performance bonuses available\n• Retail commission: 10% on all products sold\n• Health insurance contribution for full-time staff\n• Paid continuing education opportunities",
    'hair-stylist': "Position: Licensed Hair Stylist\n\nRequirements:\n• Valid cosmetology license\n• Minimum 3 years salon experience\n• Proficiency in cutting techniques for all hair types\n• Color formulation and application expertise\n• Commitment to continuing education\n\nCore Responsibilities:\n• Perform precision haircuts for diverse clientele\n• Execute color services including balayage, foiling, and color correction\n• Conduct thorough consultations to ensure client satisfaction\n• Recommend and educate clients on appropriate retail products\n• Maintain clean, organized station and equipment\n\nSchedule Requirements:\n• Minimum 32 hours weekly for full-time position\n• Must be available for at least one evening shift (until 8pm)\n• Weekend availability required (minimum 2 Saturdays per month)\n\nCompensation Package:\n• Competitive commission structure (45-60% based on experience)\n• Product commission: 10-15% on all retail sales\n• Health insurance contribution after 90-day probationary period\n• Education allowance: $500 annually for approved classes\n• Paid vacation (1 week annually after first year)\n• Regular performance reviews with opportunity for commission increases",
    'spa-technician': "Position: Licensed Esthetician\n\nRequirements:\n• Current state esthetics license\n• Minimum 1 year experience in spa environment\n• Knowledge of advanced skincare treatments\n• Training in chemical peels and microdermabrasion preferred\n• Detail-oriented with excellent sanitation practices\n\nCore Responsibilities:\n• Perform customized facial treatments based on skin analysis\n• Administer chemical peels, enzyme treatments, and extractions\n• Execute proper facial massage techniques\n• Perform full-body treatments including scrubs and wraps\n• Maintain thorough client records and treatment notes\n• Educate clients on appropriate home care regimens\n\nSchedule Details:\n• 30-40 hours weekly (full-time)\n• 20-25 hours weekly (part-time option)\n• Evening availability until 8pm twice weekly\n• Weekend rotation required\n\nCompensation Structure:\n• Service commission: 40-50% based on experience\n• Retail commission: 15% on all products sold\n• Service upgrade bonus: $10 per add-on treatment\n• Monthly treatment quotas with bonus incentives\n• Paid product training and continuing education\n• Employee discount: 30% on all spa products",
    'receptionist': "Position: Salon Coordinator/Receptionist\n\nCore Requirements:\n• High school diploma or equivalent\n• Previous customer service experience required\n• Salon or spa experience preferred but not required\n• Proficient computer skills including booking software\n• Professional phone etiquette\n\nDetailed Responsibilities:\n• Manage the appointment schedule for 8-10 service providers\n• Process client check-in/check-out efficiently\n• Handle phone inquiries and convert calls to bookings\n• Process payments accurately including tips distribution\n• Maintain retail displays and process inventory\n• Perform opening/closing procedures\n• Ensure reception area and refreshment station remain immaculate\n• Coordinate with service providers regarding schedule changes\n\nSchedule Requirements:\n• Full-time position: 38-40 hours weekly\n• Part-time position: 15-25 hours weekly\n• Must be available for at least 2 evening shifts (until 8pm)\n• Weekend availability required\n\nCompensation Package:\n• Hourly rate: $15-18 based on experience\n• Monthly booking conversion bonus (up to $200)\n• Retail sales commission: 5%\n• Employee service discount: 30%\n• Product discount: 20%\n• Performance review after 90 days with potential raise",
    'lash-technician': "Position: Certified Lash Artist\n\nRequirements:\n• Current lash extension certification\n• Minimum 1 year professional lash experience\n• Cosmetology or esthetician license preferred\n• Expertise in classic, hybrid, and volume techniques\n• Portfolio demonstrating technical precision\n\nDetailed Responsibilities:\n• Perform thorough client consultations to determine appropriate lash style\n• Execute classic sets (90-120 minutes)\n• Create volume and hybrid sets (120-180 minutes)\n• Conduct lash fills with proper assessment of remaining extensions\n• Maintain immaculate sanitation protocols\n• Document client allergies and reactions\n• Record client preferences for future appointments\n• Educate clients on proper aftercare\n\nSchedule Requirements:\n• 25-40 hours weekly based on preference\n• Evening availability until 7pm twice weekly\n• Weekend availability (minimum 2 Saturdays per month)\n• Appointments scheduled with adequate time between clients\n\nCompensation Structure:\n• Commission: 45-55% based on experience and client retention\n• Retail commission: 15% on aftercare products\n• Booking bonus: $50 for fully booked week\n• Performance-based increases reviewed quarterly\n• Continuing education stipend after 6 months",
    'massage-therapist': "Position: Licensed Massage Therapist\n\nLicense Requirements:\n• Current state massage therapy license\n• Minimum 500 hours from accredited massage program\n• Liability insurance coverage\n• CPR certification\n• Minimum 1 year professional experience\n\nModality Requirements:\n• Proficiency in Swedish massage techniques\n• Deep tissue protocol experience\n• Additional modalities desired: prenatal, hot stone, sports massage\n• Basic understanding of anatomy and contraindications\n\nCore Responsibilities:\n• Perform 60, 90, and 120-minute massage sessions\n• Conduct thorough intake for new clients\n• Document SOAP notes after each session\n• Maintain treatment room cleanliness\n• Properly sanitize equipment between clients\n• Communicate effectively about pressure and client comfort\n• Recommend appropriate treatment plans\n\nSchedule Details:\n• Part-time (15-25 hours) and full-time (25-35 hours) available\n• Maximum 6 massage hours daily\n• Evening availability until 8pm twice weekly\n• Weekend rotation required (1-2 per month)\n• 15 minutes between sessions for room reset\n\nCompensation Package:\n• Service commission: 40-50% based on experience\n• Add-on service bonus: $10 per enhancement\n• Retail commission: 10% on all products sold\n• Rebooking incentive: $5 per client who books next appointment\n• Monthly massage trade among staff members\n• Continuing education allowance after one year",
    'makeup-artist': "Position: Professional Makeup Artist\n\nQualifications Required:\n• Cosmetology or esthetician license preferred (not required)\n• Minimum 2 years professional makeup experience\n• Strong portfolio demonstrating versatile makeup applications\n• Experience with various skin types, tones, and textures\n• Knowledge of sanitary makeup application procedures\n\nDetailed Responsibilities:\n• Perform makeup consultations assessing client needs and preferences\n• Execute makeup applications for special events, photoshoots, and everyday wear\n• Specialize in bridal makeup with proper timing and durability techniques\n• Maintain immaculate kit with professional-grade products\n• Sanitize all tools between clients according to industry standards\n• Create face charts for clients who purchase products\n• Educate clients on application techniques for home use\n\nService Offerings Expected:\n• Special event makeup (60 minutes)\n• Bridal makeup including trial session\n• Natural/daytime makeup application (30-45 minutes)\n• Evening/formal makeup application (45-60 minutes)\n• False lash application\n• Makeup lessons (60-90 minutes)\n\nSchedule Requirements:\n• Flexible availability required for weekend events\n• Must accommodate early morning appointments for bridal parties\n• Tuesday-Saturday regular schedule with Sunday/Monday events as booked\n\nCompensation Structure:\n• Service commission: 45-55% based on experience\n• Retail commission: 15% on all makeup products sold\n• Bridal booking bonus: $50 per secured bridal party\n• Transportation fee for on-location services\n• Kit maintenance allowance: $200 quarterly",
    'tattoo-artist': "Position: Professional Tattoo Artist\n\nRequirements:\n• Minimum 3-5 years professional tattooing experience\n• Current bloodborne pathogen certification\n• Strong portfolio demonstrating clean linework and versatile styles\n• Understanding of proper sterilization procedures\n• Ability to create custom designs from client concepts\n\nDetailed Responsibilities:\n• Conduct thorough consultations to understand client vision\n• Create custom tattoo designs and stencils\n• Maintain sterile working environment\n• Properly set up and break down station for each client\n• Provide detailed aftercare instructions\n• Document finished work for portfolio\n• Maintain organized booking system for clients\n\nTechnical Skills Required:\n• Linework precision and consistency\n• Solid color saturation\n• Shading techniques\n• Understanding of skin types and how they affect application\n• Proper needle selection for different techniques\n• Machine maintenance and troubleshooting\n\nSchedule Details:\n• Typical workday: 12pm-8pm\n• 4-5 days per week based on preference\n• Weekend availability required (minimum 2 per month)\n• Time allocated between appointments for design preparation\n\nCompensation Structure:\n• Commission-based: 60-70% of tattoo price\n• Hourly rate: $150-200 based on experience and demand\n• Drawing fee for custom designs\n• Deposit system for appointments\n• Guaranteed minimum for slow days\n• Supply stipend available",
    'booth-rental': "Booth Rental Opportunity\n\nSpace Details:\n• 100 sq. ft. private station with lockable storage\n• Modern styling chair and full-length mirror included\n• Custom cabinetry with 5 drawers and enclosed product storage\n• Adjustable LED lighting fixtures\n• Two dedicated electrical outlets with USB ports\n• Private washbowl with adjustable water temperature\n• Access to shared color bar and processing area\n• Use of salon backbar for shampooing clients\n\nAmenities Included:\n• High-speed WiFi access\n• Online booking software subscription\n• Reception services for check-in and checkout\n• Towel service (daily laundering included)\n• Coffee/tea/water service for clients\n• Shared break room with refrigerator and microwave\n• Building utilities (water, electric, HVAC)\n• Salon liability insurance coverage\n• Weekly professional cleaning service\n• Secure building with 24-hour access\n\nLocationSpecifics:\n• High-visibility retail location with street signage\n• Ample free parking (25+ spaces)\n• Wheelchair accessible entrance and facilities\n• Located in shopping center with complementary businesses\n• 3 miles from downtown area\n\nRental Terms:\n• Monthly lease: $800-950 based on booth location\n• $500 security deposit (refundable)\n• 6-month minimum lease term with month-to-month after\n• First and last month's rent due at signing\n• Option for weekly payment plan available\n\nRenter Requirements:\n• Current state license in relevant field\n• Proof of liability insurance\n• Minimum 2 years professional experience\n• Established clientele preferred\n• References from previous salon affiliation",
    'salon-manager': "Position: Salon Manager/Director\n\nExperience Requirements:\n• Minimum 5 years salon industry experience\n• 2+ years in supervisory/management role\n• Demonstrated team leadership abilities\n• Strong financial and operational management background\n• Cosmetology license or industry education preferred\n\nCore Responsibilities:\n\nStaff Management:\n• Oversee team of 12-15 service providers\n• Conduct weekly team meetings and monthly one-on-one reviews\n• Create and manage staff schedules ensuring proper coverage\n• Implement performance improvement plans when necessary\n• Coordinate continuing education opportunities\n• Lead hiring process for new team members\n• Mediate conflict resolution between staff members\n\nOperational Duties:\n• Monitor and maintain service standards across all departments\n• Ensure compliance with state board regulations\n• Oversee inventory management and product ordering\n• Manage retail displays and promotions\n• Maintain equipment and coordinate repairs as needed\n• Process bi-weekly payroll and commission calculations\n• Create monthly staff performance reports\n\nFinancial Responsibilities:\n• Monitor daily sales targets and address shortfalls\n• Track retail inventory turns and product performance\n• Analyze service provider productivity metrics\n• Implement retention strategies for both clients and staff\n• Control costs while maintaining service quality\n• Meet or exceed monthly revenue projections\n\nSchedule Requirements:\n• Full-time position (45-50 hours weekly)\n• Tuesday-Saturday schedule with occasional evenings\n• Availability for emergency coverage as needed\n\nCompensation Package:\n• Base salary: $45,000-55,000 commensurate with experience\n• Monthly performance bonus based on salon profitability (up to $1,000)\n• Health insurance contribution\n• Cell phone allowance\n• Paid vacation (2 weeks annually)\n• Free services and significant product discount\n• Quarterly performance reviews with salary adjustment opportunities"
  },
  
  // Vietnamese versions
  professionalVi: {
    'nail-technician': 'Tiệm nail đang tuyển thợ có bằng với ít nhất 2 năm kinh nghiệm. Ứng viên phải thành thạo làm móng tay, móng chân, sơn gel, đắp bột và vẽ móng nghệ thuật. Chúng tôi cung cấp mức hoa hồng cạnh tranh, lịch làm việc linh hoạt và cơ hội phát triển chuyên môn. Thợ cần có kỹ năng phục vụ khách hàng tốt và luôn duy trì không gian làm việc sạch sẽ, vệ sinh.',
    'hair-stylist': 'Tiệm tóc đang tìm kiếm thợ tóc có kinh nghiệm để gia nhập đội ngũ chuyên nghiệp của chúng tôi. Ứng viên cần có bằng tóc hợp lệ và thể hiện chuyên môn trong cắt, nhuộm, tạo kiểu và các liệu pháp chăm sóc tóc. Thợ lý tưởng sẽ luôn cập nhật xu hướng ngành, duy trì danh mục công việc mạnh mẽ và tư vấn khách hàng xuất sắc. Chúng tôi cung cấp mức lương cạnh tranh, cơ hội học tập liên tục và môi trường làm việc hợp tác.',
    'spa-technician': 'Spa cao cấp của chúng tôi đang tìm kiếm chuyên viên spa có chứng chỉ với chuyên môn về các liệu pháp chăm sóc da nâng cao. Ứng viên phải am hiểu về thành phần sản phẩm, kỹ thuật chăm sóc da và tùy chỉnh liệu pháp. Kỹ năng giao tiếp tốt là điều cần thiết để thực hiện tư vấn khách hàng kỹ lưỡng và xây dựng phác đồ chăm sóc da cá nhân hóa. Chúng tôi cung cấp đào tạo liên tục về công nghệ và kỹ thuật mới nhất, mức lương cạnh tranh và môi trường làm việc yên tĩnh.',
    'receptionist': 'Tiệm đang phát triển của chúng tôi cần một nhân viên lễ tân chuyên nghiệp để quản lý hoạt động hàng ngày. Ứng viên lý tưởng sẽ có kỹ năng tổ chức xuất sắc, thành thạo phần mềm đặt lịch salon và khả năng xử lý nhiều nhiệm vụ trong môi trường làm việc nhanh. Trách nhiệm bao gồm quản lý lịch hẹn, giao tiếp với khách hàng, bán lẻ sản phẩm và duy trì khu vực lễ tân sạch sẽ. Ưu tiên người có kinh nghiệm làm việc tại salon hoặc spa.',
    'lash-technician': 'Chúng tôi đang tìm kiếm kỹ thuật viên mi đã được chứng nhận với kinh nghiệm được chứng minh trong nối mi classic và volume. Ứng viên lý tưởng sẽ thể hiện sự chú ý tỉ mỉ đến từng chi tiết, kiến thức về các kỹ thuật cô lập đúng cách và hiểu biết về giải phẫu mắt và các quy trình an toàn. Phải duy trì tiêu chuẩn vệ sinh vượt trội và cung cấp tư vấn khách hàng kỹ lưỡng. Mức lương dựa trên hoa hồng với tiền thưởng đặt lịch dành cho các chuyên gia có lịch đặt ổn định.',
    'massage-therapist': 'Trung tâm chăm sóc sức khỏe của chúng tôi tìm kiếm các nhà trị liệu massage có giấy phép với chứng nhận trong nhiều phương pháp bao gồm mô sâu, Swedish và các kỹ thuật trị liệu. Ứng viên nên có kiến thức giải phẫu mạnh mẽ, khả năng phát triển kế hoạch điều trị có mục tiêu và kỹ năng giao tiếp khách hàng xuất sắc. Chúng tôi cung cấp môi trường làm việc yên bình, sản phẩm và thiết bị chất lượng, mức lương cạnh tranh và cơ sở khách hàng trung thành.',
    'makeup-artist': 'Studio làm đẹp đã thành lập đang tìm kiếm chuyên gia trang điểm chuyên nghiệp với kinh nghiệm về trang điểm cô dâu, biên tập và dịp đặc biệt. Phải thể hiện được sự thành thạo kỹ thuật trên các loại da và tông màu đa dạng, kiến thức về sản phẩm và kỹ thuật hiện tại, và khả năng thực hiện ứng dụng chính xác trong thời gian giới hạn. Yêu cầu xem xét danh mục công việc trong quá trình phỏng vấn. Vị trí này cung cấp mức lương cạnh tranh và giảm giá sản phẩm.',
    'tattoo-artist': 'Studio uy tín đang tìm kiếm một nghệ sĩ xăm có kinh nghiệm để gia nhập đội ngũ của chúng tôi. Ứng viên phải trình bày danh mục công việc rộng lớn thể hiện độ chính xác kỹ thuật, tính linh hoạt nghệ thuật và đường nét sạch sẽ. Hiểu biết kỹ lưỡng về các quy trình khử trùng và quy trình an toàn là điều cần thiết. Nghệ sĩ lý tưởng sẽ duy trì tương tác chuyên nghiệp với khách hàng, có khả năng quản lý thời gian tốt và đóng góp vào môi trường studio hợp tác của chúng tôi.',
    'booth-rental': 'Cho thuê không gian làm việc tại vị trí đắc địa trong một salon đã được thiết lập, có lượng khách ra vào đông đúc. Không gian chuyên nghiệp này bao gồm một trạm tạo kiểu với thiết bị cao cấp, kho lưu trữ sản phẩm và quyền truy cập vào khu vực pha màu hiện đại. Tiền thuê bao gồm các tiện ích, dịch vụ khăn và được đưa vào nỗ lực tiếp thị kỹ thuật số của salon. Lý tưởng cho các chuyên gia đã thành lập với khách hàng hiện có đang tìm kiếm một địa điểm có uy tín với khả năng hiển thị và tiện nghi tuyệt vời.',
    'salon-manager': 'Chúng tôi đang tuyển dụng một quản lý salon có kinh nghiệm để giám sát hoạt động kinh doanh hàng ngày và phát triển nhân viên. Ứng viên lý tưởng sẽ thể hiện khả năng lãnh đạo đã được chứng minh, kinh nghiệm quản lý tài chính và kỹ năng giao tiếp xuất sắc. Trách nhiệm bao gồm kiểm soát hàng tồn kho, đánh giá hiệu suất, giải quyết xung đột và duy trì tiêu chuẩn dịch vụ. Phải có kinh nghiệm trong ngành và hiểu biết về kinh doanh liên quan. Mức lương cạnh tranh tương xứng với kinh nghiệm.'
  },
  friendlyVi: {
    'nail-technician': 'Hãy gia nhập gia đình thợ nail của chúng tôi, nơi sự sáng tạo được phát huy! Chúng tôi đang tìm kiếm những thợ nail tài năng, yêu thích việc tạo ra những bộ móng đẹp như chúng tôi. Ưu tiên người có kinh nghiệm với gel, bột đắp và nail art, nhưng tính cách thân thiện và sự tận tâm với khách hàng cũng quan trọng không kém. Chúng tôi cung cấp giờ làm việc linh hoạt, môi trường đội nhóm vui vẻ và cơ hội xây dựng mối quan hệ lâu dài với những khách hàng tuyệt vời. Hãy mang đam mê của bạn đến và cùng nhau phát triển!',
    'hair-stylist': 'Chúng tôi đang mở rộng gia đình salon và tìm kiếm những thợ tóc tài năng, mang đến sự tích cực và đam mê trong nghề! Nếu bạn yêu thích việc biến đổi mái tóc và làm cho khách hàng mỉm cười, chúng tôi muốn gặp bạn. Đội ngũ thân thiện của chúng tôi hỗ trợ lẫn nhau, tôn vinh sự sáng tạo và tin vào sự cân bằng giữa công việc và cuộc sống. Bạn sẽ được hưởng lịch làm việc linh hoạt, các buổi kỷ niệm sinh nhật, các chuyến đi nhóm và khách hàng trở thành bạn. Hãy mang kéo và nụ cười của bạn đến – cùng nhau tạo nên vẻ đẹp!',
    'spa-technician': 'Gia đình spa của chúng tôi đang tìm kiếm một chuyên viên chăm sóc da tận tâm để giúp khách hàng cảm thấy tuyệt vời nhất! Chúng tôi tin vào việc tạo ra không chỉ làn da đẹp, mà còn là những trải nghiệm tuyệt vời khiến khách hàng cảm thấy thực sự được quan tâm. Bàn tay nhẹ nhàng và tính cách thân thiện của bạn sẽ cũng quan trọng như kỹ năng chuyên môn. Hãy tham gia vào đội ngũ hỗ trợ của chúng tôi, nơi chúng tôi tôn vinh thành công của nhau và cùng nhau phát triển trong môi trường tích cực với lịch làm việc linh hoạt và khách hàng vui vẻ luôn mong chờ gặp lại bạn!',
    'receptionist': 'Hãy trở thành nụ cười chào đón của gia đình salon chúng tôi! Chúng tôi đang tìm kiếm một điều phối viên lễ tân thân thiện, yêu thích việc làm cho mọi người cảm thấy đặc biệt ngay từ khi họ bước vào. Bạn sẽ là trái tim của salon chúng tôi—chào đón khách hàng, mời nước, và đảm bảo mọi người cảm thấy như ở nhà. Nếu bạn tự nhiên ấm áp, thích đa nhiệm và tin vào việc tạo ra những trải nghiệm tuyệt vời, chúng tôi muốn gặp bạn! Hãy tham gia vào đội ngũ tích cực của chúng tôi, nơi công việc cảm thấy ít giống công việc và giống như thời gian dành cho bạn bè hơn.',
    'lash-technician': 'Hãy tham gia vào gia đình nghệ sĩ mi của chúng tôi và giúp khách hàng cảm thấy xinh đẹp mỗi ngày! Chúng tôi đang tìm kiếm một kỹ thuật viên mi thân thiện, yêu thích việc tạo ra những hàng mi tuyệt đẹp, nâng cao sự tự tin trong studio ấm cúng, chào đón của chúng tôi. Hãy mang đến tài năng của bạn cho các bộ mi classic và volume, cùng với tính cách chu đáo của bạn. Bạn sẽ làm việc với một đội ngũ hỗ trợ, tôn vinh sự sáng tạo và kết nối với khách hàng. Lịch làm việc linh hoạt, không khí vui vẻ và khách hàng trở thành bạn làm cho studio của chúng tôi là một nơi thực sự đặc biệt để phát triển sự nghiệp của bạn!',
    'massage-therapist': 'Hãy mang đôi tay chữa lành của bạn đến với gia đình wellness của chúng tôi! Chúng tôi đang tìm kiếm một nhà trị liệu massage tận tâm, người tin vào sức mạnh của xúc chạm trị liệu để thay đổi ngày của ai đó. Môi trường thoải mái, tích cực của chúng tôi giúp cả nhân viên và khách hàng cảm thấy thoải mái. Bạn sẽ làm việc với một đội ngũ hỗ trợ, tôn trọng chuyên môn của bạn và coi trọng sự cân bằng giữa công việc và cuộc sống. Giờ làm việc linh hoạt, không gian điều trị thoải mái và khách hàng biết ơn làm cho đây là một nơi thực sự đáng khen ngợi để thực hành nghề của bạn. Hãy tham gia cùng chúng tôi và chia sẻ món quà sức khỏe của bạn!',
    'makeup-artist': 'Mời các chuyên gia trang điểm sáng tạo tham gia vào gia đình làm đẹp của chúng tôi! Nếu bạn yêu thích việc làm cho khách hàng cảm thấy xinh đẹp và tự tin thông qua nghệ thuật trang điểm, chúng tôi muốn bạn trong đội ngũ của mình. Studio thân thiện, hỗ trợ của chúng tôi tôn vinh sự sáng tạo và kết nối cá nhân. Bạn sẽ thích thú làm việc với những khách hàng tuyệt vời cho các sự kiện đặc biệt, tạo ra những phong cách hàng ngày và chia sẻ niềm đam mê làm đẹp của bạn. Lịch làm việc linh hoạt, không khí vui vẻ và khách hàng rời đi như bạn bè làm cho studio của chúng tôi là nơi đầy niềm vui để phát triển nghệ thuật của bạn!',
    'tattoo-artist': 'Hãy tham gia vào gia đình studio xăm của chúng tôi, nơi nghệ thuật và cộng đồng hòa quyện! Chúng tôi đang tìm kiếm một nghệ sĩ tài năng mang đến năng lượng tích cực và đam mê sáng tạo vào công việc. Ngoài kỹ năng kỹ thuật tuyệt vời, chúng tôi đánh giá cao những nghệ sĩ kết nối với khách hàng và làm cho trải nghiệm xăm của họ đáng nhớ. Tiệm xăm thoải mái của chúng tôi có văn hóa hỗ trợ, không drama nơi các nghệ sĩ truyền cảm hứng cho nhau và cùng nhau phát triển. Lịch làm việc linh hoạt, các sự kiện tiệm thường xuyên và khách hàng trở thành bạn bè khiến đây là một nơi thực sự đặc biệt để tạo ra nghệ thuật lâu dài.',
    'booth-rental': 'Gọi các chuyên gia làm đẹp độc lập đang tìm kiếm ngôi nhà mới! Gia đình salon thân thiện, hỗ trợ của chúng tôi có không gian hoàn hảo cho bạn và khách hàng của bạn. Bạn sẽ thích thú với không khí ấm áp nơi mọi người tôn vinh thành công của nhau, các buổi gặp mặt salon thường xuyên và môi trường không drama. Không gian này bao gồm mọi thứ bạn cần để làm cho khách hàng của bạn cảm thấy đặc biệt, cộng thêm nhiều chỗ đậu xe và khả năng hiển thị tuyệt vời. Hãy mang tài năng và khách hàng của bạn đến – chúng tôi muốn chào đón bạn vào cộng đồng làm đẹp của chúng tôi!',
    'salon-manager': 'Hãy tham gia vào gia đình salon của chúng tôi với tư cách là người lãnh đạo mới! Chúng tôi đang tìm kiếm một người yêu thích con người với kinh nghiệm quản lý, người có thể hướng dẫn đội ngũ của chúng tôi với sự ấm áp và sự khôn ngoan. Bạn sẽ giúp nuôi dưỡng môi trường tích cực nơi sự sáng tạo phát triển và mọi người cảm thấy được đánh giá cao. Ngoài lịch trình và hoạt động, bạn sẽ là trái tim của văn hóa salon chúng tôi—tôn vinh những chiến thắng của đội, hướng dẫn tài năng mới và giữ cho năng lượng tích cực. Nếu bạn tin rằng lãnh đạo là về việc phát huy những điều tốt nhất ở người khác, chúng tôi muốn chào đón bạn vào gia đình làm đẹp gắn kết của chúng tôi!'
  },
  luxuryVi: {
    'nail-technician': 'Salon độc quyền của chúng tôi đang tìm kiếm một nghệ sĩ nail ưu tú để phục vụ khách hàng danh giá. Ứng viên lý tưởng sẽ thể hiện sự chính xác đặc biệt trong các dịch vụ cao cấp bao gồm móng gel, nail art vẽ tay và các liệu pháp đặc trưng. Bạn sẽ làm việc trong môi trường xa hoa với các sản phẩm cao cấp, thiết bị hiện đại và khách hàng tinh tế đòi hỏi sự hoàn hảo. Chúng tôi cung cấp mức lương cao, không khí tinh tế và cơ hội nâng cao nghệ thuật của bạn lên tiêu chuẩn cao nhất của ngành chăm sóc móng sang trọng.',
    'hair-stylist': 'Salon danh tiếng của chúng tôi mời các bậc thầy tạo mẫu tóc gia nhập đội ngũ độc quyền của chúng tôi phục vụ khách hàng tinh hoa. Chúng tôi tìm kiếm những nghệ sĩ thể hiện kỹ năng đặc biệt trong cắt chính xác, phối màu cao cấp và kỹ thuật tạo kiểu thảm đỏ. Danh mục công việc của bạn nên thể hiện những tác phẩm đột phá phản ánh tiêu chuẩn không thỏa hiệp. Môi trường sang trọng của chúng tôi có các tiện nghi cao cấp, công nghệ tân tiến và những dòng sản phẩm tốt nhất. Chúng tôi cung cấp đào tạo độc quyền với các nghệ sĩ nền tảng quốc tế và mức lương xứng đáng với những chuyên gia thiết kế tóc đẳng cấp nhất.',
    'spa-technician': 'Khu sanctuary spa nổi tiếng của chúng tôi đang tìm kiếm một chuyên gia chăm sóc da ưu tú để mang đến những trải nghiệm chăm sóc da siêu việt cho khách hàng danh giá. Ứng viên lý tưởng sẽ có chuyên môn trong các phương pháp tiên tiến bao gồm vi mài mòn kim cương, liệu pháp LED và các quy trình điều trị tùy chỉnh. Bạn sẽ làm việc với các dòng sản phẩm độc quyền, mang lại kết quả trong một không gian điều trị hoàn hảo được thiết kế cho sự thư giãn tối đa. Chúng tôi cung cấp mức lương cao, tiếp tục giáo dục với các chuyên gia chăm sóc da hàng đầu và môi trường tinh tế nơi sự xuất sắc là tiêu chuẩn duy nhất.',
    'receptionist': 'Salon sang trọng của chúng tôi đang tìm kiếm một Điều phối viên Quan hệ Khách hàng tinh tế để điều phối những trải nghiệm khách hàng đặc biệt. Ứng viên lý tưởng sẽ có kỹ năng giao tiếp hoàn hảo, sự kín đáo với khách hàng nổi tiếng và sự thanh lịch tự nhiên trong cách thể hiện. Bạn sẽ thành thạo hệ thống đặt lịch cao cấp của chúng tôi, tuyển chọn đồ uống và đảm bảo hành trình khách hàng suôn sẻ từ khi đến đến khi rời đi. Sự hiện diện tinh tế của bạn sẽ thiết lập tông cho không khí độc quyền của chúng tôi, nơi mọi chi tiết đều quan trọng và không có yêu cầu nào là quá xa hoa.',
    'lash-technician': 'Studio làm đẹp cao cấp của chúng tôi đang tìm kiếm một nghệ sĩ mi bậc thầy để phục vụ khách hàng tinh tế. Ứng viên lý tưởng sẽ thể hiện sự điêu luyện trong việc tạo ra các thiết kế mi tùy chỉnh bao gồm mi Russian volume, mega volume và kỹ thuật kết hợp. Bạn sẽ làm việc trong một không gian riêng sang trọng với các sản phẩm cao cấp và những công cụ tiên tiến nhất trong ngành. Salon độc quyền của chúng tôi cung cấp một trải nghiệm khách hàng vô song, và chúng tôi tìm kiếm một nghệ sĩ có kỹ thuật tinh tế và phương pháp tiếp cận tinh tế sẽ làm hài lòng những người sành mi khó tính nhất.',
    'massage-therapist': 'Khu sanctuary sức khỏe độc quyền của chúng tôi mời một nhà trị liệu massage xuất sắc tham gia vào đội ngũ các chuyên gia ưu tú. Chúng tôi tìm kiếm một bậc thầy về xúc chạm trị liệu với chuyên môn về các phương pháp cao cấp bao gồm liệu pháp đá nóng, liệu pháp hương thơm và kỹ thuật mô sâu nâng cao. Bạn sẽ thực hành trong một phòng điều trị riêng có các tiện nghi sang trọng và thiết bị hiện đại. Khách hàng tinh tế của chúng tôi mong đợi những trải nghiệm chuyển đổi được cung cấp với sự chú ý tinh tế đến từng chi tiết và chăm sóc cá nhân hóa.',
    'makeup-artist': 'Studio làm đẹp danh tiếng của chúng tôi đang tìm kiếm một chuyên gia trang điểm hàng đầu để phục vụ khách hàng độc quyền bao gồm cả người nổi tiếng và giới thượng lưu xã hội. Ứng viên lý tưởng sẽ thể hiện sự thành thạo về các kỹ thuật trang điểm sang trọng, lý thuyết màu sắc và dự báo xu hướng. Danh mục công việc của bạn nên thể hiện các sản phẩm chất lượng biên tập áp dụng được cho các sự kiện nổi bật, nhiếp ảnh và dịp đặc biệt. Bạn sẽ làm việc với những dòng mỹ phẩm độc quyền nhất trong một studio riêng được trang bị hoàn hảo. Chúng tôi cung cấp mức lương cao phản ánh nghệ thuật vô song mà khách hàng của chúng tôi mong đợi.',
    'tattoo-artist': 'Studio độc quyền của chúng tôi đang tìm kiếm một nghệ sĩ xăm xuất sắc để phục vụ những khách hàng tinh tế coi xăm nghệ thuật là biểu hiện sang trọng tối thượng. Ứng viên lý tưởng sẽ thể hiện sự thành thạo trong xăm nét mảnh, chân dung siêu thực và các kỹ thuật đổi mới vượt ra ngoài xăm thông thường. Bạn sẽ làm việc trong một môi trường studio riêng tư, giống như phòng trưng bày với thiết bị hiện đại và vật liệu cao cấp. Khách hàng của chúng tôi mong đợi sự chính xác hoàn hảo, đổi mới nghệ thuật và một trải nghiệm phản ánh sự đầu tư đáng kể mà họ đặt vào nghệ thuật vĩnh viễn.',
    'booth-rental': 'Cơ hội độc quyền cho một chuyên gia làm đẹp đã thành lập để tham gia vào địa chỉ danh giá của chúng tôi. Việc cho thuê không gian cao cấp này cung cấp một không gian vô song trong salon đạt giải thưởng của chúng tôi, nơi thường xuyên có khách hàng tinh tế. Không gian được bố trí thanh lịch có thiết bị cao cấp, các chi tiết hoàn thiện sang trọng và không khí phản ánh sự tinh tế. Tiền thuê bao gồm quyền truy cập vào các tiện nghi VIP của chúng tôi bao gồm dịch vụ concierge, đỗ xe valet cho khách và việc xuất hiện trên phương tiện truyền thông xã hội được chọn lọc của chúng tôi, chỉ trưng bày những chuyên gia làm đẹp xuất sắc nhất trong thành phố.',
    'salon-manager': 'Tập đoàn salon danh tiếng của chúng tôi đang tìm kiếm một Giám đốc Điều hành xuất sắc để điều phối sự xuất sắc trong mọi khía cạnh của cơ sở sang trọng. Ứng viên lý tưởng sẽ mang đến kinh nghiệm lãnh đạo tinh tế từ môi trường khách sạn cao cấp hoặc bán lẻ sang trọng. Bạn sẽ nuôi dưỡng đội ngũ nghệ sĩ ưu tú của chúng tôi, quản lý các mối quan hệ khách hàng VIP và đảm bảo các tiêu chuẩn nghiêm ngặt của chúng tôi được duy trì không thỏa hiệp. Vai trò này đòi hỏi óc kinh doanh tinh tế, ukieren hiểu biết tốt và khả năng dự đoán nhu cầu trong một môi trường nơi bình thường không bao giờ chấp nhận được.'
  },
  casualVi: {
    'nail-technician': 'Đang tìm thợ nail tài năng để tham gia vào salon thoải mái, dễ chịu của chúng tôi! Chúng tôi cần người giỏi về gel, bột đắp và nail art cơ bản. Phong cách của chúng tôi rất chill nhưng chúng tôi nghiêm túc với công việc - khách hàng của chúng tôi thích rời đi với niềm vui và bộ móng đẹp. Bạn sẽ tự quyết định nhịp độ làm việc với giờ linh hoạt, làm việc với một đội ngũ như bạn bè và hưởng lương cạnh tranh cùng tiền tip. Hãy mang kỹ năng và năng lượng tích cực của bạn đến - chúng tôi muốn bạn tham gia vào đội của chúng tôi!',
    'hair-stylist': 'Cần thợ tóc sành điệu cho salon hiện đại, thoải mái của chúng tôi! Chúng tôi đang tìm kiếm người yêu thích công việc của họ và mang năng lượng tốt đến ghế làm việc. Dù bạn thích cắt, nhuộm, balayage hay tất cả những điều trên, chúng tôi muốn xem bạn có thể làm gì. Salon của chúng tôi có không khí thư giãn, nơi khách hàng cảm thấy thoải mái và thợ tóc có thể là chính mình. Lịch làm việc linh hoạt, chia hoa hồng hợp lý và nơi làm việc không drama khiến đây là một nơi tuyệt vời để phát triển sự nghiệp và thích thú đi làm.',
    'spa-technician': 'Cần chuyên viên spa chill cho studio wellness thư giãn của chúng tôi! Chúng tôi đang tìm kiếm người có kỹ năng về chăm sóc da mặt và điều trị cơ thể nhưng cũng mang đến năng lượng tốt cho phòng điều trị. Nơi của chúng tôi có không khí thư giãn, không phán xét nơi khách hàng có thể thực sự thư giãn. Không có kịch bản spa khô khan ở đây - chỉ có sự chăm sóc chân thành và các liệu pháp hiệu quả. Bạn sẽ có giờ làm việc linh hoạt, không gian làm việc thoải mái và khách hàng đánh giá cao cách tiếp cận chân thực của bạn về chăm sóc da và sức khỏe. Hãy tham gia vào đội ngũ của chúng tôi và làm việc tốt trong một môi trường không áp lực!',
    'receptionist': 'Cần người lễ tân thân thiện cho salon chill của chúng tôi! Chúng tôi đang tìm kiếm người có thể xử lý các công việc cơ bản - đặt lịch hẹn, ghi danh khách hàng và giữ cho mọi thứ vận hành trơn tru - đồng thời thêm vào phong cách thư giãn, chào đón của chúng tôi. Không cần kinh nghiệm chính thức, chỉ cần kỹ năng tổ chức tốt và thái độ thân thiện tự nhiên. Bạn sẽ làm việc với giờ hợp lý trong một môi trường thoải mái với một đội ngũ đánh giá cao những gì bạn làm. Ngoài ra, bạn sẽ làm quen với những khách hàng tuyệt vời của chúng tôi và là một phần quan trọng để làm cho trải nghiệm của họ tuyệt vời!',
    'lash-technician': 'Cần nghệ sĩ mi cho studio làm đẹp ấm cúng của chúng tôi! Nếu bạn có kỹ năng với mi classic và volume và thích làm việc theo nhịp độ của riêng mình, chúng tôi muốn gặp bạn. Studio của chúng tôi có cảm giác thư giãn, ấm cúng nơi khách hàng có thể thư giãn trong các buổi hẹn và thực sự tận hưởng trải nghiệm. Bạn sẽ có quyền kiểm soát lịch trình của mình, một không gian làm việc thoải mái và khách hàng đánh giá cao những hàng mi đẹp mà không cần môi trường salon kiểu cách. Hãy mang kỹ năng và con người thật của bạn đến - chúng tôi quan tâm đến sự chân thực trong khi làm công việc tuyệt vời.',
    'massage-therapist': 'Cần nhà trị liệu massage cho trung tâm wellness chân thành của chúng tôi! Chúng tôi đang tìm kiếm người có kỹ năng massage vững chắc, tạo môi trường thoải mái, không phán xét cho tất cả khách hàng. Trung tâm của chúng tôi là về việc làm cho sức khỏe dễ tiếp cận và thú vị mà không có thái độ spa kiểu cách. Bạn sẽ làm việc với giờ hợp lý, có phòng điều trị thoải mái và kết nối với khách hàng đánh giá cao cách tiếp cận chân thành của bạn với bodywork. Hãy tham gia vào đội ngũ của chúng tôi và làm công việc bạn yêu thích ở một nơi cảm thấy tốt để hiện diện.',
    'makeup-artist': 'Cần chuyên gia trang điểm sáng tạo cho studio làm đẹp vui vẻ, dễ gần của chúng tôi! Chúng tôi đang tìm kiếm người yêu thích việc tạo ra mọi thứ từ phong cách tự nhiên hàng ngày đến full glam, mà không có không khí đáng sợ của quầy mỹ phẩm. Studio của chúng tôi là về việc làm cho khách hàng cảm thấy thoải mái và có một khoảng thời gian vui vẻ trong khi trở nên xinh đẹp. Bạn sẽ thích thú với một lịch trình linh hoạt, một không khí thư giãn và những khách hàng đánh giá cao tài năng và cách tiếp cận thân thiện của bạn. Nếu bạn yêu thích trang điểm và năng lượng tốt như nhau, chúng tôi sẽ rất vui khi bạn tham gia vào đội ngũ của chúng tôi!',
    'tattoo-artist': 'Cần nghệ sĩ xăm cho tiệm thân thiện, dễ chịu của chúng tôi! Chúng tôi đang tìm kiếm người mang kỹ năng kỹ thuật vững chắc và năng lượng tốt đến công việc của họ. Tiệm của chúng tôi có một phong cách chill, chào đón mà không có thái độ đáng sợ mà một số nơi có. Khách hàng đánh giá cao cách tiếp cận không phán xét và môi trường thư giãn của chúng tôi. Bạn sẽ có sự linh hoạt với lịch trình của mình, một không gian làm việc thoải mái và tự do phát triển phong cách nghệ thuật riêng của mình. Nếu bạn có tài năng, dễ làm việc cùng và muốn sáng tạo trong một khu vực không drama, hãy trò chuyện với chúng tôi!',
    'booth-rental': 'Cho thuê không gian làm việc chill trong salon thân thiện, thoải mái của chúng tôi! Hoàn hảo cho một stylist, thợ nail hoặc nghệ sĩ mi độc lập đang tìm kiếm một nơi thoải mái để làm việc. Phong cách ở đây thư giãn và chào đón - không có drama salon hay quy tắc nghiêm ngặt về cách bạn điều hành công việc kinh doanh của mình. Bạn sẽ có một không gian làm việc đẹp, tiền thuê hợp lý bao gồm tiện ích, nhiều chỗ đậu xe và hàng xóm tuyệt vời để làm việc cùng. Hãy đưa khách hàng của bạn đến một nơi mọi người có thể cảm thấy thoải mái và là chính mình!',
    'salon-manager': 'Cần quản lý salon cho tiệm hiện đại, không drama của chúng tôi! Chúng tôi đang tìm kiếm người có thể giữ cho mọi thứ vận hành trơn tru mà không tạo ra không khí doanh nghiệp. Bạn sẽ giúp phối hợp lịch trình, giữ cho vật tư đầy đủ và nói chung là đảm bảo mọi thứ hoạt động đúng, đồng thời vẫn duy trì không khí thư giãn. Người lý tưởng có tổ chức nhưng linh hoạt, giỏi giao tiếp với mọi người và hiểu rằng một đội ngũ hạnh phúc sẽ tạo ra khách hàng hạnh phúc. Giờ làm việc hợp lý, lương cạnh tranh và sự hài lòng khi dẫn dắt một salon nơi mọi người thực sự thích đi làm!'
  },
  detailedVi: {
    'nail-technician': "Vị trí: Thợ Nail có Bằng\n\nYêu cầu:\n• Tối thiểu 2 năm kinh nghiệm chuyên nghiệp\n• Giấy phép tiểu bang hiện hành\n• Chuyên môn trong đắp bột, hệ thống gel và chăm sóc móng tự nhiên\n• Thể hiện khả năng nail art\n• Kiến thức về quy trình vệ sinh đúng cách\n\nTrách nhiệm:\n• Thực hiện manicure, pedicure, sơn gel, đắp bột acrylic và dịch vụ bột nhúng\n• Duy trì sạch sẽ khu vực làm việc giữa mỗi khách hàng\n• Khử trùng đúng cách tất cả dụng cụ theo hướng dẫn tiểu bang\n• Giới thiệu sản phẩm chăm sóc tại nhà phù hợp\n• Duy trì hồ sơ khách hàng chính xác\n\nYêu cầu Lịch làm việc:\n• Phải làm việc 2 ca cuối tuần mỗi tuần\n• Giờ làm việc thông thường: 9:30 sáng - 7:00 tối\n• Có vị trí bán thời gian và toàn thời gian\n\nThù lao:\n• Dựa trên hoa hồng (45-55% dựa trên kinh nghiệm)\n• Có thưởng hiệu suất\n• Hoa hồng bán lẻ: 10% trên tất cả sản phẩm bán được\n• Đóng góp bảo hiểm sức khỏe cho nhân viên toàn thời gian\n• Cơ hội đào tạo tiếp tục được trả lương",
    'hair-stylist': "Vị trí: Thợ Tóc có Bằng\n\nYêu cầu:\n• Giấy phép tạo mẫu tóc hợp lệ\n• Tối thiểu 3 năm kinh nghiệm salon\n• Thành thạo kỹ thuật cắt cho tất cả các loại tóc\n• Chuyên môn về pha trộn và thực hiện màu\n• Cam kết đào tạo liên tục\n\nTrách nhiệm Chính:\n• Thực hiện cắt tóc chính xác cho nhiều loại khách hàng\n• Thực hiện dịch vụ màu bao gồm balayage, highlight và điều chỉnh màu\n• Tiến hành tư vấn kỹ lưỡng để đảm bảo sự hài lòng của khách hàng\n• Giới thiệu và giáo dục khách hàng về sản phẩm bán lẻ phù hợp\n• Duy trì không gian và thiết bị sạch sẽ, ngăn nắp\n\nYêu cầu Lịch làm việc:\n• Tối thiểu 32 giờ mỗi tuần cho vị trí toàn thời gian\n• Phải có mặt ít nhất một ca tối (đến 8 giờ tối)\n• Yêu cầu làm việc cuối tuần (tối thiểu 2 thứ Bảy mỗi tháng)\n\nGói Thù lao:\n• Cơ cấu hoa hồng cạnh tranh (45-60% dựa trên kinh nghiệm)\n• Hoa hồng sản phẩm: 10-15% trên tất cả doanh số bán lẻ\n• Đóng góp bảo hiểm sức khỏe sau thời gian thử việc 90 ngày\n• Phụ cấp giáo dục: $500 hàng năm cho các khóa học được phê duyệt\n• Nghỉ phép có lương (1 tuần hàng năm sau năm đầu tiên)\n• Đánh giá hiệu suất thường xuyên với cơ hội tăng hoa hồng",
    'spa-technician': "Vị trí: Chuyên Viên Chăm Sóc Da có Bằng\n\nYêu cầu:\n• Giấy phép thẩm mỹ tiểu bang hiện hành\n• Tối thiểu 1 năm kinh nghiệm trong môi trường spa\n• Kiến thức về các liệu pháp chăm sóc da nâng cao\n• Ưu tiên đào tạo về peel hóa học và vi mài mòn da\n• Chú ý đến chi tiết với thực hành vệ sinh xuất sắc\n\nTrách nhiệm Chính:\n• Thực hiện các liệu pháp facial tùy chỉnh dựa trên phân tích da\n• Thực hiện peel hóa học, liệu pháp enzyme và làm sạch sâu\n• Thực hiện kỹ thuật massage mặt đúng cách\n• Thực hiện liệu pháp toàn thân bao gồm tẩy tế bào chết và đắp mặt nạ\n• Duy trì hồ sơ khách hàng kỹ lưỡng và ghi chú điều trị\n• Giáo dục khách hàng về chế độ chăm sóc tại nhà phù hợp\n\nChi tiết Lịch làm việc:\n• 30-40 giờ hàng tuần (toàn thời gian)\n• 20-25 giờ hàng tuần (tùy chọn bán thời gian)\n• Làm việc buổi tối đến 8 giờ tối hai lần mỗi tuần\n• Yêu cầu luân phiên cuối tuần\n\nCơ cấu Thù lao:\n• Hoa hồng dịch vụ: 40-50% dựa trên kinh nghiệm\n• Hoa hồng bán lẻ: 15% trên tất cả sản phẩm bán được\n• Thưởng nâng cấp dịch vụ: $10 cho mỗi liệu pháp bổ sung\n• Chỉ tiêu liệu pháp hàng tháng với phần thưởng khuyến khích\n• Đào tạo sản phẩm và giáo dục liên tục được trả lương\n• Giảm giá nhân viên: 30% trên tất cả sản phẩm spa",
    'receptionist': "Vị trí: Điều phối viên Salon/Lễ tân\n\nYêu cầu Chính:\n• Bằng tốt nghiệp trung học hoặc tương đương\n• Yêu cầu kinh nghiệm dịch vụ khách hàng trước đây\n• Ưu tiên kinh nghiệm salon hoặc spa nhưng không bắt buộc\n• Kỹ năng máy tính thành thạo bao gồm phần mềm đặt lịch\n• Phong cách giao tiếp điện thoại chuyên nghiệp\n\nTrách nhiệm Chi tiết:\n• Quản lý lịch hẹn cho 8-10 nhà cung cấp dịch vụ\n• Xử lý việc đăng ký/thanh toán của khách hàng một cách hiệu quả\n• Xử lý các yêu cầu qua điện thoại và chuyển đổi cuộc gọi thành đặt lịch\n• Xử lý thanh toán chính xác bao gồm phân phối tiền tip\n• Duy trì trưng bày bán lẻ và xử lý hàng tồn kho\n• Thực hiện quy trình mở/đóng cửa\n• Đảm bảo khu vực lễ tân và khu vực giải khát luôn hoàn hảo\n• Phối hợp với nhà cung cấp dịch vụ về thay đổi lịch trình\n\nYêu cầu Lịch làm việc:\n• Vị trí toàn thời gian: 38-40 giờ mỗi tuần\n• Vị trí bán thời gian: 15-25 giờ mỗi tuần\n• Phải có mặt ít nhất 2 ca tối (đến 8 giờ tối)\n• Yêu cầu làm việc cuối tuần\n\nGói Thù lao:\n• Mức lương giờ: $15-18 dựa trên kinh nghiệm\n• Thưởng chuyển đổi đặt lịch hàng tháng (lên đến $200)\n• Hoa hồng bán lẻ: 5%\n• Giảm giá dịch vụ cho nhân viên: 30%\n• Giảm giá sản phẩm: 20%\n• Đánh giá hiệu suất sau 90 ngày với tiềm năng tăng lương",
    'lash-technician': "Vị trí: Nghệ sĩ Mi đã được Chứng nhận\n\nYêu cầu:\n• Chứng nhận nối mi hiện tại\n• Tối thiểu 1 năm kinh nghiệm mi chuyên nghiệp\n• Ưu tiên bằng tạo mẫu tóc hoặc thẩm mỹ\n• Chuyên môn trong kỹ thuật mi classic, hybrid và volume\n• Danh mục thể hiện độ chính xác kỹ thuật\n\nTrách nhiệm Chi tiết:\n• Thực hiện tư vấn khách hàng kỹ lưỡng để xác định phong cách mi phù hợp\n• Thực hiện bộ mi classic (90-120 phút)\n• Tạo bộ mi volume và hybrid (120-180 phút)\n• Thực hiện fill mi với đánh giá đúng các nối mi còn lại\n• Duy trì quy trình vệ sinh hoàn hảo\n• Ghi lại các dị ứng và phản ứng của khách hàng\n• Ghi lại sở thích của khách hàng cho các cuộc hẹn tương lai\n• Giáo dục khách hàng về chăm sóc sau đúng cách\n\nYêu cầu Lịch làm việc:\n• 25-40 giờ mỗi tuần dựa trên sở thích\n• Có mặt buổi tối đến 7 giờ tối hai lần mỗi tuần\n• Làm việc cuối tuần (tối thiểu 2 thứ Bảy mỗi tháng)\n• Lịch hẹn được sắp xếp với đủ thời gian giữa các khách hàng\n\nCơ cấu Thù lao:\n• Hoa hồng: 45-55% dựa trên kinh nghiệm và giữ chân khách hàng\n• Hoa hồng bán lẻ: 15% trên sản phẩm chăm sóc sau\n• Thưởng đặt lịch: $50 cho tuần đặt lịch đầy đủ\n• Tăng dựa trên hiệu suất được xem xét hàng quý\n• Trợ cấp giáo dục tiếp tục sau 6 tháng",
    'massage-therapist': "Vị trí: Nhà Trị liệu Massage có Giấy phép\n\nYêu cầu Giấy phép:\n• Giấy phép trị liệu massage tiểu bang hiện hành\n• Tối thiểu 500 giờ từ chương trình massage được công nhận\n• Bảo hiểm trách nhiệm\n• Chứng nhận CPR\n• Tối thiểu 1 năm kinh nghiệm chuyên nghiệp\n\nYêu cầu về Phương pháp:\n• Thành thạo kỹ thuật massage Thụy Điển\n• Kinh nghiệm về quy trình mô sâu\n• Các phương pháp khác mong muốn: massage thai sản, đá nóng, massage thể thao\n• Hiểu biết cơ bản về giải phẫu và chống chỉ định\n\nTrách nhiệm Chính:\n• Thực hiện các buổi massage 60, 90 và 120 phút\n• Tiến hành thu thập thông tin kỹ lưỡng đối với khách hàng mới\n• Ghi chép SOAP notes sau mỗi buổi\n• Duy trì sự sạch sẽ của phòng điều trị\n• Khử trùng thiết bị đúng cách giữa các khách hàng\n• Giao tiếp hiệu quả về áp lực và sự thoải mái của khách hàng\n• Giới thiệu kế hoạch điều trị thích hợp\n\nChi tiết Lịch làm việc:\n• Bán thời gian (15-25 giờ) và toàn thời gian (25-35 giờ) có sẵn\n• Tối đa 6 giờ massage mỗi ngày\n• Có mặt buổi tối đến 8 giờ tối hai lần mỗi tuần\n• Yêu cầu luân phiên cuối tuần (1-2 mỗi tháng)\n• 15 phút giữa các buổi để chuẩn bị lại phòng\n\nGói Thù lao:\n• Hoa hồng dịch vụ: 40-50% dựa trên kinh nghiệm\n• Thưởng dịch vụ bổ sung: $10 mỗi nâng cấp\n• Hoa hồng bán lẻ: 10% trên tất cả sản phẩm bán được\n• Khuyến khích đặt lịch lại: $5 cho mỗi khách hàng đặt lịch hẹn tiếp theo\n• Trao đổi massage hàng tháng giữa các nhân viên\n• Trợ cấp giáo dục tiếp tục sau một năm",
    'makeup-artist': "Vị trí: Chuyên gia Trang điểm Chuyên nghiệp\n\nYêu cầu Trình độ:\n• Ưu tiên bằng tạo mẫu tóc hoặc thẩm mỹ (không bắt buộc)\n• Tối thiểu 2 năm kinh nghiệm trang điểm chuyên nghiệp\n• Danh mục công việc mạnh thể hiện các ứng dụng trang điểm đa dạng\n• Kinh nghiệm với các loại da, tông màu và kết cấu khác nhau\n• Kiến thức về quy trình ứng dụng trang điểm vệ sinh\n\nTrách nhiệm Chi tiết:\n• Thực hiện tư vấn trang điểm đánh giá nhu cầu và sở thích của khách hàng\n• Thực hiện trang điểm cho các sự kiện đặc biệt, chụp ảnh và hàng ngày\n• Chuyên về trang điểm cô dâu với kỹ thuật thời gian và độ bền phù hợp\n• Duy trì bộ dụng cụ hoàn hảo với các sản phẩm cấp chuyên nghiệp\n• Khử trùng tất cả công cụ giữa các khách hàng theo tiêu chuẩn ngành\n• Tạo bảng màu khuôn mặt cho khách hàng mua sản phẩm\n• Giáo dục khách hàng về kỹ thuật ứng dụng để sử dụng tại nhà\n\nDịch vụ Được Mong đợi:\n• Trang điểm sự kiện đặc biệt (60 phút)\n• Trang điểm cô dâu bao gồm buổi thử\n• Trang điểm tự nhiên/ban ngày (30-45 phút)\n• Trang điểm buổi tối/trang trọng (45-60 phút)\n• Gắn lông mi giả\n• Bài học trang điểm (60-90 phút)\n\nYêu cầu Lịch làm việc:\n• Yêu cầu có mặt linh hoạt cho các sự kiện cuối tuần\n• Phải đáp ứng các cuộc hẹn sáng sớm cho các nhóm cô dâu\n• Lịch trình thông thường từ thứ Ba-thứ Bảy với các sự kiện Chủ nhật/thứ Hai khi được đặt lịch\n\nCơ cấu Thù lao:\n• Hoa hồng dịch vụ: 45-55% dựa trên kinh nghiệm\n• Hoa hồng bán lẻ: 15% trên tất cả sản phẩm trang điểm bán được\n• Thưởng đặt lịch cô dâu: $50 cho mỗi nhóm cô dâu đã đặt\n• Phí vận chuyển cho các dịch vụ tại chỗ\n• Trợ cấp bảo trì bộ dụng cụ: $200 mỗi quý",
    'tattoo-artist': "Vị trí: Nghệ sĩ Xăm Chuyên nghiệp\n\nYêu cầu:\n• Tối thiểu 3-5 năm kinh nghiệm xăm chuyên nghiệp\n• Chứng nhận mầm bệnh qua đường máu hiện hành\n• Danh mục công việc mạnh thể hiện đường nét sạch và phong cách đa dạng\n• Hiểu biết về quy trình khử trùng đúng cách\n• Khả năng tạo ra các thiết kế xăm tùy chỉnh từ ý tưởng của khách hàng\n\nTrách nhiệm Chi tiết:\n• Tiến hành tư vấn kỹ lưỡng để hiểu tầm nhìn của khách hàng\n• Tạo ra các thiết kế xăm tùy chỉnh và khuôn mẫu\n• Duy trì môi trường làm việc vô trùng\n• Thiết lập và dọn dẹp khu vực làm việc đúng cách cho mỗi khách hàng\n• Cung cấp hướng dẫn chi tiết về chăm sóc sau\n• Ghi lại công việc hoàn thành cho danh mục\n• Duy trì hệ thống đặt lịch có tổ chức cho khách hàng\n\nKỹ năng Kỹ thuật Yêu cầu:\n• Độ chính xác và nhất quán trong đường nét\n• Bão hòa màu sắc chắc chắn\n• Kỹ thuật đổ bóng\n• Hiểu biết về các loại da và cách chúng ảnh hưởng đến ứng dụng\n• Lựa chọn kim đúng cho các kỹ thuật khác nhau\n• Bảo trì máy và xử lý sự cố\n\nChi tiết Lịch làm việc:\n• Ngày làm việc điển hình: 12 giờ trưa - 8 giờ tối\n• 4-5 ngày mỗi tuần dựa trên sở thích\n• Yêu cầu làm việc cuối tuần (tối thiểu 2 mỗi tháng)\n• Thời gian được phân bổ giữa các cuộc hẹn để chuẩn bị thiết kế\n\nCơ cấu Thù lao:\n• Dựa trên hoa hồng: 60-70% giá xăm\n• Mức theo giờ: $150-200 dựa trên kinh nghiệm và nhu cầu\n• Phí vẽ cho thiết kế tùy chỉnh\n• Hệ thống đặt cọc cho các cuộc hẹn\n• Đảm bảo tối thiểu cho những ngày ít khách\n• Có sẵn trợ cấp vật tư",
    'booth-rental': "Cơ hội Thuê không gian làm việc\n\nChi tiết Không gian:\n• 100 feet vuông khu vực riêng tư với kho lưu trữ có khóa\n• Ghế tạo kiểu hiện đại và gương toàn thân đi kèm\n• Tủ tùy chỉnh với 5 ngăn kéo và kho lưu trữ sản phẩm kín\n• Đèn LED điều chỉnh được\n• Hai ổ cắm điện chuyên dụng với cổng USB\n• Bồn rửa riêng với nhiệt độ nước điều chỉnh được\n• Quyền truy cập vào khu vực pha màu chung và khu vực xử lý\n• Sử dụng khu vực gội đầu của salon cho khách hàng\n\nTiện ích Bao gồm:\n• Truy cập WiFi tốc độ cao\n• Đăng ký phần mềm đặt lịch trực tuyến\n• Dịch vụ lễ tân cho đăng ký và thanh toán\n• Dịch vụ khăn (giặt hàng ngày đi kèm)\n• Dịch vụ cà phê/trà/nước cho khách hàng\n• Phòng nghỉ chung với tủ lạnh và lò vi sóng\n• Tiện ích tòa nhà (nước, điện, HVAC)\n• Bảo hiểm trách nhiệm salon\n• Dịch vụ vệ sinh chuyên nghiệp hàng tuần\n• Tòa nhà an toàn với quyền truy cập 24 giờ\n\nĐặc điểm Vị trí:\n• Địa điểm bán lẻ khả năng hiển thị cao với biển hiệu đường phố\n• Nhiều chỗ đậu xe miễn phí (25+ chỗ)\n• Lối vào và cơ sở vật chất dễ tiếp cận cho xe lăn\n• Nằm trong trung tâm mua sắm với các doanh nghiệp bổ sung\n• Cách khu vực trung tâm 3 dặm\n\nĐiều khoản Thuê:\n• Thuê hàng tháng: $800-950 dựa trên vị trí không gian\n• $500 đặt cọc an ninh (hoàn lại được)\n• Thời gian thuê tối thiểu 6 tháng với tùy chọn hàng tháng sau đó\n• Tiền thuê tháng đầu tiên và tháng cuối cùng phải trả khi ký\n• Có sẵn tùy chọn kế hoạch thanh toán hàng tuần\n\nYêu cầu đối với Người thuê:\n• Giấy phép tiểu bang hiện hành trong lĩnh vực liên quan\n• Bằng chứng bảo hiểm trách nhiệm\n• Tối thiểu 2 năm kinh nghiệm chuyên nghiệp\n• Ưu tiên khách hàng đã thiết lập\n• Tham khảo từ liên kết salon trước đây",
    'salon-manager': "Vị trí: Quản lý/Giám đốc Salon\n\nYêu cầu Kinh nghiệm:\n• Tối thiểu 5 năm kinh nghiệm trong ngành salon\n• 2+ năm trong vai trò giám sát/quản lý\n• Thể hiện khả năng lãnh đạo đội ngũ\n• Kinh nghiệm quản lý tài chính và hoạt động mạnh mẽ\n• Ưu tiên bằng tạo mẫu tóc hoặc giáo dục ngành\n\nTrách nhiệm Chính:\n\nQuản lý Nhân viên:\n• Giám sát đội ngũ 12-15 nhà cung cấp dịch vụ\n• Tiến hành cuộc họp đội ngũ hàng tuần và đánh giá cá nhân hàng tháng\n• Tạo và quản lý lịch trình nhân viên đảm bảo phạm vi phù hợp\n• Thực hiện kế hoạch cải thiện hiệu suất khi cần thiết\n• Phối hợp cơ hội giáo dục liên tục\n• Dẫn dắt quá trình tuyển dụng cho các thành viên mới trong đội\n• Đóng vai trò trung gian giải quyết xung đột giữa các thành viên nhân viên\n\nNhiệm vụ Hoạt động:\n• Giám sát và duy trì tiêu chuẩn dịch vụ trên tất cả các bộ phận\n• Đảm bảo tuân thủ các quy định của hội đồng tiểu bang\n• Giám sát quản lý hàng tồn kho và đặt hàng sản phẩm\n• Quản lý trưng bày bán lẻ và khuyến mãi\n• Duy trì thiết bị và phối hợp sửa chữa khi cần\n• Xử lý bảng lương hai tuần một lần và tính toán hoa hồng\n• Tạo báo cáo hiệu suất nhân viên hàng tháng\n\nTrách nhiệm Tài chính:\n• Giám sát mục tiêu bán hàng hàng ngày và giải quyết thiếu hụt\n• Theo dõi vòng quay hàng tồn kho bán lẻ và hiệu suất sản phẩm\n• Phân tích số liệu năng suất của nhà cung cấp dịch vụ\n• Triển khai chiến lược giữ chân cả khách hàng và nhân viên\n• Kiểm soát chi phí trong khi duy trì chất lượng dịch vụ\n• Đạt hoặc vượt dự báo doanh thu hàng tháng\n\nYêu cầu Lịch làm việc:\n• Vị trí toàn thời gian (45-50 giờ hàng tuần)\n• Lịch làm việc thứ Ba-thứ Bảy với thỉnh thoảng buổi tối\n• Sẵn sàng cho bảo hiểm khẩn cấp khi cần\n\nGói Thù lao:\n• Lương cơ bản: $45,000-55,000 tương xứng với kinh nghiệm\n• Thưởng hiệu suất hàng tháng dựa trên lợi nhuận salon (lên đến $1,000)\n• Đóng góp bảo hiểm sức khỏe\n• Phụ cấp điện thoại di động\n• Nghỉ phép có lương (2 tuần hàng năm)\n• Dịch vụ miễn phí và giảm giá sản phẩm đáng kể\n• Đánh giá hiệu suất hàng quý với cơ hội điều chỉnh lương"
  }
};

// We also need Vietnamese job templates
export const JOB_TEMPLATES_VI: Partial<JobFormValues>[] = [
  {
    id: 'nail-technician',
    title: 'Thợ làm móng',
    type: 'Toàn thời gian',
    description: 'Chúng tôi đang tìm kiếm thợ nail có kinh nghiệm để tham gia vào đội ngũ của chúng tôi. Phải thành thạo làm móng tay, móng chân, sơn gel và đắp bột. Lương cạnh tranh và môi trường làm việc tuyệt vời.'
  },
  {
    id: 'hair-stylist',
    title: 'Thợ làm tóc',
    type: 'Toàn thời gian',
    description: 'Đang tuyển thợ tóc có kỹ năng với kinh nghiệm về cắt, nhuộm và tạo kiểu. Hãy tham gia vào đội ngũ của chúng tôi và làm việc trong môi trường salon tích cực với cơ sở khách hàng trung thành. Hoa hồng cạnh tranh và phúc lợi được cung cấp.'
  },
  {
    id: 'spa-technician',
    title: 'Kỹ thuật viên Spa',
    type: 'Toàn thời gian',
    description: 'Tham gia vào spa sang trọng của chúng tôi với tư cách là một kỹ thuật viên có kỹ năng. Chúng tôi đang tìm kiếm các chuyên gia có kinh nghiệm về chăm sóc da mặt, điều trị cơ thể và tư vấn chăm sóc da. Tạo ra những trải nghiệm thư giãn cho khách hàng quan trọng của chúng tôi.'
  },
  {
    id: 'receptionist',
    title: 'Lễ tân Salon',
    type: 'Toàn thời gian',
    description: 'Đang tìm một lễ tân thân thiện và có tổ chức cho salon bận rộn của chúng tôi. Trách nhiệm bao gồm lên lịch hẹn, chào đón khách hàng, trả lời điện thoại và xử lý thanh toán. Ưu tiên kinh nghiệm dịch vụ khách hàng.'
  },
  {
    id: 'lash-technician',
    title: 'Kỹ thuật viên nối mi',
    type: 'Toàn thời gian',
    description: 'Cần kỹ thuật viên nối mi có kinh nghiệm cho một studio mi đang phát triển. Phải thành thạo nối mi classic và volume với sự chú ý tuyệt vời đến chi tiết. Yêu cầu thái độ thân thiện và phong cách chuyên nghiệp.'
  },
  {
    id: 'massage-therapist',
    title: 'Chuyên viên massage',
    type: 'Toàn thời gian',
    description: 'Cần chuyên viên massage có giấy phép cho trung tâm wellness của chúng tôi. Yêu cầu kinh nghiệm trong các kỹ thuật massage khác nhau. Phải có kỹ năng dịch vụ khách hàng xuất sắc và khả năng tùy chỉnh các liệu pháp theo nhu cầu của khách hàng.'
  },
  {
    id: 'makeup-artist',
    title: 'Chuyên gia trang điểm',
    type: 'Toàn thời gian',
    description: 'Cần chuyên gia trang điểm tài năng cho studio làm đẹp của chúng tôi. Yêu cầu kinh nghiệm với trang điểm cô dâu, sự kiện đặc biệt và trang điểm hàng ngày. Phải có một danh mục công việc mạnh và kỹ năng giao tiếp với khách hàng xuất sắc.'
  },
  {
    id: 'tattoo-artist',
    title: 'Nghệ sĩ xăm',
    type: 'Toàn thời gian',
    description: 'Cần nghệ sĩ xăm chuyên nghiệp cho studio đã thành lập. Phải có danh mục công việc mạnh thể hiện kỹ năng kỹ thuật và khả năng nghệ thuật. Yêu cầu chứng nhận sức khỏe và an toàn.'
  },
  {
    id: 'booth-rental',
    title: 'Có chỗ cho thuê',
    type: 'Cho thuê ghế',
    description: 'Có không gian cho thuê trong salon bận rộn, đã thành lập tốt của chúng tôi. Vị trí tuyệt vời với lượng khách qua lại cao. Lý tưởng cho các chuyên gia làm đẹp độc lập có sẵn khách hàng. Đã bao gồm tất cả tiện ích. Gọi để biết chi tiết.'
  },
  {
    id: 'salon-manager',
    title: 'Quản lý Salon',
    type: 'Toàn thời gian',
    description: 'Cần quản lý salon có kinh nghiệm để giám sát hoạt động hàng ngày. Trách nhiệm bao gồm quản lý nhân viên, kiểm soát hàng tồn kho, lên lịch và đảm bảo dịch vụ khách hàng xuất sắc. Yêu cầu kinh nghiệm quản lý salon trước đây.'
  }
];
