
import { Translation } from "@/hooks/useTranslation";

// Define structure for job templates
export interface JobTemplate {
  id: string;
  title: string;
  type: string;
  description: string;
  titleVi?: string;
  descriptionVi?: string;
  keywords?: string[];
  keywordsVi?: string[];
}

// Comprehensive job templates with both English and Vietnamese content
export const JOB_TEMPLATES: JobTemplate[] = [
  {
    id: "nail-technician",
    title: "Nail Technician",
    titleVi: "Thợ Nail",
    type: "full-time",
    description: "We are looking for experienced nail technicians to join our team. Must be skilled in manicures, pedicures, gel polish, and acrylic application. Competitive pay and great working environment.",
    descriptionVi: "Tiệm nail đang tuyển thợ có kinh nghiệm làm móng tay, móng chân, đắp bột và sơn gel. Môi trường làm việc thoải mái, lương cao, tip hậu, khách đông.",
    keywords: ["manicure", "pedicure", "acrylic", "gel", "polish", "nail art"],
    keywordsVi: ["làm móng", "đắp bột", "sơn gel", "móng chân", "móng tay", "vẽ móng"]
  },
  {
    id: "hair-stylist",
    title: "Hair Stylist",
    titleVi: "Thợ Làm Tóc",
    type: "full-time",
    description: "Seeking professional hair stylists with experience in cutting, coloring, and styling. Must have a great eye for detail and passion for keeping up with the latest trends.",
    descriptionVi: "Cần thợ tóc chuyên nghiệp có kinh nghiệm cắt, nhuộm và tạo kiểu tóc. Phải có mắt thẩm mỹ tốt và đam mê cập nhật xu hướng mới nhất.",
    keywords: ["haircut", "color", "style", "blowout", "hair treatment", "balayage"],
    keywordsVi: ["cắt tóc", "nhuộm tóc", "tạo kiểu", "uốn tóc", "ép tóc", "duỗi tóc"]
  },
  {
    id: "spa-technician",
    title: "Spa Technician",
    titleVi: "Kỹ Thuật Viên Spa",
    type: "full-time",
    description: "Now hiring spa technicians with knowledge of skincare treatments, facials, and body treatments. Must create a relaxing environment for clients.",
    descriptionVi: "Đang tuyển kỹ thuật viên spa có kiến thức về chăm sóc da, facial và các liệu trình điều trị cơ thể. Cần tạo không khí thư giãn cho khách hàng.",
    keywords: ["facial", "skincare", "treatment", "spa", "relaxation"],
    keywordsVi: ["chăm sóc da", "facial", "trị liệu", "spa", "thư giãn", "massage mặt"]
  },
  {
    id: "salon-receptionist",
    title: "Salon Receptionist",
    titleVi: "Lễ Tân Tiệm",
    type: "full-time",
    description: "Looking for a friendly, organized receptionist to manage appointments, greet clients, and handle payments. Must have excellent communication skills and be able to multitask.",
    descriptionVi: "Tìm lễ tân thân thiện, có tổ chức để quản lý lịch hẹn, chào đón khách hàng và xử lý thanh toán. Cần có kỹ năng giao tiếp tốt và khả năng đa nhiệm.",
    keywords: ["reception", "customer service", "scheduling", "payments", "organization"],
    keywordsVi: ["tiếp tân", "dịch vụ khách hàng", "lịch hẹn", "thanh toán", "tổ chức"]
  },
  {
    id: "salon-manager",
    title: "Salon Manager",
    titleVi: "Quản Lý Tiệm",
    type: "full-time",
    description: "Seeking experienced salon manager to oversee daily operations, manage staff, and ensure excellent customer service. Must have previous salon or retail management experience.",
    descriptionVi: "Tìm quản lý tiệm có kinh nghiệm để giám sát hoạt động hàng ngày, quản lý nhân viên và đảm bảo dịch vụ khách hàng xuất sắc. Yêu cầu có kinh nghiệm quản lý tiệm hoặc bán lẻ trước đây.",
    keywords: ["management", "leadership", "operations", "scheduling", "inventory"],
    keywordsVi: ["quản lý", "lãnh đạo", "vận hành", "sắp xếp lịch", "quản lý kho"]
  },
  {
    id: "massage-therapist",
    title: "Massage Therapist",
    titleVi: "Thợ Massage",
    type: "full-time",
    description: "Now hiring licensed massage therapists with experience in Swedish, deep tissue, and hot stone techniques. Must be able to customize treatments to meet client needs.",
    descriptionVi: "Đang tuyển thợ massage có bằng cấp và kinh nghiệm về kỹ thuật massage Thụy Điển, deep tissue và đá nóng. Cần có khả năng tùy chỉnh liệu trình điều trị để đáp ứng nhu cầu của khách hàng.",
    keywords: ["massage", "therapy", "relaxation", "deep tissue", "swedish", "hot stone"],
    keywordsVi: ["massage", "liệu pháp", "thư giãn", "deep tissue", "đá nóng", "bấm huyệt"]
  },
  {
    id: "lash-technician",
    title: "Lash Technician",
    titleVi: "Thợ Nối Mi",
    type: "full-time",
    description: "Seeking skilled eyelash technicians experienced in classic, hybrid, and volume lash extensions. Attention to detail and steady hands required.",
    descriptionVi: "Tìm thợ nối mi có kỹ năng và kinh nghiệm về nối mi classic, hybrid và volume. Yêu cầu tỉ mỉ và tay nghề vững vàng.",
    keywords: ["lash extensions", "volume lashes", "hybrid lashes", "eyelash", "classic lashes"],
    keywordsVi: ["nối mi", "mi volume", "mi hybrid", "mi classic", "mi 3D", "mi chân chồn"]
  },
  {
    id: "tattoo-artist",
    title: "Tattoo Artist",
    titleVi: "Thợ Xăm",
    type: "full-time",
    description: "Looking for talented tattoo artists with a strong portfolio. Must be experienced in various styles and committed to safe, hygienic practices.",
    descriptionVi: "Đang tìm thợ xăm tài năng có portfolio ấn tượng. Phải có kinh nghiệm về nhiều phong cách và cam kết thực hành an toàn, vệ sinh.",
    keywords: ["tattoo", "ink", "design", "art", "linework", "shading"],
    keywordsVi: ["xăm", "hình xăm", "thiết kế", "nghệ thuật", "xăm hình", "xăm thẩm mỹ"]
  },
  {
    id: "makeup-artist",
    title: "Makeup Artist",
    titleVi: "Thợ Trang Điểm",
    type: "full-time",
    description: "Seeking creative makeup artists for bridal, special event, and photoshoot services. Must have a diverse portfolio and experience with various skin tones and face shapes.",
    descriptionVi: "Tìm thợ trang điểm sáng tạo cho dịch vụ cưới, sự kiện đặc biệt và chụp ảnh. Phải có portfolio đa dạng và kinh nghiệm với các tông da và khuôn mặt khác nhau.",
    keywords: ["makeup", "bridal", "event makeup", "beauty", "cosmetics", "glam"],
    keywordsVi: ["trang điểm", "makeup cô dâu", "makeup sự kiện", "làm đẹp", "mỹ phẩm", "trang điểm chuyên nghiệp"]
  },
  {
    id: "booth-rental",
    title: "Booth Rental Available",
    titleVi: "Cho Thuê Bàn/Chỗ Ngồi",
    type: "other",
    description: "Premium booth/station rental available in busy salon. Great location with established clientele. All utilities included and flexible terms available.",
    descriptionVi: "Cho thuê chỗ/bàn làm việc cao cấp tại tiệm đông khách. Vị trí đẹp với khách hàng sẵn có. Đã bao gồm tiện ích và có điều khoản linh hoạt.",
    keywords: ["booth rental", "station rental", "chair rental", "space", "salon rental"],
    keywordsVi: ["cho thuê bàn", "cho thuê ghế", "thuê chỗ", "chia phòng", "cho thuê không gian"]
  },
  {
    id: "other-beauty",
    title: "Other Beauty Professional",
    titleVi: "Ngành Làm Đẹp Khác",
    type: "full-time",
    description: "Seeking beauty professionals for our expanding services. If you specialize in microblading, permanent makeup, body sculpting, or other beauty services, we want to talk to you!",
    descriptionVi: "Tìm kiếm chuyên gia làm đẹp cho các dịch vụ mở rộng của chúng tôi. Nếu bạn chuyên về phun xăm, trang điểm vĩnh viễn, giảm béo hoặc các dịch vụ làm đẹp khác, hãy liên hệ với chúng tôi!",
    keywords: ["beauty", "specialist", "aesthetician", "skincare", "treatments"],
    keywordsVi: ["làm đẹp", "chuyên gia", "thẩm mỹ", "chăm sóc da", "điều trị", "phun xăm"]
  }
];

// Template suggestions based on job types
export const POLISHED_DESCRIPTIONS = {
  // English templates by style
  professional: {
    "nail-technician": "We are seeking a skilled nail technician to join our established salon. The ideal candidate will have experience with manicures, pedicures, gel polish, acrylic applications, and nail art. Must maintain a clean workspace and provide excellent customer service. Competitive pay structure with opportunities for growth. Full-time position available immediately with a loyal client base.",
    "hair-stylist": "Our upscale salon is looking for an experienced hair stylist with expertise in cutting, coloring, highlighting, and styling techniques. The ideal candidate will have a proven track record of client retention and technical skills. Must stay current with industry trends and be able to consult clients on hair care and styling options. Competitive commission structure with benefits available.",
    "spa-technician": "We are currently hiring a licensed spa technician with experience in facials, body treatments, and skincare protocols. The ideal candidate will have knowledge of various skincare lines and treatment modalities, maintaining a serene environment for clients, and providing personalized care. Must be able to recommend appropriate products and home care regimens. Competitive pay plus retail commission.",
    "salon-receptionist": "Our busy salon is seeking a professional receptionist to manage front desk operations. Responsibilities include scheduling appointments, processing payments, greeting clients, answering phones, and maintaining the reception area. The ideal candidate will be organized, computer-savvy, and have excellent customer service skills. Must be able to multitask in a fast-paced environment. Full-time position with competitive hourly rate.",
    "salon-manager": "Established salon seeking an experienced manager to oversee daily operations, staff supervision, inventory management, and customer relations. The ideal candidate will have previous salon leadership experience, strong communication skills, and the ability to drive business growth. Responsibilities include scheduling, performance management, and ensuring exceptional service standards. Competitive salary plus bonus structure based on salon performance.",
    "massage-therapist": "We are seeking a licensed massage therapist proficient in various modalities including Swedish, deep tissue, and therapeutic techniques. The ideal candidate will be able to customize treatments based on client needs, maintain detailed SOAP notes, and uphold the highest standards of professionalism. Must be able to perform multiple sessions per day while maintaining quality. Competitive pay structure with tips and benefits.",
    "lash-technician": "Our salon is looking for a certified lash technician experienced in classic, volume, and hybrid extensions. The ideal candidate will have excellent attention to detail, steady hands, and the ability to create customized looks for each client. Must maintain a clean workspace and adhere to all safety protocols. Full-time position with competitive pay structure based on experience and skill level.",
    "tattoo-artist": "Professional tattoo studio seeking an experienced artist to join our team. The ideal candidate will have a strong portfolio demonstrating versatility in styles, excellent drawing skills, and knowledge of proper sterilization protocols. Must be licensed and have at least 2 years of professional experience. Commission-based compensation with opportunity for growth and loyal clientele development.",
    "makeup-artist": "We are hiring a professional makeup artist with experience in bridal, special event, and photography makeup applications. The ideal candidate will be knowledgeable about different products, techniques for various skin types, and current trends. Must be able to create looks ranging from natural to dramatic based on client preferences. Full-time position with competitive pay structure and opportunities for additional event bookings.",
    "booth-rental": "Premium booth rental opportunity available for established beauty professionals in our high-end salon. Space includes modern styling station, storage, and access to salon amenities. Ideal for professionals with an existing clientele looking for an upscale environment. Flexible lease terms available with reasonable weekly/monthly rates. All utilities included with opportunity for retail commission.",
    "other-beauty": "Our wellness center is seeking licensed beauty professionals specializing in advanced aesthetics such as microblading, permanent makeup, medical-grade skincare treatments, or body contouring. The ideal candidate will have certification in their specialty, liability insurance, and a portfolio of work. Must be able to consult clients on procedures and maintain thorough records. Competitive compensation structure based on experience and specialty."
  },
  friendly: {
    "nail-technician": "Join our fun, supportive nail salon family! We're looking for a friendly nail tech who loves creating beautiful manicures, pedicures, and nail art. If you enjoy making clients feel pampered and love keeping up with the latest nail trends, we'd love to meet you! Our team values work-life balance, celebrates birthdays, and truly cares about each other's success. Great pay, steady clients, and a positive atmosphere await!",
    "hair-stylist": "Come be part of our creative hair salon team! We're looking for a passionate stylist who loves transforming clients with amazing cuts, colors, and styles. Our salon has a fun, collaborative atmosphere where we share techniques and celebrate each other's creativity. If you enjoy making people feel beautiful and confident while working with a supportive team, this is the place for you! Flexible schedule with great earning potential.",
    "spa-technician": "Join our peaceful spa team! We're looking for a caring spa technician who loves helping clients relax and feel rejuvenated through facials, body treatments, and skincare services. Our spa values creating a supportive, calm environment for both clients and team members. If you're passionate about wellness and making people feel their best, we'd love to chat! Competitive pay plus a serene work environment.",
    "salon-receptionist": "Be the friendly face of our salon! We're seeking a warm, welcoming receptionist to greet clients, schedule appointments, and keep our front desk running smoothly. If you love connecting with people, have a knack for organization, and enjoy being part of a fun, dynamic team, this role is perfect for you! No beauty experience needed - just bring your positive attitude and people skills. Great hourly pay plus team perks!",
    "salon-manager": "Lead our amazing salon team! We're looking for a supportive, motivating salon manager who can bring out the best in our stylists while ensuring our clients have an amazing experience. If you're a people person with leadership experience and a passion for the beauty industry, we want to talk to you! This role offers work-life balance, competitive salary, and the chance to help shape our salon's future success.",
    "massage-therapist": "Join our wellness team as a massage therapist! We're looking for someone who loves helping clients feel better through the healing power of touch. Our relaxed environment values work-life balance, continuing education, and therapist wellbeing. If you're passionate about massage therapy and creating personalized experiences for clients, we'd love to meet you! Flexible schedule, great compensation, and a supportive team atmosphere.",
    "lash-technician": "Calling all lash artists! Join our fun, supportive beauty team and help clients feel gorgeous with stunning lash extensions. We value creativity, attention to detail, and creating a positive experience for everyone who sits in your chair. Our salon has a friendly vibe where we celebrate each other's work and growth. Great earning potential with flexible scheduling options!",
    "tattoo-artist": "Join our creative tattoo family! We're seeking an artist who loves creating meaningful, beautiful tattoos in our welcoming studio. Our shop values artistic freedom, collaboration, and making clients feel comfortable throughout their tattoo journey. If you have a unique style, enjoy connecting with clients, and want to work in a drama-free environment, reach out! Commission-based pay with plenty of walk-ins and appointment opportunities.",
    "makeup-artist": "Be part of our glam squad! We're looking for a makeup artist who loves making clients feel beautiful for their special moments. Whether it's bridal makeup, special events, or everyday glam, if you enjoy transforming faces and boosting confidence, we want you on our team! Our friendly studio values creativity, continuing education, and celebrating each other's artistic wins. Flexible schedule with great earning potential!",
    "booth-rental": "Looking for beauty professionals to join our salon family! We have beautiful booth spaces available in our friendly, supportive salon. Enjoy the freedom of running your own business while being part of a community that celebrates each other's success. Our location has great foot traffic, parking, and a welcoming atmosphere that clients love. Affordable weekly/monthly rates with no long-term commitment required!",
    "other-beauty": "Join our innovative beauty team! We're looking for passionate professionals specializing in brows, permanent makeup, skincare, or other beauty services. Our welcoming studio values creativity, continuing education, and making clients feel amazing. If you love what you do and want to work in a supportive environment with freedom to grow your specialty, let's talk! Flexible scheduling with competitive commission structure."
  },
  luxury: {
    "nail-technician": "Exclusive luxury nail salon seeking an elite nail artist to serve our discerning clientele. The ideal candidate will deliver flawless manicures, pedicures, and artistic nail designs with meticulous attention to detail. Must be experienced in premium product lines and provide an exceptional, personalized experience. Our upscale environment caters to high-end clients expecting superior service. Generous compensation package includes premium commission structure, gratuities, and luxury brand partnerships.",
    "hair-stylist": "Premier luxury salon inviting a master hair stylist to join our exclusive team. Catering to an elite clientele, we seek an artist who excels in precision cutting, couture color techniques, and transformative styling. The ideal candidate will have training from renowned institutions and experience in high-end salons or editorial work. Exceptional service standards and impeccable presentation required. Substantial earning potential with commission on services and premium product sales.",
    "spa-technician": "Prestigious spa seeking an exceptional aesthetician to deliver transformative skincare treatments to our exclusive clientele. The ideal candidate will be versed in advanced techniques, luxury product lines, and personalized protocol development. Must provide a seamless, indulgent experience from consultation to completion. Our serene environment caters to discerning clients expecting extraordinary results. Generous compensation includes premium service rates, gratuities, and performance bonuses.",
    "salon-receptionist": "Luxury beauty destination seeking a sophisticated front desk concierge to enhance our client experience. The ideal candidate will possess exceptional poise, discretion, and attention to detail when managing our high-profile clientele. Responsibilities include curating seamless appointments, anticipating client needs, and maintaining our elegant reception area. Impeccable presentation and communication skills essential. Competitive salary with benefits befitting our premium brand standards.",
    "salon-manager": "Prestigious salon group seeking an accomplished leader to oversee operations of our flagship luxury location. The ideal candidate will have experience managing high-end beauty or hospitality venues, understanding the nuances of premium service delivery and team excellence. Must maintain exacting standards while driving business growth and fostering relationships with our exclusive clientele. Executive compensation package includes salary, performance bonuses, and premium benefits.",
    "massage-therapist": "Elite wellness sanctuary seeking a master massage therapist to provide transcendent experiences for our distinguished clientele. The ideal candidate will possess advanced certification in multiple modalities, including deep tissue, hot stone, and therapeutic techniques. Must create bespoke treatments tailored to individual needs with impeccable attention to detail. Our tranquil setting demands a therapist who delivers an exceptional journey from welcome to farewell. Premium compensation structure with substantial gratuities.",
    "lash-technician": "Prestigious beauty atelier seeking a premier lash artist to create stunning, bespoke eyelash enhancements for our exclusive clientele. The ideal candidate will demonstrate mastery of classic, volume, and hybrid techniques with immaculate precision. Must maintain the highest standards of safety and elegance throughout the client experience. Our luxurious setting caters to discerning clients expecting exceptional results. Premium compensation package includes high service rates and performance incentives.",
    "tattoo-artist": "High-end private tattoo studio seeking a distinguished artist to serve our exclusive clientele. The ideal candidate will demonstrate masterful technique, distinctive artistic style, and experience with affluent clients. Our appointment-only atelier provides a discreet, luxurious environment for sophisticated collectors seeking custom body art. Exceptional consultation skills and portfolio required. Premium compensation structure reflects the exclusivity of our clientele and services.",
    "makeup-artist": "Luxury beauty destination seeking an elite makeup artist to create flawless, sophisticated looks for our distinguished clientele. The ideal candidate will have experience with celebrity clients, editorial work, or luxury brand partnerships. Must demonstrate versatility across classic elegance and current trends while providing an indulgent beauty experience. Our premium setting demands impeccable product knowledge and personalized service. Substantial earning potential with high service rates and gratuities.",
    "booth-rental": "Exclusive opportunity to join the most prestigious address in beauty. Premium private suite available for established beauty artist with elite clientele. Our landmark location offers unparalleled luxury, security, and discretion. Space features bespoke fixtures, premium amenities, and concierge services. Ideal for the accomplished professional seeking an environment that reflects their standard of excellence. Flexible terms for the right artist with proven high-end clientele.",
    "other-beauty": "Prestigious beauty institute seeking a specialized expert in advanced aesthetic procedures for our exclusive clientele. The ideal candidate will be masterfully skilled in their specialty, whether microblading, permanent makeup, or specialized skin treatments. Must provide an exceptional experience with meticulous attention to detail and personalized care. Our luxurious, discreet setting serves sophisticated clients expecting superior results. Premium compensation reflecting the exclusivity of your artistry and services."
  },
  casual: {
    "nail-technician": "Busy nail salon looking for a nail tech to start right away! Good with regular manicures, pedicures, and gel polish. Friendly attitude and reliable attendance a must. Steady clients and good tips for the right person. Weekend availability needed. Come join our team!",
    "hair-stylist": "Local hair salon needs a stylist who can handle cuts, color, and basic styles. Must be reliable and good with customers. Booth rental or commission available. Bring your own tools, but color provided. Flexible schedule with weekend shifts. Walk-ins and regular clients waiting for you!",
    "spa-technician": "Neighborhood spa looking for a tech who knows facials and body treatments. No need for years of experience - willing to train someone with the right attitude. Part-time or full-time available. Relaxed environment with steady appointments and good tips. Some weekend hours required.",
    "salon-receptionist": "Need a friendly front desk person for our busy salon! Answer phones, book appointments, and check clients in/out. Basic computer skills needed. No beauty experience required - just reliable and good with people. Part-time to start with possibility of full-time. Weekend availability a plus!",
    "salon-manager": "Local salon looking for someone to help run daily operations. Need to be organized, good with people, and able to handle schedules, supplies, and basic bookkeeping. Previous salon experience helpful but not required for the right person. Full-time position with competitive hourly rate plus bonuses.",
    "massage-therapist": "Casual spa needs a massage therapist ASAP! Must be licensed and know the basics - Swedish, deep tissue, relaxation. Bring your own sheets, we provide table and supplies. Friendly, laid-back environment with steady bookings. Choose your own hours with some weekend availability required. Great tips!",
    "lash-technician": "Busy beauty spot needs a lash tech! Classic and volume experience preferred. Part-time to start, could become full-time. Bring your own supplies, we provide the space. Relaxed vibe with regular clients already asking for lash services. Make your own schedule with some weekend availability.",
    "tattoo-artist": "Local shop looking for a tattoo artist to join our crew. Should be comfortable with walk-ins and custom work. Flash designs available or bring your own style. Clean work and good attitude more important than years of experience. Commission split is fair with opportunity to build your client list quickly.",
    "makeup-artist": "Need a makeup artist for our salon! Special events, basic makeovers, and everyday looks. Perfect for someone building their portfolio. Part-time hours available with extra bookings for weddings and events. Some makeup provided, bring your favorite products. Weekend availability important.",
    "booth-rental": "Got a station open for rent! Great location with lots of foot traffic. Bring your own clients or build from our walk-ins. All utilities included, just pay weekly booth fee. No long-term contract - simple week-to-week rental. Perfect for stylists, barbers, braiders, or nail techs with some experience.",
    "other-beauty": "Local beauty spot has room for someone doing brows, permanent makeup, or other beauty services. Part-time space available - rent by the day or specific hours each week. Bring your own supplies and clients, or build from our customer base. Laid-back atmosphere with flexible scheduling options."
  },
  detailed: {
    "nail-technician": "Position: Nail Technician\n\nResponsibilities:\n• Perform manicures, pedicures, gel polish applications\n• Apply and maintain acrylic nails and nail extensions\n• Create custom nail art and designs\n• Maintain strict sanitation standards\n• Build client relationships and retain customers\n\nRequirements:\n• Valid nail technician license\n• Minimum 1 year experience preferred\n• Knowledge of proper sanitation procedures\n• Excellent customer service skills\n• Weekend availability required\n\nCompensation:\n• Competitive commission (up to 60%)\n• Credit card tips paid daily\n• Product commission bonuses\n• Guaranteed minimum wage during slow periods\n• Health insurance available after probation period",
    "hair-stylist": "Position: Hair Stylist\n\nResponsibilities:\n• Perform precision haircuts for diverse clientele\n• Execute color services including highlights, balayage, and corrective color\n• Create special occasion and bridal hairstyles\n• Consult with clients on hair care and styling options\n• Recommend appropriate retail products\n\nRequirements:\n• Valid cosmetology license\n• Minimum 2 years salon experience preferred\n• Color certification recommended\n• Excellent customer service skills\n• Must provide own cutting tools\n\nCompensation:\n• Competitive commission structure (45-60%)\n• Retail commission (10-15%)\n• Health benefits for full-time stylists\n• Paid continuing education opportunities\n• 401k program available after 1 year",
    "spa-technician": "Position: Spa Technician/Esthetician\n\nResponsibilities:\n• Perform facial treatments and skin analysis\n• Administer body treatments and exfoliation services\n• Provide waxing and hair removal services\n• Maintain treatment rooms to highest cleanliness standards\n• Educate clients on home care regimens\n\nRequirements:\n• Valid esthetician license\n• Knowledge of skincare lines and ingredients\n• Experience with various facial technologies preferred\n• Excellent customer service skills\n• Ability to work evenings and weekends\n\nCompensation:\n• Hourly base + commission structure\n• Treatment add-on bonuses\n• Retail commission (15%)\n• Monthly treatment quotas with bonuses\n• Free/discounted services and products",
    "salon-receptionist": "Position: Salon Receptionist\n\nResponsibilities:\n• Manage appointment scheduling system\n• Process client payments and handle cash drawer\n• Answer multi-line phone system\n• Greet clients and offer refreshments\n• Maintain cleanliness of reception area\n• Assist with inventory management\n\nRequirements:\n• High school diploma or equivalent\n• Previous customer service experience\n• Proficiency with computer booking systems\n• Excellent communication skills\n• Ability to multitask in fast-paced environment\n\nCompensation:\n• Competitive hourly rate ($15-18/hour)\n• Retail commission opportunities\n• Tip share program\n• Employee discount on services and products\n• Paid time off after probation period",
    "salon-manager": "Position: Salon Manager\n\nResponsibilities:\n• Oversee daily operations and staff scheduling\n• Manage inventory and supply ordering\n• Train and develop service providers\n• Handle client concerns and maintain service standards\n• Monitor salon performance metrics\n• Implement marketing initiatives\n\nRequirements:\n• Minimum 3 years salon industry experience\n• Previous management experience preferred\n• Strong leadership and communication skills\n• Computer proficiency including POS systems\n• Cosmetology license a plus but not required\n\nCompensation:\n• Base salary ($50,000-65,000 annually)\n• Performance-based quarterly bonuses\n• Health insurance and retirement benefits\n• Paid vacation and sick leave\n• Continuing education allowance",
    "massage-therapist": "Position: Licensed Massage Therapist\n\nResponsibilities:\n• Perform various massage modalities (Swedish, Deep Tissue, Hot Stone)\n• Customize treatments based on client needs\n• Maintain accurate client records\n• Adhere to proper draping and professional standards\n• Maintain treatment room cleanliness\n\nRequirements:\n• Current massage therapy license\n• Minimum 500 hours certified training\n• Liability insurance\n• Physical stamina for multiple sessions\n• Available for weekend shifts\n\nCompensation:\n• $25-40 per service hour + tips\n• Commission on product sales\n• Free monthly massages\n• Continuing education stipend\n• Healthcare contribution after 90 days",
    "lash-technician": "Position: Eyelash Extension Technician\n\nResponsibilities:\n• Apply classic, hybrid, and volume lash extensions\n• Perform lash lifts and tints\n• Conduct thorough client consultations\n• Maintain precise application records\n• Clean and sanitize tools and workspace\n\nRequirements:\n• Certification in eyelash extensions\n• Cosmetology or esthetician license preferred\n• Excellent hand-eye coordination\n• Attention to detail and patience\n• Portfolio of previous work\n\nCompensation:\n• Commission-based pay (50-70%)\n• Retail commission on lash care products\n• Booking bonuses for filled schedules\n• Paid advanced training opportunities\n• Flexible scheduling available",
    "tattoo-artist": "Position: Tattoo Artist\n\nResponsibilities:\n• Create custom tattoo designs based on client requests\n• Apply tattoos using proper techniques and equipment\n• Maintain strict sterilization and safety protocols\n• Provide aftercare instructions to clients\n• Contribute to shop's artistic environment\n\nRequirements:\n• Minimum 2 years professional tattooing experience\n• Current bloodborne pathogens certification\n• Strong portfolio demonstrating range of styles\n• Excellent drawing and design skills\n• Professional attitude and reliability\n\nCompensation:\n• 60/40 commission split (artist/shop)\n• Opportunity to sell flash designs and artwork\n• Booth rental option available for established artists\n• Health insurance contribution after 6 months\n• Paid convention attendance opportunities",
    "makeup-artist": "Position: Professional Makeup Artist\n\nResponsibilities:\n• Apply makeup for special events, bridal parties, and photoshoots\n• Perform makeup consultations and tutorials\n• Keep up with current makeup trends and techniques\n• Maintain a clean, organized makeup kit\n• Create detailed face charts when needed\n\nRequirements:\n• Professional makeup training or certification\n• Knowledge of different skin types and tones\n• Experience with photography makeup preferred\n• Well-maintained professional kit with quality products\n• Reliable transportation for on-location services\n\nCompensation:\n• $50-125 per makeup application + gratuity\n• Commission on product sales (15%)\n• Bridal party booking bonuses\n• Paid photoshoot opportunities\n• Flexible scheduling with focus on weekends",
    "booth-rental": "Opportunity: Premium Booth Rental\n\nSpace Details:\n• Modern styling station with hydraulic chair\n• Dedicated storage cabinet and product space\n• Access to shampoo area and color bar\n• Use of salon amenities (towels, coffee bar, wifi)\n• Prime location in busy shopping district\n\nRental Terms:\n• Weekly rate: $200-250 (based on experience)\n• Monthly option available at discounted rate\n• No long-term contract required (month-to-month)\n• Utilities and basic supplies included\n• Option to sell retail products with 85/15 split\n\nIdeal For:\n• Established stylists with existing clientele\n• Self-motivated beauty professionals\n• Cosmetologists seeking independence\n• Specialists in hair, nails, or lashes\n• Professionals with proper licensing and insurance",
    "other-beauty": "Position: Specialized Beauty Professional\n\nWe're seeking experts in:\n• Microblading/Permanent Makeup\n• Medical Aesthetics/Advanced Skincare\n• Body Contouring/Sculpting\n• Eyebrow Lamination/Henna\n• Other specialized beauty services\n\nResponsibilities:\n• Perform specialized treatments in your area of expertise\n• Maintain proper certification and continuing education\n• Follow all health and safety protocols\n• Build client relationships and maintain records\n• Contribute to salon's service diversity\n\nRequirements:\n• Current license/certification in specialty\n• Liability insurance\n• Portfolio of previous work\n• Excellent client communication skills\n• Willingness to cross-promote with other service providers\n\nCompensation:\n• Commission structure based on specialty (60-70%)\n• Product commission opportunities\n• Performance-based incentives\n• Flexible scheduling options\n• Marketing support for your specialty services"
  },
  
  // Vietnamese templates by style
  professionalVi: {
    "nail-technician": "Chúng tôi đang tìm kiếm thợ nail có tay nghề cao để gia nhập tiệm salon đã được khẳng định. Ứng viên lý tưởng sẽ có kinh nghiệm làm móng tay, móng chân, sơn gel, đắp bột và vẽ móng nghệ thuật. Phải duy trì không gian làm việc sạch sẽ và cung cấp dịch vụ khách hàng xuất sắc. Cơ cấu lương cạnh tranh với cơ hội phát triển. Vị trí toàn thời gian có sẵn ngay lập tức với lượng khách hàng trung thành.",
    "hair-stylist": "Tiệm salon cao cấp của chúng tôi đang tìm kiếm một thợ làm tóc có kinh nghiệm với chuyên môn về cắt, nhuộm, highlight và các kỹ thuật tạo kiểu. Ứng viên lý tưởng sẽ có thành tích về việc giữ chân khách hàng và kỹ năng chuyên môn. Phải cập nhật với xu hướng ngành và có thể tư vấn khách hàng về chăm sóc tóc và các lựa chọn tạo kiểu. Cơ cấu hoa hồng cạnh tranh với các phúc lợi sẵn có.",
    "spa-technician": "Chúng tôi đang tuyển dụng kỹ thuật viên spa có giấy phép với kinh nghiệm về facial, điều trị cơ thể và các quy trình chăm sóc da. Ứng viên lý tưởng sẽ có kiến thức về các dòng sản phẩm chăm sóc da và các phương pháp điều trị khác nhau, duy trì môi trường yên tĩnh cho khách hàng và cung cấp dịch vụ chăm sóc cá nhân hóa. Phải có khả năng giới thiệu các sản phẩm phù hợp và chế độ chăm sóc tại nhà. Mức lương cạnh tranh cộng với hoa hồng bán lẻ.",
    "salon-receptionist": "Tiệm salon bận rộn của chúng tôi đang tìm kiếm một lễ tân chuyên nghiệp để quản lý hoạt động tiếp tân. Trách nhiệm bao gồm lên lịch hẹn, xử lý thanh toán, chào đón khách hàng, trả lời điện thoại và duy trì khu vực lễ tân. Ứng viên lý tưởng sẽ có tổ chức, thành thạo máy tính và có kỹ năng dịch vụ khách hàng xuất sắc. Phải có khả năng làm nhiều việc cùng lúc trong môi trường nhịp độ nhanh. Vị trí toàn thời gian với mức lương theo giờ cạnh tranh.",
    "salon-manager": "Tiệm salon đã thành lập đang tìm kiếm một người quản lý có kinh nghiệm để giám sát hoạt động hàng ngày, giám sát nhân viên, quản lý hàng tồn kho và quan hệ khách hàng. Ứng viên lý tưởng sẽ có kinh nghiệm lãnh đạo salon trước đây, kỹ năng giao tiếp tốt và khả năng thúc đẩy tăng trưởng kinh doanh. Trách nhiệm bao gồm lên lịch, quản lý hiệu suất và đảm bảo tiêu chuẩn dịch vụ xuất sắc. Mức lương cạnh tranh cộng với cơ cấu thưởng dựa trên hiệu suất salon.",
    "massage-therapist": "Chúng tôi đang tìm kiếm một nhà trị liệu massage có giấy phép thành thạo trong nhiều phương pháp bao gồm Thụy Điển, deep tissue và các kỹ thuật trị liệu. Ứng viên lý tưởng sẽ có khả năng điều chỉnh các liệu trình dựa trên nhu cầu của khách hàng, duy trì ghi chú SOAP chi tiết và giữ vững tiêu chuẩn cao nhất về tính chuyên nghiệp. Phải có khả năng thực hiện nhiều buổi mỗi ngày trong khi duy trì chất lượng. Cơ cấu lương cạnh tranh với tiền tip và phúc lợi.",
    "lash-technician": "Tiệm salon của chúng tôi đang tìm kiếm một kỹ thuật viên mi được chứng nhận có kinh nghiệm về nối mi classic, volume và hybrid. Ứng viên lý tưởng sẽ có sự chú ý tuyệt vời đến chi tiết, bàn tay vững vàng và khả năng tạo ra kiểu dáng tùy chỉnh cho từng khách hàng. Phải duy trì không gian làm việc sạch sẽ và tuân thủ tất cả các quy trình an toàn. Vị trí toàn thời gian với cơ cấu lương cạnh tranh dựa trên kinh nghiệm và mức độ kỹ năng.",
    "tattoo-artist": "Studio xăm chuyên nghiệp đang tìm kiếm một nghệ sĩ có kinh nghiệm để tham gia vào đội ngũ của chúng tôi. Ứng viên lý tưởng sẽ có một portfolio mạnh thể hiện sự đa dạng về phong cách, kỹ năng vẽ xuất sắc và kiến thức về các quy trình khử trùng đúng cách. Phải có giấy phép và ít nhất 2 năm kinh nghiệm chuyên nghiệp. Lương dựa trên hoa hồng với cơ hội phát triển và xây dựng khách hàng trung thành.",
    "makeup-artist": "Chúng tôi đang tuyển dụng một chuyên gia trang điểm chuyên nghiệp với kinh nghiệm về trang điểm cô dâu, sự kiện đặc biệt và nhiếp ảnh. Ứng viên lý tưởng sẽ hiểu biết về các sản phẩm khác nhau, kỹ thuật cho nhiều loại da và xu hướng hiện tại. Phải có khả năng tạo ra những kiểu trang điểm từ tự nhiên đến ấn tượng dựa trên sở thích của khách hàng. Vị trí toàn thời gian với cơ cấu lương cạnh tranh và cơ hội đặt thêm sự kiện.",
    "booth-rental": "Cơ hội thuê bàn làm việc cao cấp dành cho các chuyên gia làm đẹp đã thành danh tại salon cao cấp của chúng tôi. Không gian bao gồm trạm tạo kiểu hiện đại, tủ lưu trữ và quyền truy cập vào tiện ích salon. Lý tưởng cho các chuyên gia có sẵn khách hàng đang tìm kiếm môi trường cao cấp. Các điều khoản thuê linh hoạt với giá hàng tuần/hàng tháng hợp lý. Tất cả các tiện ích được bao gồm với cơ hội hưởng hoa hồng bán lẻ.",
    "other-beauty": "Trung tâm chăm sóc sức khỏe của chúng tôi đang tìm kiếm các chuyên gia làm đẹp có giấy phép chuyên về thẩm mỹ nâng cao như phun xăm, trang điểm vĩnh viễn, các liệu pháp chăm sóc da cấp y tế hoặc định hình cơ thể. Ứng viên lý tưởng sẽ có chứng chỉ trong chuyên môn của họ, bảo hiểm trách nhiệm và portfolio công việc. Phải có khả năng tư vấn khách hàng về các thủ tục và duy trì hồ sơ đầy đủ. Cơ cấu lương cạnh tranh dựa trên kinh nghiệm và chuyên môn."
  },
  friendlyVi: {
    "nail-technician": "Hãy tham gia gia đình tiệm nail thân thiện, hỗ trợ của chúng tôi! Chúng tôi đang tìm một thợ nail thân thiện, yêu thích việc tạo ra những mẫu móng, pedicure và nail art đẹp. Nếu bạn thích làm cho khách hàng cảm thấy được chăm sóc và thích theo kịp các xu hướng nail mới nhất, chúng tôi rất muốn gặp bạn! Đội ngũ của chúng tôi coi trọng cân bằng công việc-cuộc sống, kỷ niệm sinh nhật và thực sự quan tâm đến sự thành công của nhau. Lương tốt, khách hàng đều đặn và bầu không khí tích cực đang chờ đón bạn!",
    "hair-stylist": "Hãy trở thành một phần của đội ngũ salon tóc sáng tạo của chúng tôi! Chúng tôi đang tìm kiếm một stylist đam mê, yêu thích việc biến đổi khách hàng với những kiểu cắt, màu sắc và kiểu tóc tuyệt vời. Salon của chúng tôi có bầu không khí vui vẻ, hợp tác nơi chúng tôi chia sẻ kỹ thuật và tôn vinh sự sáng tạo của nhau. Nếu bạn thích làm cho mọi người cảm thấy đẹp và tự tin khi làm việc với một đội ngũ hỗ trợ, đây là nơi dành cho bạn! Lịch trình linh hoạt với tiềm năng thu nhập tuyệt vời.",
    "spa-technician": "Tham gia đội ngũ spa yên bình của chúng tôi! Chúng tôi đang tìm kiếm một kỹ thuật viên spa chu đáo, yêu thích việc giúp khách hàng thư giãn và cảm thấy được phục hồi thông qua các dịch vụ facial, điều trị cơ thể và chăm sóc da. Spa của chúng tôi đề cao việc tạo ra môi trường hỗ trợ, yên tĩnh cho cả khách hàng và thành viên trong đội. Nếu bạn đam mê về sức khỏe và làm cho mọi người cảm thấy tốt nhất, chúng tôi rất muốn trò chuyện! Lương cạnh tranh cộng với môi trường làm việc yên tĩnh.",
    "salon-receptionist": "Hãy là gương mặt thân thiện của salon chúng tôi! Chúng tôi đang tìm kiếm một lễ tân ấm áp, thân thiện để chào đón khách hàng, sắp xếp lịch hẹn và giữ cho quầy lễ tân của chúng tôi hoạt động trơn tru. Nếu bạn thích kết nối với mọi người, có khả năng tổ chức và thích là một phần của đội ngũ vui vẻ, năng động, vai trò này là hoàn hảo cho bạn! Không cần kinh nghiệm về làm đẹp - chỉ cần mang theo thái độ tích cực và kỹ năng giao tiếp của bạn. Lương theo giờ tốt cộng với các đặc quyền của đội ngũ!",
    "salon-manager": "Lãnh đạo đội ngũ salon tuyệt vời của chúng tôi! Chúng tôi đang tìm kiếm một quản lý salon hỗ trợ, động viên, người có thể phát huy điều tốt nhất ở các stylist của chúng tôi đồng thời đảm bảo khách hàng có trải nghiệm tuyệt vời. Nếu bạn là người giao tiếp tốt với kinh nghiệm lãnh đạo và đam mê về ngành công nghiệp làm đẹp, chúng tôi muốn nói chuyện với bạn! Vai trò này cung cấp cân bằng công việc-cuộc sống, mức lương cạnh tranh và cơ hội giúp định hình thành công trong tương lai của salon chúng tôi.",
    "massage-therapist": "Tham gia đội ngũ chăm sóc sức khỏe của chúng tôi với tư cách là nhà trị liệu massage! Chúng tôi đang tìm kiếm người yêu thích việc giúp khách hàng cảm thấy tốt hơn thông qua sức mạnh chữa lành của cảm giác. Môi trường thoải mái của chúng tôi đề cao sự cân bằng công việc-cuộc sống, giáo dục liên tục và sự khỏe mạnh của nhà trị liệu. Nếu bạn đam mê về trị liệu massage và tạo ra những trải nghiệm cá nhân hóa cho khách hàng, chúng tôi rất muốn gặp bạn! Lịch trình linh hoạt, lương tốt và bầu không khí đội ngũ hỗ trợ.",
    "lash-technician": "Gọi tất cả các nghệ sĩ nối mi! Tham gia đội ngũ làm đẹp vui vẻ, hỗ trợ của chúng tôi và giúp khách hàng cảm thấy tuyệt đẹp với những bộ mi nối ấn tượng. Chúng tôi đề cao sự sáng tạo, chú ý đến chi tiết và tạo ra trải nghiệm tích cực cho tất cả những ai ngồi vào ghế của bạn. Salon của chúng tôi có không khí thân thiện nơi chúng tôi tôn vinh công việc và sự phát triển của nhau. Tiềm năng thu nhập tuyệt vời với các tùy chọn lịch trình linh hoạt!",
    "tattoo-artist": "Tham gia vào gia đình xăm sáng tạo của chúng tôi! Chúng tôi đang tìm kiếm một nghệ sĩ yêu thích việc tạo ra những hình xăm có ý nghĩa, đẹp đẽ trong studio thân thiện của chúng tôi. Shop của chúng tôi đề cao tự do nghệ thuật, hợp tác và làm cho khách hàng cảm thấy thoải mái trong suốt hành trình xăm của họ. Nếu bạn có phong cách độc đáo, thích kết nối với khách hàng và muốn làm việc trong môi trường không drama, hãy liên hệ! Lương dựa trên hoa hồng với nhiều khách vãng lai và cơ hội hẹn trước.",
    "makeup-artist": "Hãy trở thành một phần của đội ngũ glam của chúng tôi! Chúng tôi đang tìm kiếm một chuyên gia trang điểm yêu thích việc làm cho khách hàng cảm thấy đẹp cho những khoảnh khắc đặc biệt của họ. Cho dù đó là trang điểm cô dâu, sự kiện đặc biệt hay làm đẹp hàng ngày, nếu bạn thích biến đổi gương mặt và nâng cao sự tự tin, chúng tôi muốn bạn tham gia đội ngũ của chúng tôi! Studio thân thiện của chúng tôi đề cao sự sáng tạo, giáo dục liên tục và tôn vinh thành công nghệ thuật của nhau. Lịch trình linh hoạt với tiềm năng thu nhập tuyệt vời!",
    "booth-rental": "Đang tìm kiếm các chuyên gia làm đẹp tham gia vào gia đình salon của chúng tôi! Chúng tôi có những không gian bàn làm việc đẹp có sẵn trong salon thân thiện, hỗ trợ của chúng tôi. Tận hưởng sự tự do điều hành công việc kinh doanh của riêng bạn trong khi là một phần của cộng đồng tôn vinh sự thành công của nhau. Vị trí của chúng tôi có lượng khách qua lại lớn, chỗ đậu xe và bầu không khí thân thiện mà khách hàng yêu thích. Giá thuê hàng tuần/hàng tháng hợp lý không yêu cầu cam kết dài hạn!",
    "other-beauty": "Tham gia đội ngũ làm đẹp sáng tạo của chúng tôi! Chúng tôi đang tìm kiếm các chuyên gia đam mê chuyên về lông mày, trang điểm vĩnh viễn, chăm sóc da hoặc các dịch vụ làm đẹp khác. Studio thân thiện của chúng tôi đề cao sự sáng tạo, giáo dục liên tục và làm cho khách hàng cảm thấy tuyệt vời. Nếu bạn yêu thích việc bạn làm và muốn làm việc trong một môi trường hỗ trợ với tự do phát triển chuyên môn của bạn, hãy trò chuyện với chúng tôi! Lịch trình linh hoạt với cơ cấu hoa hồng cạnh tranh."
  },
  luxuryVi: {
    "nail-technician": "Tiệm nail sang trọng đang tìm một nghệ sĩ nail đẳng cấp để phục vụ khách hàng cao cấp. Ứng viên lý tưởng sẽ thực hiện các dịch vụ làm móng tay, móng chân và thiết kế móng nghệ thuật hoàn hảo với sự chú ý đến từng chi tiết. Phải có kinh nghiệm với các dòng sản phẩm cao cấp và cung cấp trải nghiệm cá nhân hóa ngoại hạng. Môi trường làm việc cao cấp của chúng tôi phục vụ khách hàng đẳng cấp mong đợi dịch vụ vượt trội. Gói đãi ngộ hấp dẫn bao gồm cơ cấu hoa hồng cao, tiền boa và hợp tác với các thương hiệu xa xỉ.",
    "hair-stylist": "Salon xa xỉ hàng đầu mời gọi một nhà tạo mẫu tóc bậc thầy tham gia đội ngũ độc quyền của chúng tôi. Phục vụ khách hàng tinh hoa, chúng tôi tìm kiếm một nghệ sĩ xuất sắc trong cắt tỉa chính xác, kỹ thuật màu couture và tạo kiểu biến đổi. Ứng viên lý tưởng sẽ có đào tạo từ các học viện danh tiếng và kinh nghiệm tại các salon cao cấp hoặc công việc biên tập. Yêu cầu tiêu chuẩn dịch vụ xuất sắc và trình bày không chê vào đâu được. Tiềm năng thu nhập đáng kể với hoa hồng dịch vụ và bán sản phẩm cao cấp.",
    "spa-technician": "Spa uy tín đang tìm kiếm một chuyên gia thẩm mỹ xuất sắc để cung cấp các liệu trình chăm sóc da biến đổi cho khách hàng độc quyền của chúng tôi. Ứng viên lý tưởng sẽ thông thạo các kỹ thuật nâng cao, dòng sản phẩm xa xỉ và phát triển quy trình cá nhân hóa. Phải cung cấp một trải nghiệm liền mạch, xa hoa từ tư vấn đến hoàn thành. Môi trường yên tĩnh của chúng tôi phục vụ các khách hàng tinh tế mong đợi kết quả phi thường. Đãi ngộ hậu hĩnh bao gồm giá dịch vụ cao, tiền boa và thưởng hiệu suất.",
    "salon-receptionist": "Điểm đến làm đẹp xa xỉ đang tìm kiếm một lễ tân quầy tiếp tân thanh lịch để nâng cao trải nghiệm khách hàng. Ứng viên lý tưởng sẽ sở hữu sự thanh thản, tế nhị và chú ý đến chi tiết ngoại hạng khi quản lý khách hàng VIP. Trách nhiệm bao gồm sắp đặt các cuộc hẹn liền mạch, dự đoán nhu cầu khách hàng và duy trì khu vực tiếp tân sang trọng. Kỹ năng trình bày và giao tiếp hoàn hảo là điều cần thiết. Mức lương cạnh tranh với phúc lợi xứng với tiêu chuẩn thương hiệu cao cấp của chúng tôi.",
    "salon-manager": "Tập đoàn salon danh tiếng đang tìm kiếm một nhà lãnh đạo thành đạt để giám sát hoạt động của địa điểm xa xỉ hàng đầu của chúng tôi. Ứng viên lý tưởng sẽ có kinh nghiệm quản lý các địa điểm làm đẹp hoặc khách sạn cao cấp, hiểu được những nét tinh tế của việc cung cấp dịch vụ cao cấp và sự xuất sắc của đội ngũ. Phải duy trì tiêu chuẩn khắt khe trong khi thúc đẩy tăng trưởng kinh doanh và nuôi dưỡng mối quan hệ với khách hàng độc quyền của chúng tôi. Gói đãi ngộ điều hành bao gồm lương, thưởng hiệu suất và phúc lợi cao cấp.",
    "massage-therapist": "Sanctuary chăm sóc sức khỏe đẳng cấp đang tìm kiếm một nhà trị liệu massage bậc thầy để cung cấp trải nghiệm siêu việt cho khách hàng xuất chúng của chúng tôi. Ứng viên lý tưởng sẽ sở hữu chứng chỉ nâng cao trong nhiều phương pháp, bao gồm deep tissue, đá nóng và kỹ thuật trị liệu. Phải tạo ra các liệu trình điều trị tùy chỉnh phù hợp với nhu cầu cá nhân với sự chú ý đặc biệt đến chi tiết. Khung cảnh yên tĩnh của chúng tôi đòi hỏi một nhà trị liệu cung cấp một hành trình xuất sắc từ khi chào đón đến khi chia tay. Cơ cấu lương cao với tiền boa đáng kể.",
    "lash-technician": "Atelier làm đẹp danh tiếng đang tìm kiếm một nghệ sĩ mi hàng đầu để tạo ra những kiểu mi đẹp, tùy chỉnh cho khách hàng độc quyền của chúng tôi. Ứng viên lý tưởng sẽ thể hiện sự thành thạo về kỹ thuật classic, volume và hybrid với độ chính xác hoàn hảo. Phải duy trì tiêu chuẩn cao nhất về an toàn và thanh lịch trong suốt trải nghiệm của khách hàng. Không gian xa xỉ của chúng tôi phục vụ những khách hàng tinh tế mong đợi kết quả ngoại hạng. Gói đãi ngộ cao cấp bao gồm mức giá dịch vụ cao và ưu đãi theo hiệu suất.",
    "tattoo-artist": "Studio xăm cao cấp riêng tư đang tìm một nghệ sĩ xuất sắc để phục vụ khách hàng độc quyền của chúng tôi. Ứng viên lý tưởng sẽ thể hiện kỹ thuật điêu luyện, phong cách nghệ thuật độc đáo và kinh nghiệm với khách hàng giàu có. Atelier chỉ nhận khách hẹn trước của chúng tôi cung cấp một môi trường kín đáo, sang trọng cho những người sưu tầm tinh tế tìm kiếm nghệ thuật cơ thể tùy chỉnh. Yêu cầu kỹ năng tư vấn và portfolio xuất sắc. Cơ cấu lương cao phản ánh tính độc quyền của khách hàng và dịch vụ của chúng tôi.",
    "makeup-artist": "Điểm đến làm đẹp xa xỉ đang tìm kiếm một chuyên gia trang điểm hàng đầu để tạo ra vẻ ngoài hoàn hảo, thanh lịch cho khách hàng xuất chúng của chúng tôi. Ứng viên lý tưởng sẽ có kinh nghiệm với khách hàng nổi tiếng, công việc biên tập hoặc hợp tác thương hiệu xa xỉ. Phải thể hiện sự đa dạng từ vẻ đẹp cổ điển đến xu hướng hiện tại trong khi cung cấp một trải nghiệm làm đẹp xa xỉ. Không gian cao cấp của chúng tôi đòi hỏi kiến thức sản phẩm hoàn hảo và dịch vụ cá nhân hóa. Tiềm năng thu nhập đáng kể với mức giá dịch vụ cao và tiền boa.",
    "booth-rental": "Cơ hội độc quyền để tham gia vào địa chỉ làm đẹp danh giá nhất. Suite riêng cao cấp có sẵn cho nghệ sĩ làm đẹp đã thành danh với khách hàng tinh hoa. Vị trí mang tính biểu tượng của chúng tôi cung cấp sự xa xỉ, an ninh và sự kín đáo vô song. Không gian có đồ đạc tùy chỉnh, tiện nghi cao cấp và dịch vụ concierge. Lý tưởng cho chuyên gia thành đạt tìm kiếm một môi trường phản ánh tiêu chuẩn xuất sắc của họ. Điều khoản linh hoạt cho nghệ sĩ phù hợp với khách hàng cao cấp đã được chứng minh.",
    "other-beauty": "Học viện làm đẹp danh tiếng đang tìm kiếm một chuyên gia trong các thủ thuật thẩm mỹ nâng cao cho khách hàng độc quyền của chúng tôi. Ứng viên lý tưởng sẽ có kỹ năng điêu luyện trong chuyên môn của họ, cho dù là phun xăm, trang điểm vĩnh viễn hay các liệu trình da chuyên biệt. Phải cung cấp một trải nghiệm ngoại hạng với sự chú ý tỉ mỉ đến chi tiết và chăm sóc cá nhân hóa. Không gian xa xỉ, kín đáo của chúng tôi phục vụ những khách hàng tinh tế mong đợi kết quả vượt trội. Đãi ngộ cao phản ánh tính độc quyền của nghệ thuật và dịch vụ của bạn."
  },
  casualVi: {
    "nail-technician": "Tiệm nail đông khách đang tìm thợ nail để bắt đầu ngay! Giỏi làm móng tay, móng chân thường xuyên và sơn gel. Thái độ thân thiện và có mặt đáng tin cậy là điều bắt buộc. Khách hàng ổn định và tip tốt cho người phù hợp. Cần có sẵn vào cuối tuần. Hãy tham gia đội ngũ của chúng tôi!",
    "hair-stylist": "Tiệm làm tóc địa phương cần một stylist có thể xử lý cắt, màu và kiểu tóc cơ bản. Phải đáng tin cậy và tốt với khách hàng. Có sẵn thuê ghế hoặc hoa hồng. Mang theo dụng cụ riêng, nhưng thuốc màu được cung cấp. Lịch trình linh hoạt với ca làm việc cuối tuần. Khách vãng lai và khách quen đang chờ bạn!",
    "spa-technician": "Spa khu phố đang tìm kiếm một kỹ thuật viên biết về facial và điều trị cơ thể. Không cần nhiều năm kinh nghiệm - sẵn sàng đào tạo người có thái độ đúng đắn. Có sẵn bán thời gian hoặc toàn thời gian. Môi trường thoải mái với lịch hẹn ổn định và tip tốt. Yêu cầu một số giờ cuối tuần.",
    "salon-receptionist": "Cần một người thân thiện ở quầy lễ tân cho salon bận rộn của chúng tôi! Trả lời điện thoại, đặt lịch hẹn và check-in/out khách hàng. Cần kỹ năng máy tính cơ bản. Không yêu cầu kinh nghiệm làm đẹp - chỉ cần đáng tin cậy và giỏi giao tiếp. Bán thời gian để bắt đầu với khả năng toàn thời gian. Có sẵn vào cuối tuần là một lợi thế!",
    "salon-manager": "Tiệm salon địa phương đang tìm người để giúp điều hành hoạt động hàng ngày. Cần có tổ chức, giỏi giao tiếp và có khả năng xử lý lịch trình, vật tư và kế toán cơ bản. Kinh nghiệm salon trước đây hữu ích nhưng không bắt buộc đối với người phù hợp. Vị trí toàn thời gian với mức lương theo giờ cạnh tranh cộng thưởng.",
    "massage-therapist": "Spa bình dân cần một nhà trị liệu massage NGAY! Phải có giấy phép và biết những kiến thức cơ bản - Thụy Điển, deep tissue, thư giãn. Mang theo ga giường riêng, chúng tôi cung cấp bàn và vật tư. Môi trường thân thiện, thoải mái với lịch đặt ổn định. Chọn giờ làm việc của riêng bạn với một số yêu cầu có sẵn vào cuối tuần. Tip tốt!",
    "lash-technician": "Điểm làm đẹp bận rộn cần một kỹ thuật viên mi! Ưu tiên kinh nghiệm classic và volume. Bán thời gian để bắt đầu, có thể trở thành toàn thời gian. Mang theo vật tư riêng, chúng tôi cung cấp không gian. Không khí thoải mái với khách hàng quen đã hỏi về dịch vụ mi. Lập lịch trình riêng với một số có sẵn vào cuối tuần.",
    "tattoo-artist": "Tiệm địa phương đang tìm một nghệ sĩ xăm để tham gia vào đội của chúng tôi. Phải thoải mái với khách vãng lai và công việc tùy chỉnh. Có sẵn mẫu flash hoặc mang phong cách riêng của bạn. Công việc sạch sẽ và thái độ tốt quan trọng hơn nhiều năm kinh nghiệm. Chia hoa hồng công bằng với cơ hội xây dựng danh sách khách hàng của bạn nhanh chóng.",
    "makeup-artist": "Cần một chuyên gia trang điểm cho salon của chúng tôi! Sự kiện đặc biệt, trang điểm cơ bản và kiểu dáng hàng ngày. Hoàn hảo cho người đang xây dựng portfolio. Giờ bán thời gian có sẵn với lịch hẹn thêm cho đám cưới và sự kiện. Một số mỹ phẩm được cung cấp, mang theo sản phẩm yêu thích của bạn. Có sẵn cuối tuần quan trọng.",
    "booth-rental": "Có sẵn một bàn làm việc cho thuê! Vị trí tuyệt vời với nhiều khách qua lại. Mang theo khách hàng riêng hoặc xây dựng từ khách vãng lai của chúng tôi. Tất cả tiện ích được bao gồm, chỉ trả phí thuê bàn hàng tuần. Không có hợp đồng dài hạn - thuê đơn giản theo tuần. Hoàn hảo cho stylists, thợ cắt tóc nam, thợ tết tóc hoặc thợ nail có một số kinh nghiệm.",
    "other-beauty": "Địa điểm làm đẹp địa phương có chỗ cho người làm lông mày, trang điểm vĩnh viễn hoặc các dịch vụ làm đẹp khác. Có sẵn không gian bán thời gian - thuê theo ngày hoặc giờ cụ thể mỗi tuần. Mang theo vật tư và khách hàng riêng, hoặc xây dựng từ cơ sở khách hàng của chúng tôi. Bầu không khí thoải mái với các tùy chọn lịch trình linh hoạt."
  },
  detailedVi: {
    "nail-technician": "Vị trí: Thợ Nail\n\nTrách nhiệm:\n• Thực hiện làm móng tay, móng chân, sơn gel\n• Đắp và duy trì móng acrylic và móng nối\n• Tạo nail art và thiết kế tùy chỉnh\n• Duy trì tiêu chuẩn vệ sinh nghiêm ngặt\n• Xây dựng mối quan hệ khách hàng và giữ chân khách hàng\n\nYêu cầu:\n• Giấy phép thợ nail hợp lệ\n• Tối thiểu 1 năm kinh nghiệm ưu tiên\n• Kiến thức về quy trình vệ sinh đúng cách\n• Kỹ năng dịch vụ khách hàng xuất sắc\n• Yêu cầu có sẵn vào cuối tuần\n\nLương thưởng:\n• Hoa hồng cạnh tranh (lên đến 60%)\n• Tip thẻ tín dụng được trả hàng ngày\n• Tiền thưởng hoa hồng sản phẩm\n• Đảm bảo lương tối thiểu trong thời gian vắng khách\n• Bảo hiểm y tế sau thời gian thử việc",
    "hair-stylist": "Vị trí: Thợ Làm Tóc\n\nTrách nhiệm:\n• Thực hiện cắt tóc chính xác cho nhiều đối tượng khách hàng\n• Thực hiện dịch vụ màu bao gồm highlight, balayage và màu hiệu chỉnh\n• Tạo kiểu tóc dịp đặc biệt và cô dâu\n• Tư vấn khách hàng về chăm sóc tóc và các lựa chọn tạo kiểu\n• Giới thiệu các sản phẩm bán lẻ phù hợp\n\nYêu cầu:\n• Giấy phép thẩm mỹ hợp lệ\n• Tối thiểu 2 năm kinh nghiệm salon ưu tiên\n• Chứng chỉ về màu khuyến khích\n• Kỹ năng dịch vụ khách hàng xuất sắc\n• Phải cung cấp dụng cụ cắt riêng\n\nLương thưởng:\n• Cơ cấu hoa hồng cạnh tranh (45-60%)\n• Hoa hồng bán lẻ (10-15%)\n• Phúc lợi sức khỏe cho stylist toàn thời gian\n• Cơ hội giáo dục liên tục có trả lương\n• Chương trình 401k có sẵn sau 1 năm",
    "spa-technician": "Vị trí: Kỹ Thuật Viên Spa/Chuyên Viên Thẩm Mỹ\n\nTrách nhiệm:\n• Thực hiện các liệu trình facial và phân tích da\n• Thực hiện các liệu trình cơ thể và dịch vụ tẩy tế bào chết\n• Cung cấp dịch vụ waxing và tẩy lông\n• Duy trì phòng điều trị đến tiêu chuẩn sạch sẽ cao nhất\n• Giáo dục khách hàng về các chế độ chăm sóc tại nhà\n\nYêu cầu:\n• Giấy phép thẩm mỹ hợp lệ\n• Kiến thức về các dòng sản phẩm chăm sóc da và thành phần\n• Ưu tiên kinh nghiệm với các công nghệ facial khác nhau\n• Kỹ năng dịch vụ khách hàng xuất sắc\n• Khả năng làm việc buổi tối và cuối tuần\n\nLương thưởng:\n• Cơ cấu lương cơ bản + hoa hồng\n• Tiền thưởng bổ sung liệu trình\n• Hoa hồng bán lẻ (15%)\n• Hạn ngạch liệu trình hàng tháng với tiền thưởng\n• Dịch vụ và sản phẩm miễn phí/giảm giá",
    "salon-receptionist": "Vị trí: Lễ Tân Salon\n\nTrách nhiệm:\n• Quản lý hệ thống lịch hẹn\n• Xử lý thanh toán của khách hàng và xử lý ngăn tiền mặt\n• Trả lời hệ thống điện thoại nhiều đường dây\n• Chào đón khách hàng và mời đồ uống giải khát\n• Duy trì sự sạch sẽ của khu vực lễ tân\n• Hỗ trợ quản lý hàng tồn kho\n\nYêu cầu:\n• Bằng tốt nghiệp trung học hoặc tương đương\n• Kinh nghiệm dịch vụ khách hàng trước đây\n• Thành thạo với hệ thống đặt chỗ máy tính\n• Kỹ năng giao tiếp xuất sắc\n• Khả năng xử lý nhiều việc cùng lúc trong môi trường nhịp độ nhanh\n\nLương thưởng:\n• Mức lương giờ cạnh tranh ($15-18/giờ)\n• Cơ hội hoa hồng bán lẻ\n• Chương trình chia sẻ tiền tip\n• Giảm giá nhân viên cho dịch vụ và sản phẩm\n• Nghỉ phép có lương sau thời gian thử việc",
    "salon-manager": "Vị trí: Quản Lý Salon\n\nTrách nhiệm:\n• Giám sát hoạt động hàng ngày và lịch nhân viên\n• Quản lý hàng tồn kho và đặt hàng vật tư\n• Đào tạo và phát triển nhà cung cấp dịch vụ\n• Xử lý các vấn đề của khách hàng và duy trì tiêu chuẩn dịch vụ\n• Giám sát các số liệu hiệu suất salon\n• Thực hiện các sáng kiến tiếp thị\n\nYêu cầu:\n• Tối thiểu 3 năm kinh nghiệm ngành salon\n• Ưu tiên kinh nghiệm quản lý trước đây\n• Kỹ năng lãnh đạo và giao tiếp mạnh mẽ\n• Thành thạo máy tính bao gồm hệ thống POS\n• Giấy phép thẩm mỹ là một lợi thế nhưng không bắt buộc\n\nLương thưởng:\n• Lương cơ bản ($50,000-65,000/năm)\n• Tiền thưởng hiệu suất hàng quý\n• Bảo hiểm sức khỏe và phúc lợi hưu trí\n• Nghỉ phép và nghỉ ốm có lương\n• Phụ cấp giáo dục liên tục",
    "massage-therapist": "Vị trí: Nhà Trị Liệu Massage Có Giấy Phép\n\nTrách nhiệm:\n• Thực hiện các phương pháp massage khác nhau (Thụy Điển, Deep Tissue, Đá Nóng)\n• Tùy chỉnh liệu trình dựa trên nhu cầu của khách hàng\n• Duy trì hồ sơ khách hàng chính xác\n• Tuân thủ tiêu chuẩn che phủ và tiêu chuẩn chuyên môn phù hợp\n• Duy trì sự sạch sẽ của phòng điều trị\n\nYêu cầu:\n• Giấy phép trị liệu massage hiện tại\n• Tối thiểu 500 giờ đào tạo được chứng nhận\n• Bảo hiểm trách nhiệm\n• Sức chịu đựng thể chất cho nhiều buổi\n• Có sẵn cho ca làm việc cuối tuần\n\nLương thưởng:\n• $25-40 mỗi giờ dịch vụ + tiền tip\n• Hoa hồng bán sản phẩm\n• Massage miễn phí hàng tháng\n• Phụ cấp giáo dục liên tục\n• Đóng góp chăm sóc sức khỏe sau 90 ngày",
    "lash-technician": "Vị trí: Kỹ Thuật Viên Nối Mi\n\nTrách nhiệm:\n• Nối mi classic, hybrid và volume\n• Thực hiện uốn và nhuộm mi\n• Tiến hành tư vấn khách hàng kỹ lưỡng\n• Duy trì hồ sơ ứng dụng chính xác\n• Vệ sinh và khử trùng dụng cụ và không gian làm việc\n\nYêu cầu:\n• Chứng chỉ nối mi\n• Ưu tiên giấy phép thẩm mỹ hoặc chuyên viên thẩm mỹ\n• Phối hợp tay-mắt xuất sắc\n• Chú ý đến chi tiết và kiên nhẫn\n• Portfolio công việc trước đây\n\nLương thưởng:\n• Lương dựa trên hoa hồng (50-70%)\n• Hoa hồng bán lẻ cho các sản phẩm chăm sóc mi\n• Tiền thưởng đặt lịch cho lịch đã lấp đầy\n• Cơ hội đào tạo nâng cao có trả lương\n• Lịch trình linh hoạt có sẵn",
    "tattoo-artist": "Vị trí: Nghệ Sĩ Xăm\n\nTrách nhiệm:\n• Tạo thiết kế xăm tùy chỉnh dựa trên yêu cầu của khách hàng\n• Áp dụng hình xăm sử dụng kỹ thuật và thiết bị phù hợp\n• Duy trì nghiêm ngặt quy trình khử trùng và an toàn\n• Cung cấp hướng dẫn chăm sóc sau khi xăm cho khách hàng\n• Đóng góp vào môi trường nghệ thuật của tiệm\n\nYêu cầu:\n• Tối thiểu 2 năm kinh nghiệm xăm chuyên nghiệp\n• Chứng nhận mầm bệnh trong máu hiện tại\n• Portfolio mạnh thể hiện phạm vi phong cách\n• Kỹ năng vẽ và thiết kế xuất sắc\n• Thái độ chuyên nghiệp và đáng tin cậy\n\nLương thưởng:\n• Hoa hồng chia 60/40 (nghệ sĩ/tiệm)\n• Cơ hội bán thiết kế flash và tác phẩm nghệ thuật\n• Tùy chọn thuê booth có sẵn cho các nghệ sĩ đã thành lập\n• Đóng góp bảo hiểm sức khỏe sau 6 tháng\n• Cơ hội tham dự hội nghị có trả tiền",
    "makeup-artist": "Vị trí: Chuyên Gia Trang Điểm Chuyên Nghiệp\n\nTrách nhiệm:\n• Trang điểm cho sự kiện đặc biệt, tiệc cưới và chụp ảnh\n• Thực hiện tư vấn trang điểm và hướng dẫn\n• Cập nhật với xu hướng và kỹ thuật trang điểm hiện tại\n• Duy trì bộ dụng cụ trang điểm sạch sẽ, có tổ chức\n• Tạo biểu đồ khuôn mặt chi tiết khi cần thiết\n\nYêu cầu:\n• Đào tạo hoặc chứng chỉ trang điểm chuyên nghiệp\n• Kiến thức về các loại da và tông màu khác nhau\n• Ưu tiên kinh nghiệm với trang điểm nhiếp ảnh\n• Bộ dụng cụ chuyên nghiệp được bảo quản tốt với sản phẩm chất lượng\n• Phương tiện đi lại đáng tin cậy cho các dịch vụ tại chỗ\n\nLương thưởng:\n• $50-125 mỗi lần trang điểm + tiền tip\n• Hoa hồng bán sản phẩm (15%)\n• Tiền thưởng đặt tiệc cưới\n• Cơ hội chụp ảnh có trả tiền\n• Lịch trình linh hoạt với trọng tâm vào cuối tuần",
    "booth-rental": "Cơ hội: Thuê Bàn Làm Việc Cao Cấp\n\nChi Tiết Không Gian:\n• Trạm tạo kiểu hiện đại với ghế thủy lực\n• Tủ lưu trữ chuyên dụng và không gian sản phẩm\n• Tiếp cận khu vực gội đầu và quầy màu\n• Sử dụng tiện nghi salon (khăn, quầy cà phê, wifi)\n• Vị trí đắc địa trong khu mua sắm sầm uất\n\nĐiều Khoản Thuê:\n• Giá thuê hàng tuần: $200-250 (dựa trên kinh nghiệm)\n• Tùy chọn hàng tháng có sẵn với giá giảm\n• Không yêu cầu hợp đồng dài hạn (theo tháng)\n• Tiện ích và vật tư cơ bản được bao gồm\n• Tùy chọn bán sản phẩm bán lẻ với tỷ lệ chia 85/15\n\nLý Tưởng Cho:\n• Stylists đã thành lập với khách hàng hiện có\n• Chuyên gia làm đẹp tự thúc đẩy\n• Chuyên viên thẩm mỹ tìm kiếm sự độc lập\n• Chuyên gia về tóc, móng hoặc mi\n• Các chuyên gia có giấy phép và bảo hiểm phù hợp",
    "other-beauty": "Vị trí: Chuyên Gia Làm Đẹp Chuyên Biệt\n\nChúng tôi đang tìm kiếm chuyên gia trong:\n• Phun xăm/Trang điểm vĩnh viễn\n• Thẩm mỹ y tế/Chăm sóc da nâng cao\n• Định hình cơ thể/Tạo dáng\n• Uốn lông mày/Henna\n• Các dịch vụ làm đẹp chuyên biệt khác\n\nTrách nhiệm:\n• Thực hiện các liệu trình chuyên biệt trong lĩnh vực chuyên môn của bạn\n• Duy trì chứng nhận và giáo dục liên tục phù hợp\n• Tuân theo tất cả các quy trình sức khỏe và an toàn\n• Xây dựng mối quan hệ khách hàng và duy trì hồ sơ\n• Đóng góp vào sự đa dạng dịch vụ của salon\n\nYêu cầu:\n• Giấy phép/chứng chỉ hiện tại trong chuyên môn\n• Bảo hiểm trách nhiệm\n• Portfolio công việc trước đây\n• Kỹ năng giao tiếp khách hàng xuất sắc\n• Sẵn sàng quảng bá chéo với các nhà cung cấp dịch vụ khác\n\nLương thưởng:\n• Cơ cấu hoa hồng dựa trên chuyên môn (60-70%)\n• Cơ hội hoa hồng sản phẩm\n• Ưu đãi dựa trên hiệu suất\n• Các tùy chọn lịch trình linh hoạt\n• Hỗ trợ tiếp thị cho dịch vụ chuyên môn của bạn"
  }
};
