
import { JobFormValues, IndustryType } from './jobFormSchema';

// Define template card display data
export const templateCards = [
  {
    id: "nails",
    emoji: "💅",
    title: "Nail Salon",
    subtitle: "For nail salon positions",
    slogan: "Perfect for nail artists & technicians",
    industry: "nails" as IndustryType,
    background: "bg-gradient-to-br from-pink-50 to-rose-50",
  },
  {
    id: "hair",
    emoji: "✂️",
    title: "Hair Salon",
    subtitle: "For hair stylist positions",
    slogan: "Ideal for stylists & colorists",
    industry: "hair" as IndustryType,
    background: "bg-gradient-to-br from-blue-50 to-cyan-50",
  },
  {
    id: "lashes",
    emoji: "👁️",
    title: "Lash Artist",
    subtitle: "For lash extension specialists",
    slogan: "Perfect for lash & brow experts",
    industry: "lashes" as IndustryType,
    background: "bg-gradient-to-br from-violet-50 to-purple-50",
  },
  {
    id: "massage",
    emoji: "🧘",
    title: "Massage Therapist",
    subtitle: "For massage & spa positions",
    slogan: "For wellness & therapy professionals",
    industry: "massage" as IndustryType,
    background: "bg-gradient-to-br from-green-50 to-emerald-50",
  },
  {
    id: "tattoo",
    emoji: "🖋️",
    title: "Tattoo Artist",
    subtitle: "For tattoo shop positions",
    slogan: "For talented tattoo professionals",
    industry: "tattoo" as IndustryType,
    background: "bg-gradient-to-br from-gray-50 to-slate-50",
  },
  {
    id: "brows",
    emoji: "✨",
    title: "Brow Artist",
    subtitle: "For eyebrow specialists",
    slogan: "Perfect for microblading & brow experts",
    industry: "brows" as IndustryType,
    background: "bg-gradient-to-br from-amber-50 to-yellow-50",
  },
  {
    id: "skincare",
    emoji: "✨",
    title: "Esthetician",
    subtitle: "For skincare specialists",
    slogan: "For facials & skincare experts",
    industry: "skincare" as IndustryType,
    background: "bg-gradient-to-br from-indigo-50 to-blue-50",
  },
  {
    id: "barber",
    emoji: "💈",
    title: "Barber",
    subtitle: "For barbershop positions",
    slogan: "Perfect for skilled barbers",
    industry: "barber" as IndustryType,
    background: "bg-gradient-to-br from-red-50 to-orange-50",
  },
  {
    id: "makeup",
    emoji: "💄",
    title: "Makeup Artist",
    subtitle: "For makeup specialists",
    slogan: "For beauty & makeup professionals",
    industry: "makeup" as IndustryType,
    background: "bg-gradient-to-br from-fuchsia-50 to-pink-50",
  },
];

// Job Templates with full form data
export const jobTemplates: Record<string, JobFormValues> = {
  nails: {
    title: "Nail Technician Needed - Full-Time Position",
    description: "We are looking for experienced nail technicians to join our team. Our salon provides a friendly, clean environment with a loyal client base. You'll have the opportunity to showcase your creativity and technical skills in a supportive atmosphere.\n\nWe value attention to detail, customer service, and professionalism.",
    vietnameseDescription: "Tiệm Nail cần thợ có kinh nghiệm, bao lương hoặc ăn chia tùy khả năng. Tiệm đông khách, sạch sẽ, không khí làm việc vui vẻ, lương cao, có chỗ ở cho thợ ở xa và có tip hậu.",
    location: "San Jose, CA",
    compensation_details: "$800-1200/week depending on experience",
    salary_range: "$800-1200/week",
    jobType: "full-time",
    experience_level: "experienced",
    contactEmail: "salon@example.com",
    requirements: ["Valid nail license", "Minimum 1 year experience", "Acrylic and gel experience", "Good English communication"],
    specialties: ["Acrylic", "Gel", "Dipping Powder", "Manicure", "Pedicure"],
  },
  
  hair: {
    title: "Hair Stylist Position - Join Our Growing Team",
    description: "We are seeking talented hair stylists to join our premium salon. This role offers a creative environment where you can grow your skills and clientele. You'll provide exceptional service while building lasting relationships with clients.\n\nWe offer competitive compensation and ongoing education opportunities.",
    vietnameseDescription: "",
    location: "Los Angeles, CA",
    compensation_details: "Commission-based + hourly guarantee",
    salary_range: "$50,000-70,000/year",
    jobType: "full-time",
    experience_level: "experienced",
    contactEmail: "careers@example.com",
    requirements: ["Cosmetology license", "2+ years salon experience", "Portfolio of work", "Customer service skills"],
    specialties: ["Cutting", "Coloring", "Styling", "Extensions", "Treatments"],
  },
  
  lashes: {
    title: "Lash Extension Artist - Luxury Spa Environment",
    description: "Join our team of lash artists in our upscale beauty studio. We're looking for detail-oriented professionals with excellent technique and client care. You'll work in a relaxing environment focused on delivering premium lash services.\n\nBuild your career with a growing brand that values quality and artistry.",
    vietnameseDescription: "",
    location: "Orange County, CA",
    compensation_details: "Commission + tips, average $30-40/hour",
    salary_range: "$45,000-60,000/year",
    jobType: "part-time",
    experience_level: "intermediate",
    contactEmail: "beauty@example.com",
    requirements: ["Lash certification", "1+ years experience", "Portfolio of work", "Professional appearance"],
    specialties: ["Classic Lashes", "Volume Lashes", "Hybrid Sets", "Lash Lifts"],
  },
  
  massage: {
    title: "Licensed Massage Therapist - Flexible Hours",
    description: "We are looking for licensed massage therapists to join our wellness center. You'll provide therapeutic massage services in a peaceful, client-focused environment. This position allows you to use your expertise while helping clients achieve relaxation and pain relief.\n\nWe offer flexible scheduling and a supportive team atmosphere.",
    vietnameseDescription: "",
    location: "San Francisco, CA",
    compensation_details: "$40-60/hour + tips",
    salary_range: "$50,000-70,000/year",
    jobType: "part-time",
    experience_level: "experienced",
    contactEmail: "wellness@example.com",
    requirements: ["Massage therapy license", "2+ years experience", "Knowledge of multiple modalities", "Excellent communication skills"],
    specialties: ["Deep Tissue", "Swedish", "Hot Stone", "Sports Massage", "Prenatal"],
  },
  
  tattoo: {
    title: "Tattoo Artist Position - Established Studio",
    description: "Our busy tattoo studio is seeking talented artists to join our team. You'll work in a creative, professional environment with a steady client base. This position is perfect for artists looking to expand their portfolio and build a loyal clientele.\n\nWe provide a clean, modern workspace and industry-standard equipment.",
    vietnameseDescription: "",
    location: "Portland, OR",
    compensation_details: "Commission-based (50-70% of bookings)",
    salary_range: "$40,000-80,000/year",
    jobType: "contract",
    experience_level: "experienced",
    contactEmail: "art@example.com",
    requirements: ["Professional tattoo experience", "Strong portfolio", "Bloodborne pathogen certification", "Customer service skills"],
    specialties: ["Traditional", "Japanese", "Realism", "Black and Grey", "Color Work"],
  },
  
  brows: {
    title: "Brow Artist / Microblading Specialist",
    description: "We're seeking a talented brow artist to join our beauty studio. You'll specialize in shaping, tinting, lamination, and microblading services. This role requires precision, artistry, and excellent client communication to help clients achieve their perfect brow look.\n\nJoin our passionate team in a luxurious, client-focused environment.",
    vietnameseDescription: "",
    location: "Seattle, WA",
    compensation_details: "$25-35/hour plus commission on products",
    salary_range: "$40,000-55,000/year",
    jobType: "part-time",
    experience_level: "intermediate",
    contactEmail: "brows@example.com",
    requirements: ["Microblading certification", "1+ years experience", "Portfolio of before/after photos", "Esthetician license preferred"],
    specialties: ["Microblading", "Brow Lamination", "Tinting", "Shaping", "Threading"],
  },
  
  skincare: {
    title: "Licensed Esthetician - Medical Spa",
    description: "Our upscale medical spa is looking for a licensed esthetician to perform facial treatments and skincare services. You'll work with high-end products and technology in a clinical yet luxurious environment. This position involves customizing treatments for clients and providing expert skincare advice.\n\nJoin our team of professionals dedicated to exceptional client results.",
    vietnameseDescription: "",
    location: "Miami, FL",
    compensation_details: "$18-25/hour plus commission and tips",
    salary_range: "$35,000-50,000/year",
    jobType: "full-time",
    experience_level: "experienced",
    contactEmail: "medspa@example.com",
    requirements: ["Esthetics license", "2+ years experience", "Knowledge of medical-grade skincare", "Sales ability"],
    specialties: ["Chemical Peels", "Microdermabrasion", "Facials", "LED Therapy", "Microneedling"],
  },
  
  barber: {
    title: "Barber Wanted - Modern Barbershop",
    description: "Join our team of skilled barbers in a modern, high-end barbershop. We're looking for professionals who excel at precision cutting, fades, and beard grooming. You'll provide exceptional service in a stylish, client-focused environment with a loyal customer base.\n\nThis position offers competitive compensation and room to grow your clientele.",
    vietnameseDescription: "",
    location: "Austin, TX",
    compensation_details: "Commission-based (60-70%) + tips",
    salary_range: "$45,000-65,000/year",
    jobType: "full-time",
    experience_level: "experienced",
    contactEmail: "barbershop@example.com",
    requirements: ["Barber license", "2+ years experience", "Skilled in modern cutting techniques", "Professional appearance"],
    specialties: ["Fades", "Razor Cuts", "Beard Grooming", "Hot Towel Shaves", "Line-ups"],
  },
  
  makeup: {
    title: "Makeup Artist - Luxury Beauty Boutique",
    description: "We are seeking a talented makeup artist to join our luxury beauty boutique. You'll provide personalized makeup services, consultations, and product recommendations in an upscale retail environment. This position combines artistry with sales expertise to create unforgettable client experiences.\n\nIdeal for makeup professionals who excel at both application and education.",
    vietnameseDescription: "",
    location: "New York, NY",
    compensation_details: "$22-30/hour plus commission and tips",
    salary_range: "$40,000-60,000/year",
    jobType: "full-time",
    experience_level: "intermediate",
    contactEmail: "beautycareer@example.com",
    requirements: ["Makeup artistry certification", "2+ years experience", "Knowledge of premium cosmetic brands", "Portfolio of work"],
    specialties: ["Bridal", "Editorial", "Natural Glam", "Special Occasion", "Mature Skin"],
  },
};
