
import { IndustryType, JobFormValues } from './jobFormSchema';

// Job templates for different industries
interface JobTemplate extends JobFormValues {
  id: string;
  popularity: 'most-hired' | 'fastest-applicants' | 'trusted' | 'trending';
  summary: string;
  salary_range: string;
}

// Group templates by industry
export const jobTemplatesByIndustry: Record<IndustryType, JobTemplate[]> = {
  nail: [
    {
      id: 'nail-1',
      title: 'Nail Tech Needed - High Tip Area',
      industry: 'nail',
      job_type: 'full_time',
      location: 'New York, NY',
      description: 'We are a busy nail salon in an affluent area looking for experienced nail technicians. Our clients tip well and we have a steady flow of appointments. We offer competitive pay and a friendly work environment. Experience with manicures, pedicures, and nail art required.',
      requirements: 'Valid license, 1+ years experience, acrylic skills, English speaking, reliable transportation',
      salary_min: 18,
      salary_max: 25,
      tips_range: 'Very High ($150-300/day)',
      compensation_type: 'hourly',
      compensation_details: 'Hourly rate plus tips, product commission available',
      benefits: 'Flexible scheduling, paid vacation after 1 year, health insurance contribution',
      schedule: 'Tuesday-Saturday, 9am-7pm, can be flexible',
      vietnamese_description: 'Cần thợ nail có kinh nghiệm làm việc ở khu khách sang, tip cao. Tiệm đông khách, thân thiện, lương cao. Cần biết làm bột, chân tay nước, và nail art.',
      popularity: 'most-hired',
      summary: 'Busy salon in affluent area with excellent tips and steady clientele. Great for experienced techs looking for stability and high earnings.',
      salary_range: '$18-25/hr + $150-300 daily tips',
      contact_name: 'Sarah',
      contact_phone: '555-123-4567',
      contact_email: 'manager@examplenailsalon.com'
    },
    {
      id: 'nail-2',
      title: 'Tuyển Thợ Nail Bao Lương - Tip Cao',
      industry: 'nail',
      job_type: 'full_time',
      location: 'Houston, TX',
      description: 'Tiệm ở khu Mỹ trắng, giàu sang, tip cao. Cần thợ nail có kinh nghiệm, làm full-time hoặc part-time. Bao lương $5,500-7,000/tháng tùy theo kinh nghiệm. Chỗ làm vui vẻ, không khí gia đình.',
      requirements: 'Cần có bằng nail, ít nhất 2 năm kinh nghiệm, biết làm đủ loại nail và waxing là một lợi thế',
      salary_min: 5500,
      salary_max: 7000,
      tips_range: 'Rất Cao ($200-350/ngày)',
      compensation_type: 'salary',
      compensation_details: 'Bao lương theo tháng + tips, có hỗ trợ chỗ ở nếu cần',
      benefits: 'Bao ăn trưa, có chỗ ở nếu cần, đón từ phi trường',
      schedule: 'Thứ Ba - Chủ Nhật, 10am-8pm, có thể linh động',
      vietnamese_description: 'Tiệm ở khu Mỹ trắng, giàu sang, tip cao. Cần thợ nail có kinh nghiệm, làm full-time hoặc part-time. Bao lương $5,500-7,000/tháng tùy theo kinh nghiệm. Chỗ làm vui vẻ, không khí gia đình.',
      popularity: 'fastest-applicants',
      summary: 'Salon in upscale area offering guaranteed salary ($5.5-7K/month) with high tips. Housing assistance available if needed.',
      salary_range: '$5,500-7,000/month + tips',
      contact_name: 'Hương',
      contact_phone: '555-987-6543',
      contact_email: 'huong@luxurynailspa.com'
    },
    {
      id: 'nail-3',
      title: 'Hiring Full-Time Nail Artist - $20-30/hr + High Tips',
      industry: 'nail',
      job_type: 'full_time',
      location: 'Los Angeles, CA',
      description: 'Upscale nail boutique in Beverly Hills seeking talented nail artists to join our team. We specialize in gel extensions, nail art, and luxury treatments. Our clientele includes celebrities and influencers who tip generously. Weekly pay with growth opportunities.',
      requirements: 'Valid CA nail license, 3+ years experience, advanced nail art skills, professional demeanor, Instagram portfolio preferred',
      salary_min: 20,
      salary_max: 30,
      tips_range: 'Premium ($200-400/day)',
      compensation_type: 'hourly',
      compensation_details: 'Competitive hourly rate, product commission, performance bonuses',
      benefits: 'Weekly pay, health insurance option, paid training, career advancement',
      schedule: 'Flexible shifts available, some weekend work required',
      vietnamese_description: 'Tiệm sang trọng ở Beverly Hills cần thợ nail có kỹ năng cao về nail art và gel extension. Khách hàng bao gồm người nổi tiếng và influencer, tip rất tốt. Trả lương theo tuần và có cơ hội thăng tiến.',
      popularity: 'trending',
      summary: 'High-end salon in Beverly Hills with celebrity clientele. Great for ambitious nail artists with advanced skills seeking premium income.',
      salary_range: '$20-30/hr + $200-400 daily tips',
      contact_name: 'Michael',
      contact_phone: '555-555-1234',
      contact_email: 'careers@glamournails.com'
    },
    {
      id: 'nail-4',
      title: 'Part-Time Nail Technician - Weekends Only',
      industry: 'nail',
      job_type: 'part_time',
      location: 'Chicago, IL',
      description: 'Looking for weekend nail technicians to help with our busy weekend rush. Perfect for those with weekday commitments or students. Friendly environment with regular clients and good tips.',
      requirements: 'Valid license, basic manicure/pedicure skills, reliability, customer service focus',
      salary_min: 15,
      salary_max: 22,
      tips_range: 'Good ($100-150/day)',
      compensation_type: 'hourly',
      compensation_details: 'Hourly pay plus tips, bonus for bringing new clients',
      benefits: 'Flexible weekend scheduling, free salon services',
      schedule: 'Saturday and Sunday, 9am-6pm',
      vietnamese_description: 'Tiệm cần thợ nail làm cuối tuần để phục vụ khách vào những ngày bận rộn. Phù hợp với người có việc làm trong tuần hoặc sinh viên. Môi trường làm việc thân thiện, khách quen tip tốt.',
      popularity: 'trusted',
      summary: 'Weekend-only position perfect for students or those with weekday commitments. Steady clientele and supportive environment.',
      salary_range: '$15-22/hr + tips',
      contact_name: 'Lisa',
      contact_phone: '555-888-9999',
      contact_email: 'weekend@nailstudio.com'
    }
  ],
  hair: [
    {
      id: 'hair-1',
      title: 'Experienced Hair Stylist - Commission Based',
      industry: 'hair',
      job_type: 'full_time',
      location: 'Miami, FL',
      description: 'High-end hair salon in South Beach seeking experienced stylists. Strong clientele preferred but not required. We offer premium products, modern facilities, and ongoing education. Great earning potential with our commission structure.',
      requirements: 'Valid cosmetology license, 3+ years experience, cutting and color expertise, portfolio of work',
      salary_min: 50000,
      salary_max: 90000,
      tips_range: 'Excellent',
      compensation_type: 'commission',
      compensation_details: '50-60% commission based on experience and performance',
      benefits: 'Education allowance, product discounts, flexible scheduling',
      schedule: 'Tuesday-Saturday with flexible hours',
      vietnamese_description: '',
      popularity: 'most-hired',
      summary: 'Upscale salon offering high commission structure (50-60%) with education benefits. Ideal for stylists with established clientele.',
      salary_range: '$50K-90K/year potential',
      contact_name: 'Gabriela',
      contact_phone: '555-765-4321',
      contact_email: 'careers@southbeachhair.com'
    },
    {
      id: 'hair-2',
      title: 'Barber/Stylist Needed - Guaranteed Base + Commission',
      industry: 'hair',
      job_type: 'full_time',
      location: 'Atlanta, GA',
      description: 'Modern barbershop with diverse clientele seeking skilled barbers and stylists. We offer a guaranteed base pay plus commission, ensuring you earn even during slower periods. Busy location with walk-in traffic and appointment bookings.',
      requirements: 'Licensed barber/cosmetologist, fade techniques, texturing expertise, beard grooming skills',
      salary_min: 35000,
      salary_max: 70000,
      tips_range: 'Very Good ($100-200/day)',
      compensation_type: 'hybrid',
      compensation_details: 'Base salary + 40% commission on services',
      benefits: 'Guaranteed income, paid vacation, continuing education',
      schedule: 'Flexible shifts, must work at least one weekend day',
      vietnamese_description: '',
      popularity: 'fastest-applicants',
      summary: 'Modern barbershop offering guaranteed base pay plus commission (40%). Security plus upside in a busy location.',
      salary_range: '$35K-70K/year',
      contact_name: 'Marcus',
      contact_phone: '555-222-3333',
      contact_email: 'join@moderncuts.com'
    }
  ],
  lash: [
    {
      id: 'lash-1',
      title: 'Certified Lash Technician - Full Time',
      industry: 'lash',
      job_type: 'full_time',
      location: 'Denver, CO',
      description: 'Boutique lash studio seeking certified lash technician. We specialize in classic and volume lash extensions. Join our talented team in a serene, upscale environment with loyal clientele.',
      requirements: 'Lash certification, portfolio of work, 1+ year experience with volume lashes, excellent attention to detail',
      salary_min: 45000,
      salary_max: 65000,
      tips_range: 'Good',
      compensation_type: 'hybrid',
      compensation_details: 'Base pay + commission structure, retail bonuses',
      benefits: 'Product discounts, flexible scheduling, continuing education',
      schedule: 'Tuesday-Saturday, appointment-based hours',
      vietnamese_description: '',
      popularity: 'trusted',
      summary: 'Upscale lash studio with loyal clients offering hybrid compensation model. Perfect for certified lash artists seeking stable income.',
      salary_range: '$45K-65K/year',
      contact_name: 'Jenna',
      contact_phone: '555-444-9876',
      contact_email: 'jobs@flutterstudio.com'
    }
  ],
  massage: [
    {
      id: 'massage-1',
      title: 'Licensed Massage Therapist - Flexible Hours',
      industry: 'massage',
      job_type: 'full_time',
      location: 'Seattle, WA',
      description: 'Well-established spa seeking licensed massage therapists. We offer a peaceful work environment, quality products, and a steady flow of clients. Specialties in Swedish, deep tissue, and hot stone massage preferred.',
      requirements: 'Valid massage license, 2+ years experience, professional demeanor, ability to perform various modalities',
      salary_min: 50000,
      salary_max: 80000,
      tips_range: 'Very Good',
      compensation_type: 'commission',
      compensation_details: '50% commission on services, retail bonuses',
      benefits: 'Flexible scheduling, continuing education, self-care stipend',
      schedule: 'Create your own schedule, minimum 24 hours per week',
      vietnamese_description: '',
      popularity: 'trending',
      summary: 'Established spa offering flexible scheduling and 50% commission. Excellent for experienced therapists seeking work-life balance.',
      salary_range: '$50K-80K/year',
      contact_name: 'Taylor',
      contact_phone: '555-333-2222',
      contact_email: 'careers@serenityspacompany.com'
    }
  ],
  beauty: [
    {
      id: 'beauty-1',
      title: 'Makeup Artist / Beauty Advisor - Full Time',
      industry: 'beauty',
      job_type: 'full_time',
      location: 'Las Vegas, NV',
      description: 'Luxury beauty boutique seeking experienced makeup artist/beauty advisor. Work with high-end products and a diverse clientele including tourists and locals. Special event and wedding makeup services are a major part of our business.',
      requirements: 'Makeup artistry certification, retail experience, knowledge of premium beauty brands, portfolio of work',
      salary_min: 40000,
      salary_max: 60000,
      tips_range: 'Excellent',
      compensation_type: 'hybrid',
      compensation_details: 'Base salary + commission on services and product sales',
      benefits: 'Product allowance, paid training, employee discounts',
      schedule: 'Wednesday-Sunday, including some evenings',
      vietnamese_description: '',
      popularity: 'most-hired',
      summary: 'Luxury beauty boutique catering to tourists and locals. Great for ambitious makeup artists seeking retail and service experience.',
      salary_range: '$40K-60K/year + commission',
      contact_name: 'Alex',
      contact_phone: '555-777-8888',
      contact_email: 'talent@glamoursuite.com'
    }
  ]
};
