export type Salon = {
  id: string;
  name: string;
  asking_price?: string;
  zalo?: string;
  owner_name?: string;
  email?: string;
  phone?: string;
  image?: string;
  city?: string;
  state?: string;
  features?: string[];
  rating?: number;
  website?: string;
  hours?: string;
  services?: string[];
  paymentMethods?: string[];
  isHiring?: boolean;
  description?: string;
  logo?: string;
  neighborhood?: string;
  reviewCount?: number;
  specialty?: string;
  beforeAfterGallery?: string[];
  isPremium?: boolean;
  featured?: boolean;
  // Keep existing fields for backward compatibility
  zip_code?: string;
  facebook?: string;
  amenities?: string[];
  price?: string | number;
  location?: string;
  imageUrl?: string;
  shortBio?: string;
  category?: string;
  contact_info?: {
    owner_name?: string;
    phone?: string;
    email?: string;
    zalo?: string;
  };
  user_id?: string;
  created_at?: string;
  updated_at?: string;
  status?: string;
  expiration_date?: string;
  bio?: string;
  established?: string;
  bookingLink?: string;
  square_feet?: number;
  monthly_rent?: number;
  socialMedia?: {
    instagram?: string;
    facebook?: string;
    tiktok?: string;
  };
  is_vietnamese_listing?: boolean;
};
