-- Community Seeding Script
-- Create diverse, authentic community posts with comments
-- Backdated over 7-10 days for organic feel

-- Personal Stories (English & Vietnamese)
INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Just finished my first full set of gel extensions on myself! 💅 Started nail art 6 months ago as a stress reliever during college, now I''m thinking about making this my career. The feeling when you create something beautiful with your hands is unmatched ✨ #NailArtJourney #SelfTaught #DreamsBigger', 'story', 'nails', ARRAY['nail-art', 'gel-extensions', 'self-taught'], ARRAY['https://images.unsplash.com/photo-1649972904349-6e44c42644a7'], 24, 3, false, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Hôm nay mình thử technique mới để làm lông mi cong tự nhiên mà không cần mascara! 😍 Dùng heated eyelash curler + setting spray trước khi curl. Hiệu quả bất ngờ luôn các bạn ơi! Lông mi cong suốt 8 tiếng mà vẫn mềm mại. Ai muốn thử thì nhắn mình nhé 💕 #BeautyTipsVN #LashHacks', 'story', 'lashes', ARRAY['lash-tips', 'vietnamese-beauty'], ARRAY[], 31, 3, false, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Had the worst hair disaster last week - tried to bleach my hair at home and it turned ORANGE 🙈 Rushed to my colorist friend who spent 4 hours fixing it. Now I have the most gorgeous ashy blonde! Lesson learned: some things are worth paying professionals for. But also grateful for amazing friends who save the day 💛 #HairDisaster #FriendshipGoals #ProfessionalColorist', 'story', 'hair', ARRAY['hair-color', 'salon-life', 'friendship'], ARRAY[], 45, 2, false, NOW() - INTERVAL '5 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Mình vừa mở salon nhỏ tại quận 7! 🎉 Từ việc học nail art ở nhà đến có studio riêng, hành trình 2 năm đầy thử thách nhưng xứng đáng! Cảm ơn tất cả khách hàng đã tin tưởng và ủng hộ từ những ngày đầu. Special opening promotion: 30% off cho tất cả dịch vụ tuần đầu! #NewSalon #VietNailArt #SalonLife #District7', 'story', 'business', ARRAY['new-salon', 'vietnamese-business', 'grand-opening'], ARRAY['https://images.unsplash.com/photo-1581091226825-a6a2a5aee158'], 67, 4, true, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Client transformation today has me emotional 🥺💕 She came in feeling insecure about her eyebrows after over-plucking in the 2000s (we''ve all been there!). 2 hours later with microblading and she was literally crying happy tears. This is why I love what I do - it''s not just about beauty, it''s about confidence and helping people feel like the best version of themselves ✨ #MicrobladingMagic #ClientLove #ConfidenceBoost', 'story', 'brows', ARRAY['microblading', 'client-transformation', 'confidence'], ARRAY[], 89, 3, false, NOW() - INTERVAL '4 days');