-- Fixed Community Posts with Valid Categories
-- Test batch with correct categories

INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES

-- US/UK Beauty Trends
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '🌹 Rose-water nails are having a MOMENT! Just did my first DIY set and I''m obsessed. Mixed actual rose water into my clear coat for this dreamy translucent finish. Pro tip: let each layer dry completely or you''ll get bubbles! Who else is trying this trend? 💅✨ - Jess from LA 🇺🇸 #RoseWaterNails #NailTrends #DIYBeauty', 'showcase', 'nails', ARRAY['rose-water-nails', 'nail-trends', 'diy'], ARRAY['https://images.unsplash.com/photo-1604654894610-df63bc536371'], 142, 18, true, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Cluster lashes vs individual lashes - which team are you on? 👀 I''ve been using clusters for 3 months now and honestly, they''re SO much easier than individuals but still give that custom look. Takes me 10 mins vs 45! Anyone else make the switch? Drop your fave cluster brands below! 💕 - Emma, Manchester 🇬🇧 #ClusterLashes #LashExtensions #BeautyDebate', 'question', 'lashes', ARRAY['cluster-lashes', 'lash-extensions', 'beauty-debate'], ARRAY['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b'], 89, 24, false, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Under-eye brightening hack that actually WORKS! 👀✨ Mix your concealer with a tiny drop of liquid highlighter before applying. Instant awake look even after 3 hours of sleep. Thank me later! What''s your go-to tired eye trick? - Madison, Austin 🇺🇸 #UnderEyeBrightening #MakeupHacks #TiredEyes', 'tip', 'makeup', ARRAY['under-eye-brightening', 'makeup-hacks', 'concealer-tips'], ARRAY['https://images.unsplash.com/photo-1515377905703-c4788e51af15'], 234, 45, true, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Clean girl satin skin tutorial! ✨ Skip the matte, embrace the glow. My routine: hydrating primer + tinted moisturizer + cream blush + clear gloss. That''s it! Natural but elevated. Who''s with me on this movement? - Taylor, Portland 🇺🇸 #CleanGirl #SatinSkin #NaturalMakeup', 'tip', 'general', ARRAY['clean-girl', 'satin-skin', 'natural-makeup'], ARRAY['https://images.unsplash.com/photo-1487412947147-5cebf100ffc2'], 187, 33, false, NOW() - INTERVAL '4 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'LED neck masks are the new face masks! 💡 Using mine 3x a week and my tech neck lines are disappearing. 20 minutes while watching Netflix = anti-aging multitasking. Has anyone else joined the LED revolution? - Olivia, Birmingham 🇬🇧 #LEDTherapy #NeckMask #AntiAging', 'story', 'general', ARRAY['led-therapy', 'neck-mask', 'anti-aging'], ARRAY['https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec'], 145, 22, false, NOW() - INTERVAL '5 days'),

-- Korean Beauty Trends
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '유리알 피부 2.0 도전 중! 🇰🇷 Glass skin but make it EXTRA dewy. 7-step routine with double essence and sleeping mask every night. 한 달째 하고 있는데 진짜 효과 있어요! Anyone else obsessed with the glass skin evolution? - Min-ji, Seoul 🇰🇷 #GlassSkin2Point0 #KBeauty #DewyComplexion', 'tip', 'general', ARRAY['glass-skin', 'k-beauty', 'dewy-skin'], ARRAY['https://images.unsplash.com/photo-1596755389378-c31d21fd1273'], 267, 38, true, NOW() - INTERVAL '6 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'PDRN 세럼이 진짜 대박이에요! 💉 Salmon DNA in skincare sounds weird but the results are INSANE. My acne scars are fading so fast! Has anyone else tried PDRN serums? Drop your experiences! - Soo-jin, Busan 🇰🇷 #PDRNSerum #KBeauty #SkinHealing', 'story', 'general', ARRAY['pdrn-serum', 'k-beauty', 'acne-scars'], ARRAY['https://images.unsplash.com/photo-1556228578-8c89e6adf883'], 189, 29, false, NOW() - INTERVAL '7 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Hydrogel mask addiction is real! 💧 Using them 4x a week and my skin has never been more hydrated. The cooling effect is perfect for this heat wave. What''s your favorite hydrogel mask brand? - Eun-bi, Seoul 🇰🇷 #HydrogelMask #KBeauty #Hydration', 'question', 'general', ARRAY['hydrogel-mask', 'k-beauty', 'hydration'], ARRAY['https://images.unsplash.com/photo-1570554886111-e80fcac6c8f4'], 134, 28, false, NOW() - INTERVAL '8 days'),

-- Japanese Beauty Trends
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'CANMAKEのパーソナルカラーパレット最高！🇯🇵 Found my perfect color match and my makeup game changed completely. The quality for the price is unbeatable! Anyone else obsessed with CANMAKE? - Yuki, Tokyo 🇯🇵 #CANMAKE #PersonalColor #JBeauty', 'showcase', 'makeup', ARRAY['canmake', 'personal-color', 'j-beauty'], ARRAY['https://images.unsplash.com/photo-1512207736890-6ffed8c0af4b'], 145, 23, false, NOW() - INTERVAL '9 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Jirai Kei makeup tutorial coming tomorrow! 💔🎀 The dark romantic aesthetic is so beautiful but definitely not for beginners. Practice makes perfect! Who wants to see my step-by-step process? - Mika, Harajuku 🇯🇵 #JiraiKei #JapaneseStreetStyle #DarkRomantic', 'tip', 'makeup', ARRAY['jirai-kei', 'japanese-street-style', 'dark-romantic'], ARRAY['https://images.unsplash.com/photo-1594736797933-d0a9ba012d5d'], 289, 67, true, NOW() - INTERVAL '10 days'),

-- Global Tech Beauty Trends  
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'TikTok #morningshed routine is my new religion! 🌅 Oil cleanse + vitamin C + SPF in under 5 minutes. Efficiency meets results. Who else is part of the morning shed movement? Share your routine! - Alex, Toronto 🇨🇦 #MorningShed #SkincareRoutine #TikTokTrends', 'tip', 'general', ARRAY['morning-shed', 'skincare-routine', 'tiktok-trends'], ARRAY['https://images.unsplash.com/photo-1559181567-c3190ca9959b'], 201, 44, false, NOW() - INTERVAL '11 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'AI beauty apps are scary accurate! 📱 Tried 3 different ones and they all recommended the same foundation shade. Technology is wild! Anyone else using AI for beauty recommendations? - Jordan, Vancouver 🇨🇦 #AIBeauty #BeautyTech #FoundationMatch', 'story', 'general', ARRAY['ai-beauty', 'beauty-tech', 'foundation-match'], ARRAY['https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c'], 189, 28, false, NOW() - INTERVAL '12 days');