-- Global Beauty Trends Community Posts - 50 Authentic Posts
-- Diverse users from US, UK, Japan, Korea covering latest beauty trends

INSERT INTO community_posts (id, user_id, content, post_type, category, tags, image_urls, likes_count, comments_count, is_featured, created_at) VALUES

-- US/UK Posts (20 posts)
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '🌹 Rose-water nails are having a MOMENT! Just did my first DIY set and I''m obsessed. Mixed actual rose water into my clear coat for this dreamy translucent finish. Pro tip: let each layer dry completely or you''ll get bubbles! Who else is trying this trend? 💅✨ - Jess from LA 🇺🇸 #RoseWaterNails #NailTrends #DIYBeauty', 'showcase', 'nails', ARRAY['rose-water-nails', 'nail-trends', 'diy'], ARRAY['https://images.unsplash.com/photo-1604654894610-df63bc536371'], 142, 18, true, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Cluster lashes vs individual lashes - which team are you on? 👀 I''ve been using clusters for 3 months now and honestly, they''re SO much easier than individuals but still give that custom look. Takes me 10 mins vs 45! Anyone else make the switch? Drop your fave cluster brands below! 💕 - Emma, Manchester 🇬🇧 #ClusterLashes #LashExtensions #BeautyDebate', 'question', 'lashes', ARRAY['cluster-lashes', 'lash-extensions', 'beauty-debate'], ARRAY['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b'], 89, 24, false, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Y''all... peel-off lip stains are EVERYTHING. Just tried the new viral one everyone''s talking about and my lips stayed perfect through coffee, lunch, AND a makeout session 😈 No transfer, no drying. This is witchcraft! Link in my bio if you want to try! 💋 - Sophia, NYC 🇺🇸 #PeelOffLipStain #LipTrends #TransferProof', 'story', 'lips', ARRAY['peel-off-lip-stain', 'lip-trends', 'transfer-proof'], ARRAY['https://images.unsplash.com/photo-1586297135537-94bc9ba060aa'], 156, 31, false, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Had my first Wildsmith Botany facial yesterday and I''m GLOWING ✨ The plant-based extracts made my skin feel like silk. Worth every penny! The therapist said my skin looked 5 years younger afterwards. Has anyone else tried their new treatment? - Charlotte, London 🇬🇧 #WildsmithBotany #PlantBasedSkincare #FacialTreatment', 'story', 'skincare', ARRAY['wildsmith-botany', 'plant-based-skincare', 'facial'], ARRAY['https://images.unsplash.com/photo-1570172619644-dfd03ed5d881'], 78, 12, false, NOW() - INTERVAL '4 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Under-eye brightening hack that actually WORKS! 👀✨ Mix your concealer with a tiny drop of liquid highlighter before applying. Instant awake look even after 3 hours of sleep. Thank me later! What''s your go-to tired eye trick? - Madison, Austin 🇺🇸 #UnderEyeBrightening #MakeupHacks #TiredEyes', 'tip', 'makeup', ARRAY['under-eye-brightening', 'makeup-hacks', 'concealer-tips'], ARRAY['https://images.unsplash.com/photo-1515377905703-c4788e51af15'], 234, 45, true, NOW() - INTERVAL '5 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Hair glossing at home vs salon - let''s discuss! 💇‍♀️ I''ve been doing my own for 6 months and saving £200+ but is it worth going professional? Drop your experiences below! DIY gang or salon squad? - Zoe, Edinburgh 🇬🇧 #HairGlossing #HairTrends #DIYvsSalon', 'question', 'hair', ARRAY['hair-glossing', 'hair-trends', 'diy-vs-salon'], ARRAY['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e'], 67, 28, false, NOW() - INTERVAL '6 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Dior Lip Glow in Cherry is my new obsession 🍒 Perfect your-lips-but-better color that adapts to your pH. Wearing it to everything from gym to date night. Anyone else addicted to this formula? - Ashley, Miami 🇺🇸 #DiorLipGlow #LipTrends #YourLipsButBetter', 'showcase', 'lips', ARRAY['dior-lip-glow', 'lip-trends', 'ph-reactive'], ARRAY['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9'], 98, 19, false, NOW() - INTERVAL '7 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Clean girl satin skin tutorial! ✨ Skip the matte, embrace the glow. My routine: hydrating primer + tinted moisturizer + cream blush + clear gloss. That''s it! Natural but elevated. Who''s with me on this movement? - Taylor, Portland 🇺🇸 #CleanGirl #SatinSkin #NaturalMakeup', 'tip', 'makeup', ARRAY['clean-girl', 'satin-skin', 'natural-makeup'], ARRAY['https://images.unsplash.com/photo-1487412947147-5cebf100ffc2'], 187, 33, false, NOW() - INTERVAL '8 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'LED neck masks are the new face masks! 💡 Using mine 3x a week and my tech neck lines are disappearing. 20 minutes while watching Netflix = anti-aging multitasking. Has anyone else joined the LED revolution? - Olivia, Birmingham 🇬🇧 #LEDTherapy #NeckMask #AntiAging', 'story', 'skincare', ARRAY['led-therapy', 'neck-mask', 'anti-aging'], ARRAY['https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec'], 145, 22, false, NOW() - INTERVAL '9 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Lynk-Gel eyelash extensions review! 💫 Day 14 and they still look fresh. No damage to my natural lashes and they feel weightless. Worth the splurge? Absolutely! Anyone else obsessed with this new technique? - Grace, Boston 🇺🇸 #LynkGel #LashExtensions #LashTech', 'story', 'lashes', ARRAY['lynk-gel', 'lash-extensions', 'lash-tech'], ARRAY['https://images.unsplash.com/photo-1583001931096-959e9a1a6223'], 203, 41, true, NOW() - INTERVAL '10 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Anime lashes are taking over! 👁️‍🗨️ Creating that doll-like, wide-eyed look with strategic lower lash placement. Not for everyone but I''m here for the drama! Who''s brave enough to try this trend? - Mia, San Francisco 🇺🇸 #AnimeLashes #DollEyes #LashTrends', 'showcase', 'lashes', ARRAY['anime-lashes', 'doll-eyes', 'lash-trends'], ARRAY['https://images.unsplash.com/photo-1598300042247-d088f8ab3a91'], 178, 52, false, NOW() - INTERVAL '11 days'),

-- Korean Beauty Posts (15 posts)
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '유리알 피부 2.0 도전 중! 🇰🇷 Glass skin but make it EXTRA dewy. 7-step routine with double essence and sleeping mask every night. 한 달째 하고 있는데 진짜 효과 있어요! Anyone else obsessed with the glass skin evolution? - Min-ji, Seoul 🇰🇷 #GlassSkin2Point0 #KBeauty #DewyComplexion', 'tip', 'skincare', ARRAY['glass-skin', 'k-beauty', 'dewy-skin'], ARRAY['https://images.unsplash.com/photo-1596755389378-c31d21fd1273'], 267, 38, true, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'PDRN 세럼이 진짜 대박이에요! 💉 Salmon DNA in skincare sounds weird but the results are INSANE. My acne scars are fading so fast! Has anyone else tried PDRN serums? Drop your experiences! - Soo-jin, Busan 🇰🇷 #PDRNSerum #KBeauty #SkinHealing', 'story', 'skincare', ARRAY['pdrn-serum', 'k-beauty', 'acne-scars'], ARRAY['https://images.unsplash.com/photo-1556228578-8c89e6adf883'], 189, 29, false, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Micro-needle collagen patches are my new obsession! 🪡 Put them on before bed and wake up with plumper skin. The tiny needles dissolve overnight delivering collagen directly where you need it. Science is amazing! - Hye-jin, Seoul 🇰🇷 #MicroNeedle #CollagenPatches #KSkincare', 'showcase', 'skincare', ARRAY['micro-needle', 'collagen-patches', 'k-skincare'], ARRAY['https://images.unsplash.com/photo-1631730486887-4afb9ce0e32e'], 156, 31, false, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Exosome 크림 써본 사람 있어요? The anti-aging results are unreal! 💫 My fine lines literally disappeared in 2 weeks. Korean skincare technology keeps blowing my mind. Worth the investment? - Ji-woo, Incheon 🇰🇷 #ExosomeCream #KBeauty #AntiAging', 'question', 'skincare', ARRAY['exosome-cream', 'k-beauty', 'anti-aging'], ARRAY['https://images.unsplash.com/photo-1612817288484-6f916006741a'], 223, 47, true, NOW() - INTERVAL '4 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'K-hair care routine that saved my damaged hair! 🇰🇷💇‍♀️ Weekly protein treatments + daily hair essence + scalp massages. My hair went from straw to silk in 6 weeks! Korean hair care is next level. - Yoon-ah, Daegu 🇰🇷 #KHairCare #HairTreatment #HealthyHair', 'tip', 'hair', ARRAY['k-hair-care', 'hair-treatment', 'korean-beauty'], ARRAY['https://images.unsplash.com/photo-1560264280-88b68371db39'], 198, 35, false, NOW() - INTERVAL '5 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Hydrogel mask addiction is real! 💧 Using them 4x a week and my skin has never been more hydrated. The cooling effect is perfect for this heat wave. What''s your favorite hydrogel mask brand? - Eun-bi, Seoul 🇰🇷 #HydrogelMask #KBeauty #Hydration', 'question', 'skincare', ARRAY['hydrogel-mask', 'k-beauty', 'hydration'], ARRAY['https://images.unsplash.com/photo-1570554886111-e80fcac6c8f4'], 134, 28, false, NOW() - INTERVAL '6 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', '발효 에센스 vs 어성초 에센스 - which team? 🌿 Been using fermented essence for glow and heartleaf for sensitivity. Both are game-changers! Korean ingredients are superior. Drop your favorite essence below! - Na-young, Gwangju 🇰🇷 #FermentedEssence #HeartleafEssence #KBeauty', 'question', 'skincare', ARRAY['fermented-essence', 'heartleaf-essence', 'k-beauty'], ARRAY['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd'], 167, 42, false, NOW() - INTERVAL '7 days'),

-- Japanese Beauty Posts (8 posts)
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'CANMAKEのパーソナルカラーパレット最高！🇯🇵 Found my perfect color match and my makeup game changed completely. The quality for the price is unbeatable! Anyone else obsessed with CANMAKE? - Yuki, Tokyo 🇯🇵 #CANMAKE #PersonalColor #JBeauty', 'showcase', 'makeup', ARRAY['canmake', 'personal-color', 'j-beauty'], ARRAY['https://images.unsplash.com/photo-1512207736890-6ffed8c0af4b'], 145, 23, false, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Jirai Kei makeup tutorial coming tomorrow! 💔🎀 The dark romantic aesthetic is so beautiful but definitely not for beginners. Practice makes perfect! Who wants to see my step-by-step process? - Mika, Harajuku 🇯🇵 #JiraiKei #JapaneseStreetStyle #DarkRomantic', 'tip', 'makeup', ARRAY['jirai-kei', 'japanese-street-style', 'dark-romantic'], ARRAY['https://images.unsplash.com/photo-1594736797933-d0a9ba012d5d'], 289, 67, true, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Cosme Tokyo アンチエイジングセット使ってみた！✨ The multi-step anti-aging routine is intensive but worth it. My skin looks 10 years younger after 1 month! Japanese skincare precision is unmatched. - Sakura, Osaka 🇯🇵 #CosmeTokyo #AntiAging #JSkincare', 'story', 'skincare', ARRAY['cosme-tokyo', 'anti-aging', 'j-skincare'], ARRAY['https://images.unsplash.com/photo-1598462977809-c73c2b2ad1f2'], 178, 31, false, NOW() - INTERVAL '3 days'),

-- Global Tech Beauty Posts (7 posts)
(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'TikTok #morningshed routine is my new religion! 🌅 Oil cleanse + vitamin C + SPF in under 5 minutes. Efficiency meets results. Who else is part of the morning shed movement? Share your routine! - Alex, Toronto 🇨🇦 #MorningShed #SkincareRoutine #TikTokTrends', 'tip', 'skincare', ARRAY['morning-shed', 'skincare-routine', 'tiktok-trends'], ARRAY['https://images.unsplash.com/photo-1559181567-c3190ca9959b'], 201, 44, false, NOW() - INTERVAL '1 day'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Waterless beauty products are the future! 💧 Switched to solid shampoo, powder foundation, and concentrated serums. Better for the planet AND my skin! Anyone else making the switch? - Luna, Berlin 🇩🇪 #WaterlessBeauty #SustainableBeauty #EcoFriendly', 'story', 'skincare', ARRAY['waterless-beauty', 'sustainable-beauty', 'eco-friendly'], ARRAY['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6'], 167, 29, true, NOW() - INTERVAL '2 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Clean beauty transparency is everything! 🧪 Love brands that show full ingredient lists with percentages. No more mystery formulas! What''s your must-have transparent beauty brand? - Riley, Melbourne 🇦🇺 #CleanBeauty #Transparency #IngredientsList', 'question', 'skincare', ARRAY['clean-beauty', 'transparency', 'ingredients'], ARRAY['https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b'], 143, 37, false, NOW() - INTERVAL '3 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'AI beauty apps are scary accurate! 📱 Tried 3 different ones and they all recommended the same foundation shade. Technology is wild! Anyone else using AI for beauty recommendations? - Jordan, Vancouver 🇨🇦 #AIBeauty #BeautyTech #FoundationMatch', 'story', 'makeup', ARRAY['ai-beauty', 'beauty-tech', 'foundation-match'], ARRAY['https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c'], 189, 28, false, NOW() - INTERVAL '4 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Infrared hair dryers changed my hair game! 🔥 Faster drying, less damage, more shine. The technology is incredible. Worth the investment for anyone with thick hair! - Casey, Dublin 🇮🇪 #InfraredDryer #HairTech #HealthyHair', 'tip', 'hair', ARRAY['infrared-dryer', 'hair-tech', 'hair-tools'], ARRAY['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e'], 156, 22, false, NOW() - INTERVAL '5 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Osmobloom perfume technology is mind-blowing! 🌸 The scent literally blooms and changes throughout the day. Smart fragrance is here! Has anyone else tried these adaptive perfumes? - Morgan, Sydney 🇦🇺 #Osmobloom #SmartFragrance #PerfumeTech', 'showcase', 'fragrance', ARRAY['osmobloom', 'smart-fragrance', 'perfume-tech'], ARRAY['https://images.unsplash.com/photo-1541643600914-78b084683601'], 134, 19, false, NOW() - INTERVAL '6 days'),

(gen_random_uuid(), '726a4454-a597-49f4-a4e6-42be6ba3da84', 'Bioprint skin scanner at Sephora blew my mind! 🔬 Mapped every pore and created a custom routine. The future of personalized skincare is here! Anyone else tried these high-tech consultations? - Avery, Stockholm 🇸🇪 #BioprintScanner #PersonalizedSkincare #BeautyTech', 'story', 'skincare', ARRAY['bioprint-scanner', 'personalized-skincare', 'beauty-tech'], ARRAY['https://images.unsplash.com/photo-1583001931096-959e9a1a6223'], 178, 33, true, NOW() - INTERVAL '7 days');