
import { JobTemplate, IndustryType } from '@/components/posting/job/jobFormSchema';

// Define job templates for each industry
export const getJobTemplate = (industry: IndustryType): JobTemplate => {
  return jobTemplates[industry] || jobTemplates.custom;
};

// Job templates for different industries
export const jobTemplates: Record<IndustryType, JobTemplate> = {
  nails: {
    id: 'nails-template',
    title: 'Nail Technician Wanted',
    industry: 'nails',
    salonName: 'Crystal Nails & Spa',
    description: 'Looking for experienced nail technicians to join our busy salon. Great pay, flexible hours, and a friendly team environment.',
    vietnameseDescription: 'Cần thợ nail có kinh nghiệm, lương cao, giờ giấc linh động, môi trường làm việc thân thiện.',
    location: 'Houston, TX',
    jobType: 'full-time',
    compensation_type: 'commission',
    compensation_details: '60/40 commission',
    weekly_pay: true,
    has_housing: true,
    has_wax_room: true,
    owner_will_train: false,
    no_supply_deduction: true,
    salary_range: '$800-$1500/week',
    experience_level: '1+ years',
    requirements: [
      'Valid nail license',
      'At least 1 year of experience',
      'Acrylic and gel experience required',
      'Customer service skills',
      'Weekend availability'
    ],
    specialties: [
      'Acrylic',
      'Gel',
      'Dipping powder',
      'Pedicure',
      'Nail art'
    ],
    thumbnailUrl: '/lovable-uploads/nail-salon.jpg',
    contactName: 'Kim Nguyen',
    contactEmail: 'crystalnails@example.com',
    contactPhone: '(713) 555-1234'
  },
  hair: {
    id: 'hair-template',
    title: 'Hair Stylist Position Available',
    industry: 'hair',
    salonName: 'Blush Hair Studio',
    description: 'Upscale hair salon seeking talented stylists to join our team. Bring your creativity and build your clientele with us in a supportive environment.',
    vietnameseDescription: 'Salon cao cấp đang tìm kiếm các nhà tạo mẫu tóc tài năng. Hãy mang sự sáng tạo của bạn và xây dựng khách hàng với chúng tôi trong môi trường hỗ trợ.',
    location: 'Los Angeles, CA',
    jobType: 'full-time',
    compensation_type: 'commission',
    compensation_details: '50/50 commission',
    weekly_pay: true,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: false,
    no_supply_deduction: false,
    salary_range: '$1000-$2000/week',
    experience_level: '2+ years',
    requirements: [
      'Cosmetology license',
      'At least 2 years of experience',
      'Portfolio of work',
      'Color mixing expertise',
      'Excellent customer service'
    ],
    specialties: [
      'Color',
      'Balayage',
      'Extensions',
      'Cutting',
      'Styling'
    ],
    thumbnailUrl: '/lovable-uploads/hair-salon.jpg',
    contactName: 'Jessica Williams',
    contactEmail: 'blushhair@example.com',
    contactPhone: '(323) 555-6789'
  },
  lashes: {
    id: 'lashes-template',
    title: 'Lash Artist Needed',
    industry: 'lashes',
    salonName: 'Flutter Lash Studio',
    description: 'Growing lash studio looking for certified lash technicians. Join our team and help clients achieve gorgeous, fluttery lashes.',
    vietnameseDescription: 'Studio mi đang phát triển cần thợ mi có chứng chỉ. Tham gia đội ngũ của chúng tôi và giúp khách hàng có được hàng mi đẹp.',
    location: 'Dallas, TX',
    jobType: 'full-time',
    compensation_type: 'hourly',
    compensation_details: '$20-25/hour plus tips',
    weekly_pay: true,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: true,
    no_supply_deduction: true,
    salary_range: '$700-$1200/week',
    experience_level: '6+ months',
    requirements: [
      'Lash certification',
      'At least 6 months experience',
      'Professional demeanor',
      'Detail-oriented',
      'Able to work weekends'
    ],
    specialties: [
      'Classic lashes',
      'Volume lashes',
      'Hybrid sets',
      'Lash lifts',
      'Lash tinting'
    ],
    thumbnailUrl: '/lovable-uploads/lash-studio.jpg',
    contactName: 'Sarah Johnson',
    contactEmail: 'flutter@example.com',
    contactPhone: '(214) 555-9876'
  },
  massage: {
    id: 'massage-template',
    title: 'Licensed Massage Therapist',
    industry: 'massage',
    salonName: 'Serenity Massage & Spa',
    description: 'Upscale day spa seeking licensed massage therapists to perform various modalities. Join our team of wellness professionals.',
    vietnameseDescription: 'Spa cao cấp đang tìm kiếm các nhà trị liệu massage có giấy phép để thực hiện các phương pháp khác nhau. Tham gia đội ngũ chuyên gia sức khỏe của chúng tôi.',
    location: 'Chicago, IL',
    jobType: 'part-time',
    compensation_type: 'commission',
    compensation_details: '60% commission',
    weekly_pay: false,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: false,
    no_supply_deduction: true,
    salary_range: '$1000-$1800/week',
    experience_level: '2+ years',
    requirements: [
      'State massage license',
      'At least 2 years experience',
      'Professional appearance',
      'Knowledge of multiple modalities',
      'Excellent time management'
    ],
    specialties: [
      'Deep tissue',
      'Swedish',
      'Hot stone',
      'Sports massage',
      'Prenatal'
    ],
    thumbnailUrl: '/lovable-uploads/massage-spa.jpg',
    contactName: 'Michael Chen',
    contactEmail: 'serenity@example.com',
    contactPhone: '(312) 555-4321'
  },
  tattoo: {
    id: 'tattoo-template',
    title: 'Tattoo Artist Position',
    industry: 'tattoo',
    salonName: 'Ink & Art Tattoo Studio',
    description: 'Established tattoo studio looking for talented artists to join our team. Bring your portfolio and clientele to grow with us.',
    vietnameseDescription: 'Studio xăm hình đã thành lập đang tìm kiếm các nghệ sĩ tài năng tham gia đội ngũ của chúng tôi. Mang theo danh mục và khách hàng của bạn để phát triển cùng chúng tôi.',
    location: 'Austin, TX',
    jobType: 'full-time',
    compensation_type: 'commission',
    compensation_details: '70/30 split',
    weekly_pay: false,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: false,
    no_supply_deduction: false,
    salary_range: 'Varies based on clientele',
    experience_level: '3+ years',
    requirements: [
      'Professional portfolio',
      'At least 3 years experience',
      'Bloodborne pathogen certification',
      'Knowledge of sterilization procedures',
      'Strong drawing skills'
    ],
    specialties: [
      'Traditional',
      'Neo-traditional',
      'Japanese',
      'Realism',
      'Black and grey'
    ],
    thumbnailUrl: '/lovable-uploads/tattoo-studio.jpg',
    contactName: 'Alex Rodriguez',
    contactEmail: 'inkart@example.com',
    contactPhone: '(512) 555-8765'
  },
  brows: {
    id: 'brows-template',
    title: 'Brow Artist Wanted',
    industry: 'brows',
    salonName: 'Perfect Arch Brow Bar',
    description: 'Seeking skilled brow artists for our specialized brow studio. Experience with microblading and brow lamination preferred.',
    vietnameseDescription: 'Tìm kiếm nghệ sĩ chân mày có kỹ năng cho studio chân mày chuyên biệt của chúng tôi. Ưu tiên kinh nghiệm về microblading và uốn lông mày.',
    location: 'Miami, FL',
    jobType: 'full-time',
    compensation_type: 'hourly',
    compensation_details: '$18-22/hour plus tips',
    weekly_pay: true,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: true,
    no_supply_deduction: true,
    salary_range: '$600-$1000/week',
    experience_level: '1+ years',
    requirements: [
      'Esthetics or cosmetology license',
      'At least 1 year experience',
      'Knowledge of brow mapping',
      'Excellent attention to detail',
      'Customer service skills'
    ],
    specialties: [
      'Brow shaping',
      'Microblading',
      'Brow lamination',
      'Brow tinting',
      'Threading'
    ],
    thumbnailUrl: '/lovable-uploads/brow-studio.jpg',
    contactName: 'Olivia Martinez',
    contactEmail: 'perfectarch@example.com',
    contactPhone: '(305) 555-2468'
  },
  skincare: {
    id: 'skincare-template',
    title: 'Esthetician Needed',
    industry: 'skincare',
    salonName: 'Glow Skincare Studio',
    description: 'Luxury skincare studio seeking licensed estheticians to perform facials, peels, and other skin treatments in our serene environment.',
    vietnameseDescription: 'Studio chăm sóc da cao cấp đang tìm kiếm các chuyên gia thẩm mỹ có giấy phép để thực hiện các liệu pháp chăm sóc da trong môi trường thanh lịch của chúng tôi.',
    location: 'Seattle, WA',
    jobType: 'full-time',
    compensation_type: 'hybrid',
    compensation_details: 'Base + commission',
    weekly_pay: false,
    has_housing: false,
    has_wax_room: true,
    owner_will_train: false,
    no_supply_deduction: true,
    salary_range: '$800-$1500/week',
    experience_level: '2+ years',
    requirements: [
      'Esthetics license',
      'At least 2 years experience',
      'Knowledge of skincare products',
      'Experience with chemical peels',
      'Professional demeanor'
    ],
    specialties: [
      'Facials',
      'Chemical peels',
      'Microdermabrasion',
      'LED therapy',
      'Extractions'
    ],
    thumbnailUrl: '/lovable-uploads/skincare-studio.jpg',
    contactName: 'Emma Wilson',
    contactEmail: 'glowskincare@example.com',
    contactPhone: '(206) 555-3690'
  },
  barber: {
    id: 'barber-template',
    title: 'Barber Position Open',
    industry: 'barber',
    salonName: 'Classic Cuts Barbershop',
    description: 'Traditional barbershop seeking skilled barbers for cuts, shaves, and beard trims. Join our team and build your clientele in our busy location.',
    vietnameseDescription: 'Tiệm cắt tóc truyền thống đang tìm kiếm thợ cắt tóc có kỹ năng cho các kiểu cắt, cạo râu và tỉa râu. Tham gia đội ngũ của chúng tôi và xây dựng khách hàng của bạn tại địa điểm sôi động của chúng tôi.',
    location: 'Philadelphia, PA',
    jobType: 'full-time',
    compensation_type: 'commission',
    compensation_details: '70/30 split',
    weekly_pay: true,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: false,
    no_supply_deduction: true,
    salary_range: '$800-$1500/week',
    experience_level: '2+ years',
    requirements: [
      'Barber license',
      'At least 2 years experience',
      'Skilled with razor shaves',
      'Knowledge of current trends',
      'Strong customer service'
    ],
    specialties: [
      'Fades',
      'Razor shaves',
      'Beard trims',
      'Line-ups',
      'Hot towel service'
    ],
    thumbnailUrl: '/lovable-uploads/barbershop.jpg',
    contactName: 'James Thompson',
    contactEmail: 'classiccuts@example.com',
    contactPhone: '(267) 555-1357'
  },
  makeup: {
    id: 'makeup-template',
    title: 'Makeup Artist Position',
    industry: 'makeup',
    salonName: 'Glam Squad Beauty',
    description: 'Seeking talented makeup artists to join our beauty team for special events, photoshoots, and in-studio services.',
    vietnameseDescription: 'Tìm kiếm các nghệ sĩ trang điểm tài năng tham gia đội ngũ làm đẹp của chúng tôi cho các sự kiện đặc biệt, chụp ảnh và dịch vụ trong studio.',
    location: 'New York, NY',
    jobType: 'part-time',
    compensation_type: 'hybrid',
    compensation_details: 'Hourly + commission on products',
    weekly_pay: false,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: false,
    no_supply_deduction: false,
    salary_range: 'Varies based on bookings',
    experience_level: '2+ years',
    requirements: [
      'Professional makeup kit',
      'At least 2 years experience',
      'Portfolio of work',
      'Knowledge of different skin types',
      'Available for weekend events'
    ],
    specialties: [
      'Bridal makeup',
      'Editorial',
      'Special effects',
      'Airbrush',
      'Contouring'
    ],
    thumbnailUrl: '/lovable-uploads/makeup-studio.jpg',
    contactName: 'Nicole Parker',
    contactEmail: 'glamsquad@example.com',
    contactPhone: '(212) 555-9753'
  },
  custom: {
    id: 'custom-template',
    title: '',
    industry: 'custom',
    salonName: '',
    description: '',
    vietnameseDescription: '',
    location: '',
    jobType: 'full-time',
    compensation_type: 'hourly',
    compensation_details: '',
    weekly_pay: false,
    has_housing: false,
    has_wax_room: false,
    owner_will_train: false,
    no_supply_deduction: false,
    salary_range: '',
    experience_level: '',
    requirements: [],
    specialties: [],
    thumbnailUrl: '/lovable-uploads/placeholder.jpg',
    contactName: '',
    contactEmail: '',
    contactPhone: ''
  }
};
