
import { JobFormValues } from '@/components/posting/job/jobFormSchema';

export type JobTemplateType = 
  | 'nails' 
  | 'hair' 
  | 'lashes' 
  | 'barber' 
  | 'skincare' 
  | 'spa' 
  | 'receptionist' 
  | 'manager' 
  | 'massage' 
  | 'tattoo' 
  | 'makeup' 
  | 'booth' 
  | 'beauty' 
  | 'custom';

export const getJobTemplate = (type: JobTemplateType): JobFormValues => {
  const templates: Record<JobTemplateType, JobFormValues> = {
    nails: {
      title: "Nail Technician Needed",
      description: "We're seeking a skilled nail technician with experience in manicures, pedicures, and nail art. Join our team in a friendly, upscale salon environment with competitive compensation.",
      vietnameseDescription: "Chúng tôi đang tìm kiếm một kỹ thuật viên nail có kinh nghiệm về làm móng tay, móng chân và nghệ thuật móng. Tham gia đội của chúng tôi trong môi trường salon sang trọng, thân thiện với mức thù lao cạnh tranh.",
      location: "",
      jobType: "full-time",
      compensation_type: "commission",
      weekly_pay: true,
      has_housing: false,
      has_wax_room: true,
      owner_will_train: false,
      no_supply_deduction: true,
      requirements: ["1+ year experience", "Nail art skills", "Customer service", "English basics"],
      specialties: ["Manicure", "Pedicure", "Gel", "Acrylic", "Nail Art", "Dipping Powder"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    hair: {
      title: "Hair Stylist Position Available",
      description: "Looking for an experienced hair stylist to join our team. Skills in cutting, coloring, and styling required. Great opportunity to build your clientele in a busy salon.",
      vietnameseDescription: "Đang tìm kiếm một nhà tạo mẫu tóc có kinh nghiệm để tham gia nhóm của chúng tôi. Yêu cầu kỹ năng cắt, nhuộm và tạo kiểu. Cơ hội tuyệt vời để xây dựng khách hàng của bạn trong một salon nhộn nhịp.",
      location: "",
      jobType: "full-time",
      compensation_type: "booth rental",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: false,
      requirements: ["2+ years experience", "Cutting & coloring skills", "Client portfolio", "Professional attitude"],
      specialties: ["Cutting", "Coloring", "Styling", "Extensions", "Balayage", "Highlights"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    lashes: {
      title: "Eyelash Extension Technician",
      description: "Seeking a lash artist to join our beauty studio. Experience with classic, volume, and hybrid lash extensions required. Certification preferred.",
      vietnameseDescription: "Tìm kiếm một nghệ sĩ mi để tham gia studio làm đẹp của chúng tôi. Yêu cầu kinh nghiệm với nối mi classic, volume và hybrid. Ưu tiên có chứng chỉ.",
      location: "",
      jobType: "full-time",
      compensation_type: "commission",
      weekly_pay: true,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: true,
      requirements: ["Lash certification", "1+ year experience", "Portfolio of work", "Client retention skills"],
      specialties: ["Classic Lashes", "Volume Lashes", "Hybrid Lashes", "Lash Lifts", "Lash Tinting"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    barber: {
      title: "Barber Wanted - Immediate Position",
      description: "Busy barbershop looking for skilled barber. Experience with fades, beard trims, and razor work required. Great earning potential with existing clientele.",
      vietnameseDescription: "Tiệm cắt tóc bận rộn đang tìm thợ cắt tóc có kỹ năng. Yêu cầu kinh nghiệm với kiểu fade, tỉa râu và làm việc với dao cạo. Tiềm năng thu nhập tốt với khách hàng hiện có.",
      location: "",
      jobType: "full-time",
      compensation_type: "commission",
      weekly_pay: true,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: true,
      requirements: ["2+ years experience", "Skilled in modern techniques", "Professional appearance", "Reliable transportation"],
      specialties: ["Fades", "Beard Trims", "Hot Towel Shaves", "Razor Work", "Line-ups", "Hair Design"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    skincare: {
      title: "Esthetician Needed",
      description: "Spa seeking licensed esthetician for facials, treatments, and skincare services. Knowledge of professional product lines and excellent customer service required.",
      vietnameseDescription: "Spa đang tìm kiếm chuyên gia thẩm mỹ được cấp phép cho các dịch vụ chăm sóc da mặt, điều trị và chăm sóc da. Yêu cầu kiến thức về các dòng sản phẩm chuyên nghiệp và dịch vụ khách hàng xuất sắc.",
      location: "",
      jobType: "full-time",
      compensation_type: "hourly + commission",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: true,
      owner_will_train: false,
      no_supply_deduction: true,
      requirements: ["Esthetician license", "1+ year experience", "Product knowledge", "Sales ability"],
      specialties: ["Facials", "Chemical Peels", "Waxing", "Microdermabrasion", "LED Therapy", "Skin Analysis"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    spa: {
      title: "Spa Technician Position",
      description: "Luxury spa seeking technicians for body treatments, scrubs, and wraps. Experience with high-end spa protocols preferred. Full and part-time positions available.",
      vietnameseDescription: "Spa cao cấp đang tìm kiếm kỹ thuật viên cho các liệu pháp cơ thể, tẩy tế bào chết và ủ. Ưu tiên có kinh nghiệm với các quy trình spa cao cấp. Có vị trí toàn thời gian và bán thời gian.",
      location: "",
      jobType: "part-time",
      compensation_type: "hourly + commission",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: true,
      no_supply_deduction: true,
      requirements: ["Spa certification", "Customer service skills", "Knowledge of body treatments", "Professional demeanor"],
      specialties: ["Body Treatments", "Body Scrubs", "Body Wraps", "Aromatherapy", "Hot Stone Therapy", "Hydrotherapy"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    receptionist: {
      title: "Salon Receptionist / Front Desk",
      description: "Busy salon seeking friendly, organized receptionist. Duties include scheduling appointments, greeting clients, handling phone calls, and processing payments.",
      vietnameseDescription: "Salon bận rộn đang tìm kiếm lễ tân thân thiện, có tổ chức. Nhiệm vụ bao gồm lên lịch hẹn, chào đón khách hàng, xử lý cuộc gọi điện thoại và xử lý thanh toán.",
      location: "",
      jobType: "full-time",
      compensation_type: "hourly",
      weekly_pay: true,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: true,
      no_supply_deduction: false,
      requirements: ["Customer service experience", "Computer skills", "Multi-tasking ability", "Professional phone manner"],
      specialties: ["Appointment Scheduling", "Client Relations", "Payment Processing", "Inventory Management", "Phone Skills"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    manager: {
      title: "Salon Manager - Experienced Leader Needed",
      description: "Growing salon seeking experienced manager to oversee daily operations, staff management, and business development. Leadership experience in beauty industry required.",
      vietnameseDescription: "Salon đang phát triển tìm kiếm người quản lý có kinh nghiệm để giám sát hoạt động hàng ngày, quản lý nhân viên và phát triển kinh doanh. Yêu cầu kinh nghiệm lãnh đạo trong ngành làm đẹp.",
      location: "",
      jobType: "full-time",
      compensation_type: "salary + bonus",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: false,
      requirements: ["3+ years salon management", "Staff supervision experience", "Business acumen", "Marketing skills"],
      specialties: ["Team Leadership", "Scheduling", "Inventory Control", "Client Relations", "Business Growth", "Staff Training"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    massage: {
      title: "Licensed Massage Therapist",
      description: "Wellness center seeking licensed massage therapist. Experience with Swedish, deep tissue, and sports massage required. Flexible scheduling available.",
      vietnameseDescription: "Trung tâm sức khỏe đang tìm kiếm nhà trị liệu massage có giấy phép. Yêu cầu kinh nghiệm với massage kiểu Thụy Điển, mô sâu và thể thao. Có lịch linh hoạt.",
      location: "",
      jobType: "part-time",
      compensation_type: "commission",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: true,
      requirements: ["Massage therapy license", "2+ years experience", "Multiple modalities", "Professional boundaries"],
      specialties: ["Swedish", "Deep Tissue", "Sports Massage", "Prenatal", "Hot Stone", "Reflexology"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    tattoo: {
      title: "Tattoo Artist Position",
      description: "Established tattoo studio seeking experienced artist. Must have strong portfolio showing diverse styles. Existing client base preferred but not required.",
      vietnameseDescription: "Studio xăm hình đã thành lập đang tìm kiếm nghệ sĩ có kinh nghiệm. Phải có portfolio mạnh mẽ thể hiện các phong cách đa dạng. Ưu tiên có sẵn khách hàng nhưng không bắt buộc.",
      location: "",
      jobType: "commission",
      compensation_type: "booth rental",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: false,
      requirements: ["3+ years professional experience", "Strong portfolio", "Bloodborne pathogen certification", "Clean work habits"],
      specialties: ["Traditional", "Realism", "Japanese", "Blackwork", "Color", "Custom Design"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    makeup: {
      title: "Makeup Artist Wanted",
      description: "Beauty studio seeking talented makeup artist for special events, bridal, and editorial work. Experience with diverse skin tones and photography makeup required.",
      vietnameseDescription: "Studio làm đẹp đang tìm kiếm chuyên gia trang điểm tài năng cho các sự kiện đặc biệt, trang điểm cô dâu và công việc biên tập. Yêu cầu kinh nghiệm với các tông da đa dạng và trang điểm chụp ảnh.",
      location: "",
      jobType: "part-time",
      compensation_type: "per event",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: false,
      requirements: ["Professional makeup kit", "Portfolio of work", "Weekend availability", "Client-focused approach"],
      specialties: ["Bridal", "Special Event", "Editorial", "Airbrush", "Halloween/SFX", "Natural Makeup"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    booth: {
      title: "Booth Rental Available - Prime Location",
      description: "Established salon offering booth rental for beauty professionals. Great location with high foot traffic and existing clientele. All utilities included in rental fee.",
      vietnameseDescription: "Salon đã thành lập cung cấp cho thuê booth cho các chuyên gia làm đẹp. Vị trí tốt với lưu lượng khách bộ hành cao và khách hàng hiện tại. Tất cả tiện ích đều được bao gồm trong phí thuê.",
      location: "",
      jobType: "booth rental",
      compensation_type: "booth rental",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: true,
      owner_will_train: false,
      no_supply_deduction: false,
      requirements: ["Beauty professional license", "Self-motivated", "Client base preferred", "Professional equipment"],
      specialties: ["Hair", "Nails", "Lashes", "Brows", "Facials", "Waxing"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    beauty: {
      title: "Beauty Professional Needed",
      description: "Full-service salon seeking licensed beauty professional. Multiple services possible depending on your specialization and experience.",
      vietnameseDescription: "Salon dịch vụ đầy đủ đang tìm kiếm chuyên gia làm đẹp được cấp phép. Có thể cung cấp nhiều dịch vụ tùy thuộc vào chuyên môn và kinh nghiệm của bạn.",
      location: "",
      jobType: "full-time",
      compensation_type: "commission",
      weekly_pay: true,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: true,
      no_supply_deduction: true,
      requirements: ["Beauty professional license", "Customer service skills", "Reliable", "Team player"],
      specialties: ["Various beauty services"],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    },
    custom: {
      title: "",
      description: "",
      vietnameseDescription: "",
      location: "",
      jobType: "full-time",
      compensation_type: "",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      owner_will_train: false,
      no_supply_deduction: false,
      requirements: [],
      specialties: [],
      contactName: "",
      contactEmail: "",
      contactPhone: "",
      salonName: ""
    }
  };

  return templates[type] || templates.custom;
};
