import { Job } from "@/types/job";

export const generateVietNailJobSamples = (): Job[] => {
  return [
    {
      id: "job-vn-001",
      role: "Nail Technician",
      title: "Cần Thợ Nail Giỏi",
      company: "Luxury Nails & Spa",
      location: "Houston, TX",
      posted_at: "2 days ago",
      created_at: new Date().toISOString(),
      description: "Tiệm nail sang trọng ở Houston cần tuyển thợ nail có kinh nghiệm làm everything. Bao lương hoặc ăn chia.",
      employment_type: "Full-time/Part-time",
      compensation_details: "$800 - $1200/week",
      contact_info: {
        owner_name: "Linh Nguyen",
        phone: "832-123-4567",
        email: "linh.nguyen@luxurynails.com",
        notes: "Liên hệ sau 5 giờ chiều."
      },
      for_sale: false,
      is_featured: true,
      status: "active",
      image: "https://example.com/nail-salon.jpg",
      weekly_pay: true,
      has_housing: true,
      has_wax_room: true,
      no_supply_deduction: true,
      owner_will_train: false,
      tip_range: "20%+",
      salary_range: "$40k - $60k",
      vietnamese_description: "Tiệm lớn, khách sang trọng, môi trường làm việc thoải mái.",
      salon_type: "Nail Salon",
      expires_at: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      requirements: ["Có bằng nail", "Kinh nghiệm 2 năm trở lên"],
      preferred_languages: ["Vietnamese", "English"],
      benefits: ["Bảo hiểm y tế", "Nghỉ phép có lương"],
      features: ["Máy lạnh", "Wifi miễn phí"],
      price: "$0",
      monthly_rent: "$0",
      is_urgent: false,
    },
    {
      id: "job-vn-002",
      role: "Eyelash Technician",
      title: "Tuyển Thợ Nối Mi",
      company: "Bella Lash Studio",
      location: "Garden Grove, CA",
      posted_at: "1 week ago",
      created_at: new Date().toISOString(),
      description: "Studio nối mi chuyên nghiệp tại Garden Grove cần tuyển thợ nối mi có tay nghề cao. Lương cao, thưởng hấp dẫn.",
      employment_type: "Full-time",
      compensation_details: "$1000 - $1500/week",
      contact_info: {
        owner_name: "Mai Tran",
        phone: "714-987-6543",
        email: "mai.tran@bellalash.com",
        notes: "Ưu tiên người có kinh nghiệm."
      },
      for_sale: false,
      is_featured: false,
      status: "active",
      image: "https://example.com/eyelash-studio.jpg",
      weekly_pay: true,
      has_housing: false,
      has_wax_room: false,
      no_supply_deduction: true,
      owner_will_train: false,
      tip_range: "15%+",
      salary_range: "$50k - $70k",
      vietnamese_description: "Môi trường làm việc thân thiện, cơ hội phát triển nghề nghiệp.",
      salon_type: "Eyelash Studio",
      expires_at: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      requirements: ["Chứng chỉ nối mi", "Kỹ năng giao tiếp tốt"],
      preferred_languages: ["Vietnamese"],
      benefits: ["Hoa hồng cao", "Đào tạo nâng cao"],
      features: ["Thiết bị hiện đại", "Sản phẩm chất lượng"],
      price: "$0",
      monthly_rent: "$0",
      is_urgent: false,
    },
    {
      id: "job-vn-003",
      role: "Salon Manager",
      title: "Tìm Quản Lý Tiệm Nail",
      company: "Diamond Nails",
      location: "San Jose, CA",
      posted_at: "3 weeks ago",
      created_at: new Date().toISOString(),
      description: "Tiệm nail lớn ở San Jose cần tuyển quản lý có kinh nghiệm. Lương thỏa thuận, có thưởng.",
      employment_type: "Full-time",
      compensation_details: "$50k - $80k/year",
      contact_info: {
        owner_name: "Duc Pham",
        phone: "408-555-1212",
        email: "duc.pham@diamondnails.com",
        notes: "Gửi resume qua email."
      },
      for_sale: false,
      is_featured: false,
      status: "active",
      image: "https://example.com/nail-salon-interior.jpg",
      weekly_pay: false,
      has_housing: false,
      has_wax_room: false,
      no_supply_deduction: false,
      owner_will_train: false,
      tip_range: "N/A",
      salary_range: "$50k - $80k",
      vietnamese_description: "Cần người có khả năng quản lý, giao tiếp tốt.",
      salon_type: "Nail Salon",
      expires_at: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      requirements: ["Kinh nghiệm quản lý 3 năm", "Tiếng Anh lưu loát"],
      preferred_languages: ["Vietnamese", "English"],
      benefits: ["Bảo hiểm", "Thưởng cuối năm"],
      features: ["Môi trường chuyên nghiệp", "Cơ hội thăng tiến"],
      price: "$0",
      monthly_rent: "$0",
      is_urgent: false,
    },
    {
      id: "job-vn-004",
      role: "Waxing Specialist",
      title: "Cần Thợ Waxing",
      company: "Smooth Skin Spa",
      location: "Dallas, TX",
      posted_at: "1 month ago",
      created_at: new Date().toISOString(),
      description: "Spa chuyên về waxing ở Dallas cần tuyển thợ waxing có kinh nghiệm. Lương cao, có khách hàng.",
      employment_type: "Full-time/Part-time",
      compensation_details: "$900 - $1400/week",
      contact_info: {
        owner_name: "Thuy Le",
        phone: "214-777-8888",
        email: "thuy.le@smoothskin.com",
        notes: "Gọi điện để phỏng vấn."
      },
      for_sale: false,
      is_featured: false,
      status: "active",
      image: "https://example.com/waxing-room.jpg",
      weekly_pay: true,
      has_housing: false,
      has_wax_room: true,
      no_supply_deduction: true,
      owner_will_train: false,
      tip_range: "18%+",
      salary_range: "$45k - $65k",
      vietnamese_description: "Môi trường làm việc thoải mái, đồng nghiệp thân thiện.",
      salon_type: "Waxing Spa",
      expires_at: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      requirements: ["Chứng chỉ waxing", "Kỹ năng làm việc nhóm"],
      preferred_languages: ["Vietnamese"],
      benefits: ["Chiết khấu dịch vụ", "Thưởng theo doanh số"],
      features: ["Phòng waxing riêng", "Sản phẩm chất lượng"],
      price: "$0",
      monthly_rent: "$0",
      is_urgent: false,
    },
    {
      id: "job-vn-005",
      role: "Manicurist/Pedicurist",
      title: "Tuyển Thợ Làm Móng Tay Chân",
      company: "Elegant Nails",
      location: "Atlanta, GA",
      posted_at: "2 months ago",
      created_at: new Date().toISOString(),
      description: "Tiệm nail ở Atlanta cần tuyển thợ làm móng tay chân có kinh nghiệm. Bao lương hoặc ăn chia, tùy chọn.",
      employment_type: "Full-time/Part-time",
      compensation_details: "$700 - $1100/week",
      contact_info: {
        owner_name: "Hung Nguyen",
        phone: "404-222-3333",
        email: "hung.nguyen@elegantnails.com",
        notes: "Liên hệ trực tiếp để biết thêm chi tiết."
      },
      for_sale: false,
      is_featured: false,
      status: "active",
      image: "https://example.com/manicure-table.jpg",
      weekly_pay: true,
      has_housing: true,
      has_wax_room: false,
      no_supply_deduction: true,
      owner_will_train: false,
      tip_range: "20%+",
      salary_range: "$35k - $55k",
      vietnamese_description: "Tiệm đông khách, thu nhập ổn định.",
      salon_type: "Nail Salon",
      expires_at: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      requirements: ["Kinh nghiệm làm móng 1 năm", "Nhiệt tình, chịu khó"],
      preferred_languages: ["Vietnamese"],
      benefits: ["Thưởng lễ tết", "Tăng lương định kỳ"],
      features: ["Môi trường làm việc vui vẻ", "Khách hàng lịch sự"],
      price: "$0",
      monthly_rent: "$0",
      is_urgent: false,
    },
    {
      id: "job-vn-123",
      role: "Nail Technician",
      title: "Gấp! Cần Thợ Nail Gấp",
      company: "Express Nails",
      location: "Westminster, CA",
      posted_at: "1 day ago",
      created_at: new Date().toISOString(),
      description: "Tiệm nail ở Westminster cần thợ nail gấp, có kinh nghiệm làm bột và shellac. Lương cao, bao ăn ở.",
      employment_type: "Full-time",
      compensation_details: "$1200 - $1800/week",
      contact_info: {
        owner_name: "Loan Tran",
        phone: "714-111-2222",
        email: "loan.tran@expressnails.com",
        notes: "Gọi ngay để nhận việc."
      },
      for_sale: false,
      is_featured: true,
      status: "active",
      image: "https://example.com/urgent-nail-job.jpg",
      weekly_pay: true,
      has_housing: true,
      has_wax_room: false,
      no_supply_deduction: true,
      owner_will_train: false,
      tip_range: "25%+",
      salary_range: "$60k - $90k",
      vietnamese_description: "Cần thợ giỏi, làm nhanh, có trách nhiệm.",
      salon_type: "Nail Salon",
      expires_at: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
      requirements: ["Kinh nghiệm 3 năm trở lên", "Biết làm everything"],
      preferred_languages: ["Vietnamese"],
      benefits: ["Bao ăn ở", "Thưởng thêm"],
      features: ["Môi trường làm việc năng động", "Khách hàng dễ tính"],
      price: "$0",
      monthly_rent: "$0",
      is_urgent: true,
    },
  ];
};
