
import { Job } from '@/types/job';

// Generate a sample of Vietnamese nail salon job listings - these are authentic job listings
export const generateVietnameseNailJobs = (): Job[] => {
  const jobs: Job[] = [
    {
      id: 'vn-job-1',
      title: 'Magic Nails – Thợ Nail Giỏi',
      role: 'Nail Technician',
      company: 'Magic Nails',
      location: 'Great Falls, MT',
      employment_type: 'Full-time',
      description: 'Experienced nail technician needed for busy salon. Great tips and friendly environment.',
      vietnamese_description: 'Tiệm đông khách cần thợ nail có kinh nghiệm. Tip cao, môi trường làm việc thân thiện.',
      salary_range: '$1000-$1500/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Acrylic', 'Gel', 'Dip Powder'],
      contact_info: {
        phone: '(406) 453-0261',
        email: 'magicnails@example.com'
      },
      tip_range: '$300-$500/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: true,
      no_supply_deduction: true,
      is_featured: true,
      is_urgent: true,
      image: "/lovable-uploads/8858fff4-1fa3-4803-86b1-beadca5fd1df.png",
    },
    {
      id: 'vn-job-2',
      title: 'Cần Thợ Bột, Tay Chân Nước',
      role: 'Nail Technician',
      company: 'Rose Nails',
      location: 'Garden Grove, CA',
      employment_type: 'Full-time',
      description: 'Looking for skilled technicians for acrylic and pedicure services. Good pay and benefits.',
      vietnamese_description: 'Tìm thợ giỏi làm bột và tay chân nước. Lương cao và có nhiều phúc lợi.',
      salary_range: '$800-$1500/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Acrylic', 'Pedicure', 'Manicure'],
      contact_info: {
        phone: '(714) 555-4567',
        email: 'rosenails@example.com'
      },
      tip_range: '$250-$500/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: false,
      no_supply_deduction: true,
      is_featured: false,
      is_urgent: false,
      image: "/lovable-uploads/89855878-2908-47b5-98b0-1935d73cdd71.png",
    },
    {
      id: 'vn-job-3',
      title: 'Thợ Nail Biết Làm Đủ Thứ',
      role: 'Nail Technician',
      company: 'Kim Nails',
      location: 'San Jose, CA',
      employment_type: 'Part-time',
      description: 'Part-time position available for a technician who can do all types of nail services.',
      vietnamese_description: 'Cần thợ làm bán thời gian, biết làm tất cả các dịch vụ về nail.',
      salary_range: '$900-$1200/tuần',
      created_at: new Date().toISOString(),
      specialties: ['All Services'],
      contact_info: {
        phone: '(408) 555-7890',
        email: 'kimnails@example.com'
      },
      tip_range: '$100-$300/tuần',
      weekly_pay: false,
      owner_will_train: true,
      has_housing: false,
      no_supply_deduction: false,
      is_featured: false,
      is_urgent: false,
      image: "/lovable-uploads/2542d0a3-5117-433d-baee-5c0fe2bfeca2.png",
    },
    {
      id: 'vn-job-4',
      title: 'Thợ Nail Lành Nghề',
      role: 'Nail Technician',
      company: 'Elegant Nails',
      location: 'Westminster, CA',
      employment_type: 'Full-time',
      description: 'Looking for experienced nail technicians. High-end salon with great clientele.',
      vietnamese_description: 'Tìm thợ nail có kinh nghiệm. Tiệm cao cấp với khách hàng tốt.',
      salary_range: '$1200-$1800/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Gel-X', 'Design', 'Pedicure'],
      contact_info: {
        phone: '(714) 555-1234',
        email: 'elegantnails@example.com'
      },
      tip_range: '$300-$600/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: true,
      no_supply_deduction: true,
      is_featured: true,
      is_urgent: false,
      image: "/lovable-uploads/8283328c-3a93-4562-be8b-32c35c31a600.png",
    },
    {
      id: 'vn-job-5',
      title: 'Thợ Bột/Dipping Powder',
      role: 'Nail Technician',
      company: 'Beautiful Nails & Spa',
      location: 'Houston, TX',
      employment_type: 'Full-time',
      description: 'Specialized position for powder nail technicians. Great income potential.',
      vietnamese_description: 'Vị trí chuyên biệt cho thợ làm bột. Thu nhập tiềm năng cao.',
      salary_range: '$1100-$1600/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Dip Powder', 'Acrylic', 'Design'],
      contact_info: {
        phone: '(832) 555-9876',
        email: 'beautifulnails@example.com'
      },
      tip_range: '$250-$450/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: true,
      no_supply_deduction: false,
      is_featured: false,
      is_urgent: true,
      image: "/lovable-uploads/2542d0a3-5117-433d-baee-5c0fe2bfeca2.png",
    },
    {
      id: 'vn-job-6',
      title: 'Cần Gấp Thợ Chuyên Gel-X',
      role: 'Nail Technician',
      company: 'Luxury Nails & Day Spa',
      location: 'Atlanta, GA',
      employment_type: 'Full-time',
      description: 'Urgent need for Gel-X specialists. Premium salon with high-end clientele.',
      vietnamese_description: 'Cần gấp thợ chuyên Gel-X. Tiệm cao cấp với khách hàng thượng lưu.',
      salary_range: '$1300-$2000/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Gel-X', 'Extensions', 'Art'],
      contact_info: {
        phone: '(404) 555-2468',
        email: 'luxurynails@example.com'
      },
      tip_range: '$400-$700/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: true,
      no_supply_deduction: true,
      is_featured: true,
      is_urgent: true,
      image: "/lovable-uploads/89855878-2908-47b5-98b0-1935d73cdd71.png",
    },
    {
      id: 'vn-job-7',
      title: 'Cần Thợ Biết Làm Tất Cả',
      role: 'Nail Technician',
      company: 'Perfect Nails',
      location: 'Dallas, TX',
      employment_type: 'Full-time',
      description: 'Looking for techs who can perform all services. Friendly team environment.',
      vietnamese_description: 'Tìm thợ biết làm tất cả các dịch vụ. Môi trường làm việc thân thiện.',
      salary_range: '$900-$1400/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Full Service', 'Acrylic', 'Gel', 'Pedicure'],
      contact_info: {
        phone: '(214) 555-3690',
        email: 'perfectnails@example.com'
      },
      tip_range: '$200-$400/tuần',
      weekly_pay: true,
      owner_will_train: true,
      has_housing: false,
      no_supply_deduction: false,
      is_featured: false,
      is_urgent: false,
      image: "/lovable-uploads/8858fff4-1fa3-4803-86b1-beadca5fd1df.png",
    },
    {
      id: 'vn-job-8',
      title: 'Thợ Nail Full-Time/Part-Time',
      role: 'Nail Technician',
      company: 'Crystal Nails',
      location: 'Orlando, FL',
      employment_type: 'Both',
      description: 'Flexible positions available for both full-time and part-time nail techs.',
      vietnamese_description: 'Có vị trí linh hoạt cho cả thợ toàn thời gian và bán thời gian.',
      salary_range: '$800-$1300/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Basic Manicure', 'Pedicure', 'Gel Polish'],
      contact_info: {
        phone: '(407) 555-9182',
        email: 'crystalnails@example.com'
      },
      tip_range: '$150-$350/tuần',
      weekly_pay: true,
      owner_will_train: true,
      has_housing: false,
      no_supply_deduction: true,
      is_featured: false,
      is_urgent: false,
      image: "/lovable-uploads/8283328c-3a93-4562-be8b-32c35c31a600.png",
    },
    {
      id: 'vn-job-9',
      title: 'Cần Thợ Nail Nam/Nữ',
      role: 'Nail Technician',
      company: 'Diamond Nails',
      location: 'Sacramento, CA',
      employment_type: 'Full-time',
      description: 'Positions open for both male and female nail techs. Great working conditions.',
      vietnamese_description: 'Vị trí dành cho cả thợ nam và nữ. Điều kiện làm việc tốt.',
      salary_range: '$1000-$1500/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Acrylic', 'Pedicure', 'Waxing'],
      contact_info: {
        phone: '(916) 555-7463',
        email: 'diamondnails@example.com'
      },
      tip_range: '$200-$450/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: true,
      no_supply_deduction: false,
      is_featured: false,
      is_urgent: false,
      image: "/lovable-uploads/2542d0a3-5117-433d-baee-5c0fe2bfeca2.png",
    },
    {
      id: 'vn-job-10',
      title: 'Cần Thợ Làm Móng Gấp',
      role: 'Nail Technician',
      company: 'Star Nails',
      location: 'Seattle, WA',
      employment_type: 'Full-time',
      description: 'Urgent positions available at busy downtown salon. High income potential.',
      vietnamese_description: 'Cần gấp thợ làm việc tại tiệm đông khách ở trung tâm. Thu nhập cao.',
      salary_range: '$1200-$1700/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Acrylic', 'Gel', 'Nail Art'],
      contact_info: {
        phone: '(206) 555-2857',
        email: 'starnails@example.com'
      },
      tip_range: '$300-$500/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: true,
      no_supply_deduction: true,
      is_featured: true,
      is_urgent: true,
      image: "/lovable-uploads/89855878-2908-47b5-98b0-1935d73cdd71.png",
    },
    {
      id: 'vn-job-11',
      title: 'Thợ Chân Tay Nước',
      role: 'Nail Technician',
      company: 'Serenity Nails & Spa',
      location: 'Austin, TX',
      employment_type: 'Full-time',
      description: 'Seeking specialists in manicure and pedicure services. Clean, modern salon.',
      vietnamese_description: 'Tìm chuyên gia dịch vụ làm tay và chân. Tiệm sạch sẽ, hiện đại.',
      salary_range: '$700-$1200/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Manicure', 'Pedicure', 'Paraffin'],
      contact_info: {
        phone: '(512) 555-1964',
        email: 'serenitynails@example.com'
      },
      tip_range: '$150-$300/tuần',
      weekly_pay: true,
      owner_will_train: true,
      has_housing: false,
      no_supply_deduction: true,
      is_featured: false,
      is_urgent: false,
      image: "/lovable-uploads/8858fff4-1fa3-4803-86b1-beadca5fd1df.png",
    },
    {
      id: 'vn-job-12',
      title: 'Thợ Nail Chuyên Làm Design',
      role: 'Nail Technician',
      company: 'Fashion Nails',
      location: 'Las Vegas, NV',
      employment_type: 'Full-time',
      description: 'Seeking nail artists specialized in detailed designs and nail art. Premium salon.',
      vietnamese_description: 'Tìm thợ nail chuyên về các thiết kế chi tiết và nghệ thuật móng. Tiệm cao cấp.',
      salary_range: '$1500-$2500/tuần',
      created_at: new Date().toISOString(),
      specialties: ['Nail Art', '3D Design', 'Swarovski'],
      contact_info: {
        phone: '(702) 555-8421',
        email: 'fashionnails@example.com'
      },
      tip_range: '$400-$800/tuần',
      weekly_pay: true,
      owner_will_train: false,
      has_housing: true,
      no_supply_deduction: true,
      is_featured: true,
      is_urgent: false,
      image: "/lovable-uploads/8283328c-3a93-4562-be8b-32c35c31a600.png",
    }
  ];
  
  return jobs;
};
