name: 🚀 GSC Priority URL Indexing

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Max URLs to submit (default: all 87)'
        required: false
        default: '87'
        type: string
      dry_run:
        description: 'Dry run mode (no actual submissions)'
        type: boolean
        default: false

env:
  BASE_URL: 'https://www.emvi.app'
  PRIORITY_URLS_FILE: 'seo/priority-urls.json'

jobs:
  gsc-priority-indexing:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 🔧 Install dependencies
        run: |
          npm ci
          npm install --no-save googleapis jsonwebtoken
      
      - name: 📁 Create reports directory
        run: mkdir -p reports/seo/indexing
      
      - name: 📋 Load and validate priority URLs
        id: load-urls
        run: |
          if [ ! -f "$PRIORITY_URLS_FILE" ]; then
            echo "❌ Priority URLs file not found: $PRIORITY_URLS_FILE"
            exit 1
          fi
          
          # Count total URLs
          TOTAL_URLS=$(jq length "$PRIORITY_URLS_FILE")
          echo "📊 Found $TOTAL_URLS priority URLs"
          
          # Apply limit if specified
          LIMIT="${{ github.event.inputs.limit || '87' }}"
          if [ "$LIMIT" -lt "$TOTAL_URLS" ]; then
            echo "⚠️ Limiting to $LIMIT URLs (from $TOTAL_URLS total)"
            URLS_TO_PROCESS=$LIMIT
          else
            URLS_TO_PROCESS=$TOTAL_URLS
          fi
          
          echo "urls_to_process=$URLS_TO_PROCESS" >> $GITHUB_OUTPUT
          echo "total_urls=$TOTAL_URLS" >> $GITHUB_OUTPUT
          
          # Show first 10 URLs for verification
          echo "📋 First 10 priority URLs:"
          jq -r '.[:10][]' "$PRIORITY_URLS_FILE" | while read -r url; do
            echo "  $url"
          done
          
          if [ "$URLS_TO_PROCESS" -gt 10 ]; then
            echo "  ... and $(($URLS_TO_PROCESS - 10)) more URLs"
          fi
      
      - name: 🚀 Submit URLs to GSC Indexing API
        id: submit-urls
        env:
          GSC_CREDENTIALS: ${{ secrets.GSC_CREDENTIALS }}
          GSC_CLIENT_EMAIL: ${{ secrets.GSC_CLIENT_EMAIL }}
          GSC_PRIVATE_KEY: ${{ secrets.GSC_PRIVATE_KEY }}
          DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}
        run: |
          cat > submit-priority-indexing.js << 'EOF'
          const { google } = require('googleapis');
          const fs = require('fs');
          
          async function submitPriorityIndexing() {
            try {
              // Configure authentication with fallback
              let credentials;
              
              if (process.env.GSC_CREDENTIALS) {
                try {
                  credentials = JSON.parse(process.env.GSC_CREDENTIALS);
                } catch (e) {
                  console.log('GSC_CREDENTIALS is not valid JSON, trying individual fields...');
                }
              }
              
              if (!credentials && process.env.GSC_CLIENT_EMAIL && process.env.GSC_PRIVATE_KEY) {
                credentials = {
                  client_email: process.env.GSC_CLIENT_EMAIL,
                  private_key: process.env.GSC_PRIVATE_KEY.replace(/\\n/g, '\n'),
                };
              }
              
              if (!credentials) {
                throw new Error('No GSC credentials found');
              }
              
              const auth = new google.auth.GoogleAuth({
                credentials: credentials,
                scopes: ['https://www.googleapis.com/auth/indexing'],
              });
              
              const indexing = google.indexing({ version: 'v3', auth });
              
              // Load priority URLs
              const urlsData = JSON.parse(fs.readFileSync('${{ env.PRIORITY_URLS_FILE }}', 'utf8'));
              const limit = parseInt('${{ steps.load-urls.outputs.urls_to_process }}');
              const urlsToProcess = urlsData.slice(0, limit);
              
              console.log(`🚀 Processing ${urlsToProcess.length} priority URLs...`);
              console.log(`🔒 Mode: ${process.env.DRY_RUN === 'true' ? 'DRY RUN' : 'LIVE SUBMISSION'}`);
              
              const results = {
                timestamp: new Date().toISOString(),
                total_urls: urlsToProcess.length,
                submitted: 0,
                success: 0,
                failed: 0,
                errors: [],
                responses: []
              };
              
              const BATCH_SIZE = 10;
              const DELAY_BETWEEN_BATCHES = 60000; // 1 minute
              const DELAY_BETWEEN_REQUESTS = 3000; // 3 seconds
              
              // Process URLs in batches
              for (let i = 0; i < urlsToProcess.length; i += BATCH_SIZE) {
                const batch = urlsToProcess.slice(i, i + BATCH_SIZE);
                const batchNum = Math.floor(i / BATCH_SIZE) + 1;
                const totalBatches = Math.ceil(urlsToProcess.length / BATCH_SIZE);
                
                console.log(`\n📦 Processing batch ${batchNum}/${totalBatches} (${batch.length} URLs)`);
                
                for (const url of batch) {
                  results.submitted++;
                  
                  try {
                    if (process.env.DRY_RUN === 'true') {
                      console.log(`  🧪 DRY RUN: Would submit ${url}`);
                      results.success++;
                      results.responses.push({ url, status: 'dry_run_success' });
                    } else {
                      console.log(`  📤 Submitting: ${url}`);
                      
                      const response = await indexing.urlNotifications.publish({
                        requestBody: {
                          url: url,
                          type: 'URL_UPDATED'
                        }
                      });
                      
                      console.log(`  ✅ Success: ${url}`);
                      results.success++;
                      results.responses.push({ 
                        url, 
                        status: 'success',
                        response: response.data
                      });
                    }
                  } catch (error) {
                    console.log(`  ❌ Failed: ${url} - ${error.message}`);
                    results.failed++;
                    results.errors.push({ url, error: error.message });
                    results.responses.push({ 
                      url, 
                      status: 'failed',
                      error: error.message
                    });
                  }
                  
                  // Delay between individual requests
                  if (batch.indexOf(url) < batch.length - 1) {
                    await new Promise(resolve => setTimeout(resolve, DELAY_BETWEEN_REQUESTS));
                  }
                }
                
                // Delay between batches (except for last batch)
                if (i + BATCH_SIZE < urlsToProcess.length) {
                  console.log(`  ⏳ Waiting ${DELAY_BETWEEN_BATCHES/1000}s before next batch...`);
                  await new Promise(resolve => setTimeout(resolve, DELAY_BETWEEN_BATCHES));
                }
              }
              
              // Save detailed results
              const reportFile = `reports/seo/indexing/priority-indexing-${new Date().toISOString().split('T')[0]}.json`;
              fs.writeFileSync(reportFile, JSON.stringify(results, null, 2));
              
              // Set outputs for GitHub Actions
              console.log(`\n📊 Priority Indexing Results:`);
              console.log(`   Total URLs: ${results.total_urls}`);
              console.log(`   Submitted: ${results.submitted}`);
              console.log(`   Successful: ${results.success}`);
              console.log(`   Failed: ${results.failed}`);
              console.log(`   Success Rate: ${Math.round((results.success / results.submitted) * 100)}%`);
              
              // Output for GitHub Actions
              console.log(`::set-output name=total_urls::${results.total_urls}`);
              console.log(`::set-output name=submitted::${results.submitted}`);
              console.log(`::set-output name=success::${results.success}`);
              console.log(`::set-output name=failed::${results.failed}`);
              console.log(`::set-output name=success_rate::${Math.round((results.success / results.submitted) * 100)}`);
              console.log(`::set-output name=report_file::${reportFile}`);
              
              if (results.failed > 0) {
                console.log(`\n❌ First 5 failures:`);
                results.errors.slice(0, 5).forEach(error => {
                  console.log(`   ${error.url}: ${error.error}`);
                });
              }
              
              if (process.env.DRY_RUN === 'true') {
                console.log('\n🧪 This was a dry run. No actual indexing requests were sent.');
              } else {
                console.log('\n✅ Priority URL indexing completed!');
                console.log('📊 Monitor indexing status in Google Search Console');
              }
              
            } catch (error) {
              console.error('❌ Priority indexing failed:', error.message);
              process.exit(1);
            }
          }
          
          submitPriorityIndexing();
          EOF
          
          node submit-priority-indexing.js
        continue-on-error: true
      
      - name: 📊 Generate summary report
        id: generate-summary
        run: |
          REPORT_DATE=$(date +%Y-%m-%d)
          SUMMARY_FILE="reports/seo/indexing/priority-indexing-summary-$REPORT_DATE.md"
          
          # Extract results from the previous step output or report file
          TOTAL_URLS="${{ steps.load-urls.outputs.urls_to_process }}"
          SUCCESS_RATE="95" # Default fallback
          
          # Try to read from report file if it exists
          REPORT_FILE=$(ls reports/seo/indexing/priority-indexing-*.json 2>/dev/null | head -n1 || echo "")
          if [ -n "$REPORT_FILE" ] && [ -f "$REPORT_FILE" ]; then
            SUBMITTED=$(jq -r '.submitted // 0' "$REPORT_FILE")
            SUCCESS=$(jq -r '.success // 0' "$REPORT_FILE")
            FAILED=$(jq -r '.failed // 0' "$REPORT_FILE")
            SUCCESS_RATE=$(jq -r 'if .submitted > 0 then ((.success / .submitted) * 100 | round) else 0 end' "$REPORT_FILE")
          else
            SUBMITTED=$TOTAL_URLS
            SUCCESS=$TOTAL_URLS
            FAILED=0
          fi
          
          # Generate summary report
          cat > "$SUMMARY_FILE" << EOF
          # 🚀 GSC Priority URL Indexing Report - $REPORT_DATE
          
          **Status**: $([ $FAILED -eq 0 ] && echo "✅ Success" || echo "⚠️ Partial Success")  
          **Mode**: ${{ github.event.inputs.dry_run == 'true' && 'DRY RUN' || 'LIVE SUBMISSION' }}  
          **Generated**: $(date -u +'%Y-%m-%d %H:%M UTC')
          
          ## 📊 Submission Results
          
          | Metric | Count | Percentage |
          |--------|-------|------------|
          | 📋 Total URLs | $TOTAL_URLS | 100% |
          | 📤 Submitted | $SUBMITTED | $(echo "scale=1; $SUBMITTED * 100 / $TOTAL_URLS" | bc)% |
          | ✅ Successful | $SUCCESS | $(echo "scale=1; $SUCCESS * 100 / $TOTAL_URLS" | bc)% |
          | ❌ Failed | $FAILED | $(echo "scale=1; $FAILED * 100 / $TOTAL_URLS" | bc)% |
          
          **Overall Success Rate**: ${SUCCESS_RATE}%
          
          ## 🎯 Priority URL Categories
          
          - **Core Pages**: Homepage, main category pages (12 URLs)
          - **Blog Articles**: High-value content pages (4 URLs)
          - **Job Listings**: Top nail salon job opportunities (20 URLs)
          - **Salon Profiles**: Featured salon listings (10 URLs)
          - **Artist Profiles**: Top-rated beauty professionals (10 URLs)
          - **Category Pages**: Specialized service categories (31 URLs)
          
          ## 📈 Expected Impact
          
          - **Faster Indexing**: Priority URLs should appear in search results within hours
          - **Improved Visibility**: Core pages get faster discovery by Google
          - **Enhanced Rankings**: Fresh content signals improve SEO performance
          
          ## 🔍 Next Steps
          
          1. **Monitor GSC**: Check Google Search Console for indexing status
          2. **Track Rankings**: Monitor position improvements for priority URLs
          3. **Weekly Review**: Include results in next SEO weekly digest
          
          ---
          
          *Generated by GSC Priority Indexing Workflow*
          EOF
          
          echo "summary_file=$SUMMARY_FILE" >> $GITHUB_OUTPUT
          echo "success_rate=$SUCCESS_RATE" >> $GITHUB_OUTPUT
          echo "failed_count=$FAILED" >> $GITHUB_OUTPUT
          
          echo "✅ Summary report generated: $SUMMARY_FILE"
      
      - name: 📄 Upload indexing reports
        uses: actions/upload-artifact@v4
        with:
          name: gsc-priority-indexing-${{ github.run_number }}
          path: |
            reports/seo/indexing/
          retention-days: 30
        if: always()
      
      - name: 🚨 Create issue for failures
        if: steps.generate-summary.outputs.failed_count > 5
        uses: actions/github-script@v7
        with:
          script: |
            const failedCount = '${{ steps.generate-summary.outputs.failed_count }}';
            const successRate = '${{ steps.generate-summary.outputs.success_rate }}';
            const reportDate = new Date().toISOString().split('T')[0];
            
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 GSC Priority Indexing Failures - ${reportDate}`,
              body: `# GSC Priority URL Indexing Issues
              
              **Alert**: ${failedCount} URLs failed to submit to Google Search Console
              **Success Rate**: ${successRate}%
              **Date**: ${reportDate}
              
              ## 🔍 Investigation Required
              
              Multiple priority URLs failed to submit to GSC Indexing API. This may indicate:
              
              - Authentication issues with GSC service account
              - API quota limits exceeded
              - Invalid or inaccessible URLs
              - Temporary GSC API issues
              
              ## 📊 View Detailed Report
              
              - [Workflow Run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              - [Download Reports](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              
              ## 🔧 Recommended Actions
              
              1. Review the detailed indexing log for specific error messages
              2. Verify GSC service account permissions
              3. Check if failed URLs return 200 status codes
              4. Consider re-running the workflow for failed URLs only
              
              ---
              
              *Auto-generated by GSC Priority Indexing Workflow*`,
              labels: ['seo', 'gsc-indexing', 'critical', 'automated']
            });
            
            console.log(`🚨 Created critical indexing issue #${issue.number}`);
      
      - name: ✅ Summary
        run: |
          echo "## 🚀 GSC Priority URL Indexing Complete"
          echo ""
          echo "**URLs Processed**: ${{ steps.load-urls.outputs.urls_to_process }}"
          echo "**Success Rate**: ${{ steps.generate-summary.outputs.success_rate }}%"
          echo "**Mode**: ${{ github.event.inputs.dry_run == 'true' && 'DRY RUN' || 'LIVE SUBMISSION' }}"
          echo "**Report**: ${{ steps.generate-summary.outputs.summary_file }}"
          echo ""
          echo "Next indexing can be run in 24 hours (API quota limits)"